/* @generated by lenso-contract-codegen; do not edit. */
import * as lensoContractRuntime from "@lenso/contract-runtime";

export const CAPABILITY_ID = "lenso.agent.session@1";
export const DESCRIPTOR_VERSION = "1.1.0";
export const PORTABLE = true;
export const CROSS_LANE_TRANSFER = false;

export type Int64 = lensoContractRuntime.Int64;
export type Uint64 = lensoContractRuntime.Uint64;
export type Bytes = lensoContractRuntime.Bytes;
export type Timestamp = lensoContractRuntime.Timestamp;
export type Duration = lensoContractRuntime.Duration;
export type OptionalValue<T> = lensoContractRuntime.OptionalValue<T>;
export type InvocationContext = lensoContractRuntime.InvocationContext;
export type RuntimeFailure = lensoContractRuntime.RuntimeFailure;
export type UnknownDomainError = lensoContractRuntime.UnknownDomainError;
export type StreamEvent<Message, DomainError> = lensoContractRuntime.StreamEvent<Message, DomainError>;
export type StreamSession<Message, DomainError> = lensoContractRuntime.StreamSession<Message, DomainError>;

export interface AppendRequest {
  events: Array<AppendRequestEventsItem>;
  expected_revision: Uint64;
  session_id: string;
}

export interface AppendRequestEventsItem {
  event_id: string;
  kind: "session_created" | "turn_started" | "model_requested" | "model_output" | "tool_requested" | "tool_result" | "turn_completed" | "turn_failed" | "turn_cancelled";
  occurred_at: Timestamp;
  payload_json: string;
  turn_id?: string;
}

export interface AppendResponse {
  revision: Uint64;
}

export interface AppendErrorRevisionConflictPayload {
  current_revision: Uint64;
}

export interface OpenRequest {
  session_id?: string;
}

export interface OpenResponse {
  created: boolean;
  revision: Uint64;
  session_id: string;
}

export interface ReadRequest {
  after_revision: Uint64;
  limit: number;
  session_id: string;
}

export interface ReadResponse {
  events: Array<ReadResponseEventsItem>;
  revision: Uint64;
  session_id: string;
}

export interface ReadResponseEventsItem {
  event_id: string;
  kind: "session_created" | "turn_started" | "model_requested" | "model_output" | "tool_requested" | "tool_result" | "turn_completed" | "turn_failed" | "turn_cancelled";
  occurred_at: Timestamp;
  payload_json: string;
  revision: Uint64;
  turn_id?: string;
}

export type AppendError = "invalid_event" | "not_found" | { readonly code: "revision_conflict"; readonly payload: AppendErrorRevisionConflictPayload } | UnknownDomainError;
export type AppendInvocationError = { readonly kind: "domain"; readonly error: AppendError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type AppendResult = { readonly ok: true; readonly value: AppendResponse } | { readonly ok: false; readonly error: AppendInvocationError };
export type OpenError = "invalid_session_id" | "not_found" | UnknownDomainError;
export type OpenInvocationError = { readonly kind: "domain"; readonly error: OpenError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type OpenResult = { readonly ok: true; readonly value: OpenResponse } | { readonly ok: false; readonly error: OpenInvocationError };
export type ReadError = "invalid_cursor" | "not_found" | UnknownDomainError;
export type ReadInvocationError = { readonly kind: "domain"; readonly error: ReadError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type ReadResult = { readonly ok: true; readonly value: ReadResponse } | { readonly ok: false; readonly error: ReadInvocationError };
export function encodeAppendRequest(value: AppendRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeAppendRequest(wire: string): AppendRequest { return lensoContractRuntime.decodePortableJson<AppendRequest>(wire); }
export function encodeAppendResponse(value: AppendResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeAppendResponse(wire: string): AppendResponse { return lensoContractRuntime.decodePortableJson<AppendResponse>(wire); }
export function encodeAppendError(value: AppendError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeAppendError(wire: string): AppendError { return lensoContractRuntime.decodeDomainError<AppendError>(wire, ["invalid_event", "not_found"]); }

export function encodeOpenRequest(value: OpenRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeOpenRequest(wire: string): OpenRequest { return lensoContractRuntime.decodePortableJson<OpenRequest>(wire); }
export function encodeOpenResponse(value: OpenResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeOpenResponse(wire: string): OpenResponse { return lensoContractRuntime.decodePortableJson<OpenResponse>(wire); }
export function encodeOpenError(value: OpenError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeOpenError(wire: string): OpenError { return lensoContractRuntime.decodeDomainError<OpenError>(wire, ["invalid_session_id", "not_found"]); }

export function encodeReadRequest(value: ReadRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeReadRequest(wire: string): ReadRequest { return lensoContractRuntime.decodePortableJson<ReadRequest>(wire); }
export function encodeReadResponse(value: ReadResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeReadResponse(wire: string): ReadResponse { return lensoContractRuntime.decodePortableJson<ReadResponse>(wire); }
export function encodeReadError(value: ReadError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeReadError(wire: string): ReadError { return lensoContractRuntime.decodeDomainError<ReadError>(wire, ["invalid_cursor", "not_found"]); }


export interface SessionClient {
  append(request: AppendRequest, context?: InvocationContext): Promise<AppendResult>;
  open(request: OpenRequest, context?: InvocationContext): Promise<OpenResult>;
  read(request: ReadRequest, context?: InvocationContext): Promise<ReadResult>;
}

export interface SessionProvider {
  append(context: InvocationContext, request: AppendRequest): Promise<AppendResult>;
  open(context: InvocationContext, request: OpenRequest): Promise<OpenResult>;
  read(context: InvocationContext, request: ReadRequest): Promise<ReadResult>;
}

export type ProviderDispatchOutcome =
  | { readonly kind: "success"; readonly value: unknown }
  | { readonly kind: "domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };

export interface CapabilityProviderDescriptor {
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly operations: ReadonlyArray<string>;
  readonly stream_operations: ReadonlyArray<string>;
  readonly event_operations: ReadonlyArray<string>;
}

export interface CapabilityProviderBinding {
  readonly descriptor: CapabilityProviderDescriptor;
  invokeRequest(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderDispatchOutcome>;
}

function providerErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export function bindSessionProvider(
  provider: SessionProvider,
): CapabilityProviderBinding {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["append", "open", "read"],
      stream_operations: [],
      event_operations: [],
    },
    async invokeRequest(operation, context, payload) {
      switch (operation) {
      case "append": {
        let request: AppendRequest;
        try {
          request = decodeAppendRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.append(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeAppendResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeAppendError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "module_failure", detail: providerErrorMessage(error) } };
        }
      }
      case "open": {
        let request: OpenRequest;
        try {
          request = decodeOpenRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.open(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeOpenResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeOpenError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "module_failure", detail: providerErrorMessage(error) } };
        }
      }
      case "read": {
        let request: ReadRequest;
        try {
          request = decodeReadRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.read(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeReadResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeReadError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "module_failure", detail: providerErrorMessage(error) } };
        }
      }
        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
  };
}

export type Provider = SessionProvider;
export const bindProvider = bindSessionProvider;

export const portableValueProfile = lensoContractRuntime.portableValueProfile;
