/* @generated by lenso-contract-codegen; do not edit. */
import * as lensoContractRuntime from "@lenso/contract-runtime";

export const CAPABILITY_ID = "lenso.agent.session@1";
export const DESCRIPTOR_VERSION = "1.1.0";
export const DESCRIPTOR_DIGEST = "sha256:59e3fa78ae7b6f5c3a683210053a9916fa4a6c8d7b9fbc70c452d82891e5e063";
export const PORTABLE = true;
export const CROSS_LANE_TRANSFER = false;

export type Int64 = lensoContractRuntime.Int64;
export type Uint64 = lensoContractRuntime.Uint64;
export type Bytes = lensoContractRuntime.Bytes;
export type Timestamp = lensoContractRuntime.Timestamp;
export type Duration = lensoContractRuntime.Duration;
export type OptionalValue<T> = lensoContractRuntime.OptionalValue<T>;
export type InvocationContext = lensoContractRuntime.InvocationContext;
export type RuntimeFailure = lensoContractRuntime.RuntimeFailure;
export type UnknownDomainError = lensoContractRuntime.UnknownDomainError;
export type StreamEvent<Message, DomainError> = lensoContractRuntime.StreamEvent<Message, DomainError>;
export type StreamSession<Message, DomainError> = lensoContractRuntime.StreamSession<Message, DomainError>;

export interface CapabilityContractReference<Client, Provider extends object> extends CapabilityDependencyBinding<Client> {
  readonly kind: "lenso.capability";
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly descriptor_digest: string;
  readonly generated_client: string;
  readonly descriptor: CapabilityProviderDescriptor;
  bindProvider(provider: Provider): CapabilityProviderBinding;
  required(id?: string): CapabilityDependencyDeclaration<Client, "one">;
  optional(id?: string): CapabilityDependencyDeclaration<Client, "optional">;
  many(id?: string): CapabilityDependencyDeclaration<Client, "many">;
  readonly __client?: Client;
  readonly __provider?: Provider;
}

export interface AppendSessionRequest {
  events: Array<AppendSessionRequestEventsItem>;
  expected_revision: Uint64;
  session_id: string;
}

export interface AppendSessionRequestEventsItem {
  event_id: string;
  kind: "session_created" | "turn_started" | "model_requested" | "model_output" | "tool_requested" | "tool_result" | "turn_completed" | "turn_failed" | "turn_cancelled";
  occurred_at: Timestamp;
  payload_json: string;
  turn_id?: string;
}

export interface AppendSessionResponse {
  revision: Uint64;
}

export interface AppendErrorRevisionConflictPayload {
  current_revision: Uint64;
}

export interface OpenSessionRequest {
  session_id?: string;
}

export interface OpenSessionResponse {
  created: boolean;
  revision: Uint64;
  session_id: string;
}

export interface ReadSessionRequest {
  after_revision: Uint64;
  limit: number;
  session_id: string;
}

export interface ReadSessionResponse {
  events: Array<ReadSessionResponseEventsItem>;
  revision: Uint64;
  session_id: string;
}

export interface ReadSessionResponseEventsItem {
  event_id: string;
  kind: "session_created" | "turn_started" | "model_requested" | "model_output" | "tool_requested" | "tool_result" | "turn_completed" | "turn_failed" | "turn_cancelled";
  occurred_at: Timestamp;
  payload_json: string;
  revision: Uint64;
  turn_id?: string;
}

export type AppendError = "invalid_event" | "not_found" | { readonly code: "revision_conflict"; readonly payload: AppendErrorRevisionConflictPayload } | UnknownDomainError;
export type AppendInvocationError = { readonly kind: "domain"; readonly error: AppendError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type AppendResult = { readonly ok: true; readonly value: AppendSessionResponse } | { readonly ok: false; readonly error: AppendInvocationError };
export type OpenError = "invalid_session_id" | "not_found" | UnknownDomainError;
export type OpenInvocationError = { readonly kind: "domain"; readonly error: OpenError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type OpenResult = { readonly ok: true; readonly value: OpenSessionResponse } | { readonly ok: false; readonly error: OpenInvocationError };
export type ReadError = "invalid_cursor" | "not_found" | UnknownDomainError;
export type ReadInvocationError = { readonly kind: "domain"; readonly error: ReadError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type ReadResult = { readonly ok: true; readonly value: ReadSessionResponse } | { readonly ok: false; readonly error: ReadInvocationError };
export function encodeAppendRequest(value: AppendSessionRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeAppendRequest(wire: string): AppendSessionRequest { return lensoContractRuntime.decodePortableJson<AppendSessionRequest>(wire); }
export function encodeAppendResponse(value: AppendSessionResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeAppendResponse(wire: string): AppendSessionResponse { return lensoContractRuntime.decodePortableJson<AppendSessionResponse>(wire); }
export function encodeAppendError(value: AppendError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeAppendError(wire: string): AppendError { return lensoContractRuntime.decodeDomainError<AppendError>(wire, ["invalid_event", "not_found"]); }

export function encodeOpenRequest(value: OpenSessionRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeOpenRequest(wire: string): OpenSessionRequest { return lensoContractRuntime.decodePortableJson<OpenSessionRequest>(wire); }
export function encodeOpenResponse(value: OpenSessionResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeOpenResponse(wire: string): OpenSessionResponse { return lensoContractRuntime.decodePortableJson<OpenSessionResponse>(wire); }
export function encodeOpenError(value: OpenError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeOpenError(wire: string): OpenError { return lensoContractRuntime.decodeDomainError<OpenError>(wire, ["invalid_session_id", "not_found"]); }

export function encodeReadRequest(value: ReadSessionRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeReadRequest(wire: string): ReadSessionRequest { return lensoContractRuntime.decodePortableJson<ReadSessionRequest>(wire); }
export function encodeReadResponse(value: ReadSessionResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeReadResponse(wire: string): ReadSessionResponse { return lensoContractRuntime.decodePortableJson<ReadSessionResponse>(wire); }
export function encodeReadError(value: ReadError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeReadError(wire: string): ReadError { return lensoContractRuntime.decodeDomainError<ReadError>(wire, ["invalid_cursor", "not_found"]); }


export interface SessionClient {
  append(request: AppendSessionRequest, context?: InvocationContext): Promise<AppendResult>;
  open(request: OpenSessionRequest, context?: InvocationContext): Promise<OpenResult>;
  read(request: ReadSessionRequest, context?: InvocationContext): Promise<ReadResult>;
}

export interface SessionProvider {
  append(context: InvocationContext, request: AppendSessionRequest): Promise<AppendResult>;
  open(context: InvocationContext, request: OpenSessionRequest): Promise<OpenResult>;
  read(context: InvocationContext, request: ReadSessionRequest): Promise<ReadResult>;
}

export const Session: CapabilityContractReference<SessionClient, SessionProvider> = { kind: "lenso.capability", ...bindSessionDependency(), capability_id: CAPABILITY_ID, descriptor_version: DESCRIPTOR_VERSION, descriptor_digest: DESCRIPTOR_DIGEST, generated_client: "SessionClient", descriptor: { capability_id: CAPABILITY_ID, descriptor_version: DESCRIPTOR_VERSION, operations: ["append", "open", "read"], stream_operations: [], event_operations: [] }, bindProvider: bindSessionProvider, required(id) { return { kind: "lenso.dependency", ...(id === undefined ? {} : { id }), contract: this, cardinality: "one" }; }, optional(id) { return { kind: "lenso.dependency", ...(id === undefined ? {} : { id }), contract: this, cardinality: "optional" }; }, many(id) { return { kind: "lenso.dependency", ...(id === undefined ? {} : { id }), contract: this, cardinality: "many" }; }, };
export const SESSION_CONTRACT = Session;

export type ProviderDispatchOutcome =
  | { readonly kind: "success"; readonly value: unknown }
  | { readonly kind: "domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
export type ProviderStreamActionOutcome =
  | { readonly kind: "accepted" }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
export type ProviderStreamReceiveOutcome =
  | { readonly kind: "message"; readonly value: unknown }
  | { readonly kind: "peer_half_closed" }
  | { readonly kind: "terminal_success" }
  | { readonly kind: "terminal_domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
/** @internal Runtime lowering seam. */
export interface ProviderStreamSessionBinding {
  send(message: unknown): Promise<ProviderStreamActionOutcome>;
  receive(): Promise<ProviderStreamReceiveOutcome>;
  closeSend(): Promise<ProviderStreamActionOutcome>;
  cancel(): void;
}
export type ProviderStreamOpenOutcome =
  | { readonly kind: "opened"; readonly stream: ProviderStreamSessionBinding }
  | { readonly kind: "domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
export type ProviderEventPublishOutcome =
  | { readonly kind: "accepted" }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };

export interface CapabilityProviderDescriptor {
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly operations: ReadonlyArray<string>;
  readonly stream_operations: ReadonlyArray<string>;
  readonly event_operations: ReadonlyArray<string>;
}

/** @internal Runtime lowering seam. */
export interface CapabilityProviderBinding {
  readonly descriptor: CapabilityProviderDescriptor;
  invokeRequest(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderDispatchOutcome>;
  openStream(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderStreamOpenOutcome>;
  publishEvent(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderEventPublishOutcome>;
}

function providerErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export function bindSessionProvider(
  provider: SessionProvider,
): CapabilityProviderBinding {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["append", "open", "read"],
      stream_operations: [],
      event_operations: [],
    },
    async invokeRequest(operation, context, payload) {
      switch (operation) {
      case "append": {
        let request: AppendSessionRequest;
        try {
          request = decodeAppendRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.append(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeAppendResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeAppendError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
        }
      }
      case "open": {
        let request: OpenSessionRequest;
        try {
          request = decodeOpenRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.open(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeOpenResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeOpenError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
        }
      }
      case "read": {
        let request: ReadSessionRequest;
        try {
          request = decodeReadRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.read(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeReadResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeReadError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
        }
      }
        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
    async openStream(operation, context, payload) {
      switch (operation) {

        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
    async publishEvent(operation, context, payload) {
      switch (operation) {

        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
  };
}

export type Provider = SessionProvider;
export const bindProvider = bindSessionProvider;

export type DependencyInvoker = (
  operation: string,
  context: InvocationContext,
  payload: unknown,
) => Promise<ProviderDispatchOutcome>;

export interface CapabilityDependencyBinding<Client> {
  readonly descriptor: CapabilityProviderDescriptor;
  createClient(invoke: DependencyInvoker): Client;
}

export interface CapabilityDependencyDeclaration<Client, Cardinality extends "one" | "optional" | "many"> {
  readonly kind: "lenso.dependency";
  readonly id?: string;
  readonly contract: CapabilityDependencyBinding<Client>;
  readonly cardinality: Cardinality;
}

function dependencyErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export function bindSessionDependency(): CapabilityDependencyBinding<SessionClient> {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["append", "open", "read"],
      stream_operations: [],
      event_operations: [],
    },
    createClient(invoke) {
      return {
      async append(request, context) {
        let payload: unknown;
        try {
          payload = JSON.parse(encodeAppendRequest(request)) as unknown;
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "protocol_violation", detail: dependencyErrorMessage(error) } } };
        }
        const call = context ?? { requestId: "0" as Uint64, cancelled: false };
        try {
          const outcome = await invoke("append", call, payload);
          if (outcome.kind === "success") {
            return { ok: true, value: decodeAppendResponse(JSON.stringify(outcome.value)) };
          }
          if (outcome.kind === "domain") {
            return { ok: false, error: { kind: "domain", error: decodeAppendError(JSON.stringify(outcome.value)) } };
          }
          return { ok: false, error: { kind: "runtime", error: outcome.failure } };
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "plugin_failure", detail: dependencyErrorMessage(error) } } };
        }
      },
      async open(request, context) {
        let payload: unknown;
        try {
          payload = JSON.parse(encodeOpenRequest(request)) as unknown;
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "protocol_violation", detail: dependencyErrorMessage(error) } } };
        }
        const call = context ?? { requestId: "0" as Uint64, cancelled: false };
        try {
          const outcome = await invoke("open", call, payload);
          if (outcome.kind === "success") {
            return { ok: true, value: decodeOpenResponse(JSON.stringify(outcome.value)) };
          }
          if (outcome.kind === "domain") {
            return { ok: false, error: { kind: "domain", error: decodeOpenError(JSON.stringify(outcome.value)) } };
          }
          return { ok: false, error: { kind: "runtime", error: outcome.failure } };
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "plugin_failure", detail: dependencyErrorMessage(error) } } };
        }
      },
      async read(request, context) {
        let payload: unknown;
        try {
          payload = JSON.parse(encodeReadRequest(request)) as unknown;
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "protocol_violation", detail: dependencyErrorMessage(error) } } };
        }
        const call = context ?? { requestId: "0" as Uint64, cancelled: false };
        try {
          const outcome = await invoke("read", call, payload);
          if (outcome.kind === "success") {
            return { ok: true, value: decodeReadResponse(JSON.stringify(outcome.value)) };
          }
          if (outcome.kind === "domain") {
            return { ok: false, error: { kind: "domain", error: decodeReadError(JSON.stringify(outcome.value)) } };
          }
          return { ok: false, error: { kind: "runtime", error: outcome.failure } };
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "plugin_failure", detail: dependencyErrorMessage(error) } } };
        }
      },
      };
    },
  };
}

export const bindDependency = bindSessionDependency;

export const portableValueProfile = lensoContractRuntime.portableValueProfile;
