/* @generated by lenso-contract-codegen; do not edit. */
import * as lensoContractRuntime from "@lenso/contract-runtime";

export const CAPABILITY_ID = "lenso.agent@1";
export const DESCRIPTOR_VERSION = "1.1.0";
export const PORTABLE = true;
export const CROSS_LANE_TRANSFER = false;

export type Int64 = lensoContractRuntime.Int64;
export type Uint64 = lensoContractRuntime.Uint64;
export type Bytes = lensoContractRuntime.Bytes;
export type Timestamp = lensoContractRuntime.Timestamp;
export type Duration = lensoContractRuntime.Duration;
export type OptionalValue<T> = lensoContractRuntime.OptionalValue<T>;
export type InvocationContext = lensoContractRuntime.InvocationContext;
export type RuntimeFailure = lensoContractRuntime.RuntimeFailure;
export type UnknownDomainError = lensoContractRuntime.UnknownDomainError;
export type StreamEvent<Message, DomainError> = lensoContractRuntime.StreamEvent<Message, DomainError>;
export type StreamSession<Message, DomainError> = lensoContractRuntime.StreamSession<Message, DomainError>;

export interface RunTurnRequest {
  input: string;
  session_id?: string;
}

export interface RunTurnResponse {
  sequence: Uint64;
  session_id?: string;
  text: string;
}

export type RunTurnError = "concurrent_turn" | "context_limit_exceeded" | "invalid_session" | "step_limit_exceeded" | "tool_call_limit_exceeded" | UnknownDomainError;
export type RunTurnInvocationError = { readonly kind: "domain"; readonly error: RunTurnError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type RunTurnResult = { readonly ok: true; readonly value: StreamSession<RunTurnResponse, RunTurnError> } | { readonly ok: false; readonly error: RunTurnInvocationError };
export function encodeRunTurnRequest(value: RunTurnRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeRunTurnRequest(wire: string): RunTurnRequest { return lensoContractRuntime.decodePortableJson<RunTurnRequest>(wire); }
export function encodeRunTurnResponse(value: RunTurnResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeRunTurnResponse(wire: string): RunTurnResponse { return lensoContractRuntime.decodePortableJson<RunTurnResponse>(wire); }
export function encodeRunTurnError(value: RunTurnError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeRunTurnError(wire: string): RunTurnError { return lensoContractRuntime.decodeDomainError<RunTurnError>(wire, ["concurrent_turn", "context_limit_exceeded", "invalid_session", "step_limit_exceeded", "tool_call_limit_exceeded"]); }


export interface AgentClient {
  run_turn(request: RunTurnRequest, context?: InvocationContext): Promise<RunTurnResult>;
}

export interface AgentProvider {
  run_turn(context: InvocationContext, request: RunTurnRequest): Promise<RunTurnResult>;
}

export type ProviderDispatchOutcome =
  | { readonly kind: "success"; readonly value: unknown }
  | { readonly kind: "domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };

export interface CapabilityProviderDescriptor {
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly operations: ReadonlyArray<string>;
  readonly stream_operations: ReadonlyArray<string>;
  readonly event_operations: ReadonlyArray<string>;
}

export interface CapabilityProviderBinding {
  readonly descriptor: CapabilityProviderDescriptor;
  invokeRequest(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderDispatchOutcome>;
}

function providerErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export function bindAgentProvider(
  provider: AgentProvider,
): CapabilityProviderBinding {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["run_turn"],
      stream_operations: ["run_turn"],
      event_operations: [],
    },
    async invokeRequest(operation, context, payload) {
      switch (operation) {

        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
  };
}

export type Provider = AgentProvider;
export const bindProvider = bindAgentProvider;

export const portableValueProfile = lensoContractRuntime.portableValueProfile;
