/* @generated by lenso-contract-codegen; do not edit. */
import * as lensoContractRuntime from "@lenso/contract-runtime";

export const CAPABILITY_ID = "lenso.agent.model@1";
export const DESCRIPTOR_VERSION = "1.1.0";
export const PORTABLE = true;
export const CROSS_LANE_TRANSFER = false;

export type Int64 = lensoContractRuntime.Int64;
export type Uint64 = lensoContractRuntime.Uint64;
export type Bytes = lensoContractRuntime.Bytes;
export type Timestamp = lensoContractRuntime.Timestamp;
export type Duration = lensoContractRuntime.Duration;
export type OptionalValue<T> = lensoContractRuntime.OptionalValue<T>;
export type InvocationContext = lensoContractRuntime.InvocationContext;
export type RuntimeFailure = lensoContractRuntime.RuntimeFailure;
export type UnknownDomainError = lensoContractRuntime.UnknownDomainError;
export type StreamEvent<Message, DomainError> = lensoContractRuntime.StreamEvent<Message, DomainError>;
export type StreamSession<Message, DomainError> = lensoContractRuntime.StreamSession<Message, DomainError>;

export interface CompleteRequest {
  max_output_tokens: number;
  messages: Array<CompleteRequestMessagesItem>;
  model: string;
  temperature: number;
  tools: Array<CompleteRequestToolsItem>;
}

export interface CompleteRequestMessagesItem {
  arguments_json?: string;
  content: string;
  role: "system" | "user" | "assistant" | "tool";
  tool_call_id?: string;
  tool_name?: string;
}

export interface CompleteRequestToolsItem {
  description: string;
  input_schema_json: string;
  name: string;
}

export interface CompleteResponse {
  arguments_json: string;
  input_tokens: Uint64;
  kind: "text_delta" | "tool_call" | "usage";
  output_tokens: Uint64;
  sequence: Uint64;
  text: string;
  tool_call_id: string;
  tool_name: string;
}

export type CompleteError = "content_rejected" | "invalid_request" | "unsupported_model" | UnknownDomainError;
export type CompleteInvocationError = { readonly kind: "domain"; readonly error: CompleteError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type CompleteResult = { readonly ok: true; readonly value: StreamSession<CompleteResponse, CompleteError> } | { readonly ok: false; readonly error: CompleteInvocationError };
export function encodeCompleteRequest(value: CompleteRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeCompleteRequest(wire: string): CompleteRequest { return lensoContractRuntime.decodePortableJson<CompleteRequest>(wire); }
export function encodeCompleteResponse(value: CompleteResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeCompleteResponse(wire: string): CompleteResponse { return lensoContractRuntime.decodePortableJson<CompleteResponse>(wire); }
export function encodeCompleteError(value: CompleteError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeCompleteError(wire: string): CompleteError { return lensoContractRuntime.decodeDomainError<CompleteError>(wire, ["content_rejected", "invalid_request", "unsupported_model"]); }


export interface ModelClient {
  complete(request: CompleteRequest, context?: InvocationContext): Promise<CompleteResult>;
}

export interface ModelProvider {
  complete(context: InvocationContext, request: CompleteRequest): Promise<CompleteResult>;
}

export type ProviderDispatchOutcome =
  | { readonly kind: "success"; readonly value: unknown }
  | { readonly kind: "domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };

export interface CapabilityProviderDescriptor {
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly operations: ReadonlyArray<string>;
  readonly stream_operations: ReadonlyArray<string>;
  readonly event_operations: ReadonlyArray<string>;
}

export interface CapabilityProviderBinding {
  readonly descriptor: CapabilityProviderDescriptor;
  invokeRequest(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderDispatchOutcome>;
}

function providerErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export function bindModelProvider(
  provider: ModelProvider,
): CapabilityProviderBinding {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["complete"],
      stream_operations: ["complete"],
      event_operations: [],
    },
    async invokeRequest(operation, context, payload) {
      switch (operation) {

        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
  };
}

export type Provider = ModelProvider;
export const bindProvider = bindModelProvider;

export const portableValueProfile = lensoContractRuntime.portableValueProfile;
