/* @generated by lenso-contract-codegen; do not edit. */
import * as lensoContractRuntime from "@lenso/contract-runtime";

export const CAPABILITY_ID = "lenso.agent.model@1";
export const DESCRIPTOR_VERSION = "1.1.0";
export const DESCRIPTOR_DIGEST = "sha256:92b4efa0015a8fd88bf5fe179091d0201bca9557c0cd76a68c5bc0e0de7d5d64";
export const PORTABLE = true;
export const CROSS_LANE_TRANSFER = false;

export type Int64 = lensoContractRuntime.Int64;
export type Uint64 = lensoContractRuntime.Uint64;
export type Bytes = lensoContractRuntime.Bytes;
export type Timestamp = lensoContractRuntime.Timestamp;
export type Duration = lensoContractRuntime.Duration;
export type OptionalValue<T> = lensoContractRuntime.OptionalValue<T>;
export type InvocationContext = lensoContractRuntime.InvocationContext;
export type RuntimeFailure = lensoContractRuntime.RuntimeFailure;
export type UnknownDomainError = lensoContractRuntime.UnknownDomainError;
export type StreamEvent<Message, DomainError> = lensoContractRuntime.StreamEvent<Message, DomainError>;
export type StreamSession<Message, DomainError> = lensoContractRuntime.StreamSession<Message, DomainError>;

export type ProviderStream<Message, DomainError> = StreamSession<Message, DomainError> | AsyncIterable<Message>;

class ServerOutputStreamInputError extends Error {}

function isAsyncIterable<Message>(value: unknown): value is AsyncIterable<Message> {
  return typeof value === "object" && value !== null && Symbol.asyncIterator in value;
}

function lowerProviderStream<Message, DomainError>(stream: ProviderStream<Message, DomainError>): StreamSession<Message, DomainError> {
  if (!isAsyncIterable<Message>(stream)) return stream;
  const iterator = stream[Symbol.asyncIterator]();
  let cancelled = false;
  return {
    async send() { throw new ServerOutputStreamInputError("server-output stream does not accept inbound messages"); },
    async receive() {
      if (cancelled) return { kind: "terminal", outcome: { ok: true } };
      const next = await iterator.next();
      return next.done
        ? { kind: "terminal", outcome: { ok: true } }
        : { kind: "message", message: next.value };
    },
    async closeSend() {},
    cancel() {
      cancelled = true;
      const closing = iterator.return?.();
      if (closing !== undefined) void Promise.resolve(closing).catch(() => undefined);
    },
  };
}

export interface CapabilityContractReference<Client, Provider extends object, Runtime extends DependencyInvoker = DependencyInvoker> extends CapabilityDependencyBinding<Client, Runtime> {
  readonly kind: "lenso.capability";
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly descriptor_digest: string;
  readonly generated_client: string;
  readonly descriptor: CapabilityProviderDescriptor;
  bindProvider(provider: Provider): CapabilityProviderBinding;
  required(id?: string): CapabilityDependencyDeclaration<Client, "one", Runtime>;
  optional(id?: string): CapabilityDependencyDeclaration<Client, "optional", Runtime>;
  many(id?: string): CapabilityDependencyDeclaration<Client, "many", Runtime>;
  readonly __client?: Client;
  readonly __provider?: Provider;
}

export interface CompleteRequest {
  max_output_tokens: number;
  messages: Array<CompleteRequestMessagesItem>;
  model: string;
  temperature: number;
  tools: Array<CompleteRequestToolsItem>;
}

export interface CompleteRequestMessagesItem {
  arguments_json?: string;
  content: string;
  role: "system" | "user" | "assistant" | "tool";
  tool_call_id?: string;
  tool_name?: string;
}

export interface CompleteRequestToolsItem {
  description: string;
  input_schema_json: string;
  name: string;
}

export interface CompleteResponse {
  arguments_json: string;
  input_tokens: Uint64;
  kind: "text_delta" | "tool_call" | "usage";
  output_tokens: Uint64;
  sequence: Uint64;
  text: string;
  tool_call_id: string;
  tool_name: string;
}

export type CompleteError = "content_rejected" | "invalid_request" | "unsupported_model" | UnknownDomainError;
export type CompleteInvocationError = { readonly kind: "domain"; readonly error: CompleteError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type CompleteResult = { readonly ok: true; readonly value: StreamSession<CompleteResponse, CompleteError> } | { readonly ok: false; readonly error: CompleteInvocationError };
export type CompleteProviderResult = { readonly ok: true; readonly value: ProviderStream<CompleteResponse, CompleteError> } | { readonly ok: false; readonly error: CompleteInvocationError };
export type CompleteProviderOutput = AsyncIterable<CompleteResponse> | CompleteProviderResult | Promise<CompleteProviderResult>;
export function encodeCompleteRequest(value: CompleteRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeCompleteRequest(wire: string): CompleteRequest { return lensoContractRuntime.decodePortableJson<CompleteRequest>(wire); }
export function encodeCompleteResponse(value: CompleteResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeCompleteResponse(wire: string): CompleteResponse { return lensoContractRuntime.decodePortableJson<CompleteResponse>(wire); }
export function encodeCompleteError(value: CompleteError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeCompleteError(wire: string): CompleteError { return lensoContractRuntime.decodeDomainError<CompleteError>(wire, ["content_rejected", "invalid_request", "unsupported_model"]); }


export interface ModelClient {
  complete(request: CompleteRequest, context?: InvocationContext): Promise<CompleteResult>;
}

export interface ModelProvider {
  complete(context: InvocationContext, request: CompleteRequest): CompleteProviderOutput;
}

export const Model: CapabilityContractReference<ModelClient, ModelProvider, InteractionDependencyInvoker> = { kind: "lenso.capability", ...bindModelDependency(), capability_id: CAPABILITY_ID, descriptor_version: DESCRIPTOR_VERSION, descriptor_digest: DESCRIPTOR_DIGEST, generated_client: "ModelClient", descriptor: { capability_id: CAPABILITY_ID, descriptor_version: DESCRIPTOR_VERSION, operations: ["complete"], stream_operations: ["complete"], event_operations: [] }, bindProvider: bindModelProvider, required(id) { return { kind: "lenso.dependency", ...(id === undefined ? {} : { id }), contract: this, cardinality: "one" }; }, optional(id) { return { kind: "lenso.dependency", ...(id === undefined ? {} : { id }), contract: this, cardinality: "optional" }; }, many(id) { return { kind: "lenso.dependency", ...(id === undefined ? {} : { id }), contract: this, cardinality: "many" }; }, };
export const MODEL_CONTRACT = Model;

export type ProviderDispatchOutcome =
  | { readonly kind: "success"; readonly value: unknown }
  | { readonly kind: "domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
export type ProviderStreamActionOutcome =
  | { readonly kind: "accepted" }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
export type ProviderStreamReceiveOutcome =
  | { readonly kind: "message"; readonly value: unknown }
  | { readonly kind: "peer_half_closed" }
  | { readonly kind: "terminal_success" }
  | { readonly kind: "terminal_domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
/** @internal Runtime lowering seam. */
export interface ProviderStreamSessionBinding {
  send(message: unknown): Promise<ProviderStreamActionOutcome>;
  receive(): Promise<ProviderStreamReceiveOutcome>;
  closeSend(): Promise<ProviderStreamActionOutcome>;
  cancel(): void;
}
export type ProviderStreamOpenOutcome =
  | { readonly kind: "opened"; readonly stream: ProviderStreamSessionBinding }
  | { readonly kind: "domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
export type ProviderEventPublishOutcome =
  | { readonly kind: "accepted" }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };

export interface CapabilityProviderDescriptor {
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly operations: ReadonlyArray<string>;
  readonly stream_operations: ReadonlyArray<string>;
  readonly event_operations: ReadonlyArray<string>;
}

/** @internal Runtime lowering seam. */
export interface CapabilityProviderBinding {
  readonly descriptor: CapabilityProviderDescriptor;
  invokeRequest(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderDispatchOutcome>;
  openStream(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderStreamOpenOutcome>;
  publishEvent(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderEventPublishOutcome>;
}

function providerErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export function bindModelProvider(
  provider: ModelProvider,
): CapabilityProviderBinding {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["complete"],
      stream_operations: ["complete"],
      event_operations: [],
    },
    async invokeRequest(operation, context, payload) {
      switch (operation) {

        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
    async openStream(operation, context, payload) {
      switch (operation) {
      case "complete": {
        let request: CompleteRequest;
        try {
          request = decodeCompleteRequest(lensoContractRuntime.encodePortableJson(payload, "stream open request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const provided = provider.complete(context, request);
          const result = isAsyncIterable<CompleteResponse>(provided)
            ? { ok: true as const, value: provided }
            : await provided;
          if (!result.ok) {
            if (result.error.kind === "domain") {
              return { kind: "domain", value: JSON.parse(encodeCompleteError(result.error.error)) as unknown };
            }
            return { kind: "runtime", failure: result.error.error };
          }
          const stream = lowerProviderStream(result.value);
          const binding: ProviderStreamSessionBinding = {
            async send(message) {
              let decoded: CompleteResponse;
              try {
                decoded = decodeCompleteResponse(lensoContractRuntime.encodePortableJson(message, "stream message"));
              } catch (error) {
                return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
              }
              try {
                await stream.send(decoded);
                return { kind: "accepted" };
              } catch (error) {
                return { kind: "runtime", failure: error instanceof ServerOutputStreamInputError
                  ? { kind: "protocol_violation", detail: providerErrorMessage(error) }
                  : { kind: "plugin_failure", detail: providerErrorMessage(error) } };
              }
            },
            async receive() {
              try {
                const event = await stream.receive();
                if (event.kind === "message") {
                  return { kind: "message", value: JSON.parse(encodeCompleteResponse(event.message)) as unknown };
                }
                if (event.kind === "peer_half_closed") return { kind: "peer_half_closed" };
                if (event.outcome.ok) return { kind: "terminal_success" };
                return { kind: "terminal_domain", value: JSON.parse(encodeCompleteError(event.outcome.error)) as unknown };
              } catch (error) {
                return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
              }
            },
            async closeSend() {
              try {
                await stream.closeSend();
                return { kind: "accepted" };
              } catch (error) {
                return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
              }
            },
            cancel() { stream.cancel(); },
          };
          return { kind: "opened", stream: binding };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
        }
      }
        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
    async publishEvent(operation, context, payload) {
      switch (operation) {

        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
  };
}

export type Provider = ModelProvider;
export const bindProvider = bindModelProvider;

export type DependencyInvoker = (
  operation: string,
  context: InvocationContext,
  payload: unknown,
) => Promise<ProviderDispatchOutcome>;

export type InteractionDependencyInvoker = DependencyInvoker & {
  readonly providerInstance: string;
  openStream(operation: string, context: InvocationContext, payload: unknown): Promise<ProviderStreamOpenOutcome>;
  publishEvent(operation: string, context: InvocationContext, payload: unknown): Promise<ProviderEventPublishOutcome>;
};

export interface CapabilityDependencyBinding<Client, Runtime extends DependencyInvoker = DependencyInvoker> {
  readonly descriptor: CapabilityProviderDescriptor;
  createClient(invoke: Runtime): Client;
}

export interface CapabilityDependencyDeclaration<Client, Cardinality extends "one" | "optional" | "many", Runtime extends DependencyInvoker = DependencyInvoker> {
  readonly kind: "lenso.dependency";
  readonly id?: string;
  readonly contract: CapabilityDependencyBinding<Client, Runtime>;
  readonly cardinality: Cardinality;
}

function dependencyErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function dependencyRuntimeError(failure: RuntimeFailure): Error {
  return Object.assign(new Error(`Capability dependency failed: ${failure.kind}`), { failure });
}

function dependencyFailure(error: unknown): RuntimeFailure {
  if (typeof error === "object" && error !== null && "failure" in error) return (error as { failure: RuntimeFailure }).failure;
  return { kind: "plugin_failure", detail: dependencyErrorMessage(error) };
}

export function bindModelDependency(): CapabilityDependencyBinding<ModelClient, InteractionDependencyInvoker> {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["complete"],
      stream_operations: ["complete"],
      event_operations: [],
    },
    createClient(invoke) {
      return {
      async complete(request, context) {
        let payload: unknown;
        try {
          payload = JSON.parse(encodeCompleteRequest(request)) as unknown;
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "protocol_violation", detail: dependencyErrorMessage(error) } } };
        }
        const call = context ?? { requestId: "0" as Uint64, cancelled: false };
        try {
          const outcome = await invoke.openStream("complete", call, payload);
          if (outcome.kind === "domain") {
            return { ok: false, error: { kind: "domain", error: decodeCompleteError(JSON.stringify(outcome.value)) } };
          }
          if (outcome.kind === "runtime") {
            return { ok: false, error: { kind: "runtime", error: outcome.failure } };
          }
          const stream = outcome.stream;
          return { ok: true, value: {
            async send(message) {
              const encoded = JSON.parse(encodeCompleteResponse(message)) as unknown;
              const result = await stream.send(encoded);
              if (result.kind === "runtime") throw dependencyRuntimeError(result.failure);
            },
            async receive() {
              const result = await stream.receive();
              if (result.kind === "message") return { kind: "message", message: decodeCompleteResponse(JSON.stringify(result.value)) };
              if (result.kind === "peer_half_closed") return { kind: "peer_half_closed" };
              if (result.kind === "terminal_success") return { kind: "terminal", outcome: { ok: true } };
              if (result.kind === "terminal_domain") return { kind: "terminal", outcome: { ok: false, error: decodeCompleteError(JSON.stringify(result.value)) } };
              throw dependencyRuntimeError(result.failure);
            },
            async closeSend() {
              const result = await stream.closeSend();
              if (result.kind === "runtime") throw dependencyRuntimeError(result.failure);
            },
            cancel() { stream.cancel(); },
          } };
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: dependencyFailure(error) } };
        }
      },
      };
    },
  };
}

export const bindDependency = bindModelDependency;

export const portableValueProfile = lensoContractRuntime.portableValueProfile;
