/* @generated by lenso-contract-codegen; do not edit. */
import * as lensoContractRuntime from "@lenso/contract-runtime";

export const CAPABILITY_ID = "lenso.agent.tools@1";
export const DESCRIPTOR_VERSION = "1.0.0";
export const PORTABLE = true;
export const CROSS_LANE_TRANSFER = false;

export type Int64 = lensoContractRuntime.Int64;
export type Uint64 = lensoContractRuntime.Uint64;
export type Bytes = lensoContractRuntime.Bytes;
export type Timestamp = lensoContractRuntime.Timestamp;
export type Duration = lensoContractRuntime.Duration;
export type OptionalValue<T> = lensoContractRuntime.OptionalValue<T>;
export type InvocationContext = lensoContractRuntime.InvocationContext;
export type RuntimeFailure = lensoContractRuntime.RuntimeFailure;
export type UnknownDomainError = lensoContractRuntime.UnknownDomainError;
export type StreamEvent<Message, DomainError> = lensoContractRuntime.StreamEvent<Message, DomainError>;
export type StreamSession<Message, DomainError> = lensoContractRuntime.StreamSession<Message, DomainError>;

export interface CatalogRequest {

}

export interface CatalogResponse {
  tools: Array<CatalogResponseToolsItem>;
}

export interface CatalogResponseToolsItem {
  description: string;
  input_schema_json: string;
  name: string;
}

export interface ExecuteRequest {
  arguments_json: string;
  name: string;
}

export interface ExecuteResponse {
  content: string;
  content_type: "text";
  metadata_json: string;
}

export interface ExecuteErrorToolErrorPayload {
  details_json: string;
  message: string;
  provider_code: string;
}

export type CatalogError = "catalog_invalid" | UnknownDomainError;
export type CatalogInvocationError = { readonly kind: "domain"; readonly error: CatalogError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type CatalogResult = { readonly ok: true; readonly value: CatalogResponse } | { readonly ok: false; readonly error: CatalogInvocationError };
export type ExecuteError = "invalid_arguments" | { readonly code: "tool_error"; readonly payload: ExecuteErrorToolErrorPayload } | "unknown_tool" | UnknownDomainError;
export type ExecuteInvocationError = { readonly kind: "domain"; readonly error: ExecuteError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type ExecuteResult = { readonly ok: true; readonly value: ExecuteResponse } | { readonly ok: false; readonly error: ExecuteInvocationError };
export function encodeCatalogRequest(value: CatalogRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeCatalogRequest(wire: string): CatalogRequest { return lensoContractRuntime.decodePortableJson<CatalogRequest>(wire); }
export function encodeCatalogResponse(value: CatalogResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeCatalogResponse(wire: string): CatalogResponse { return lensoContractRuntime.decodePortableJson<CatalogResponse>(wire); }
export function encodeCatalogError(value: CatalogError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeCatalogError(wire: string): CatalogError { return lensoContractRuntime.decodeDomainError<CatalogError>(wire, ["catalog_invalid"]); }

export function encodeExecuteRequest(value: ExecuteRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeExecuteRequest(wire: string): ExecuteRequest { return lensoContractRuntime.decodePortableJson<ExecuteRequest>(wire); }
export function encodeExecuteResponse(value: ExecuteResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeExecuteResponse(wire: string): ExecuteResponse { return lensoContractRuntime.decodePortableJson<ExecuteResponse>(wire); }
export function encodeExecuteError(value: ExecuteError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeExecuteError(wire: string): ExecuteError { return lensoContractRuntime.decodeDomainError<ExecuteError>(wire, ["invalid_arguments", "unknown_tool"]); }


export interface ToolsClient {
  catalog(request: CatalogRequest, context?: InvocationContext): Promise<CatalogResult>;
  execute(request: ExecuteRequest, context?: InvocationContext): Promise<ExecuteResult>;
}

export interface ToolsProvider {
  catalog(context: InvocationContext, request: CatalogRequest): Promise<CatalogResult>;
  execute(context: InvocationContext, request: ExecuteRequest): Promise<ExecuteResult>;
}

export type ProviderDispatchOutcome =
  | { readonly kind: "success"; readonly value: unknown }
  | { readonly kind: "domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };

export interface CapabilityProviderDescriptor {
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly operations: ReadonlyArray<string>;
  readonly stream_operations: ReadonlyArray<string>;
  readonly event_operations: ReadonlyArray<string>;
}

export interface CapabilityProviderBinding {
  readonly descriptor: CapabilityProviderDescriptor;
  invokeRequest(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderDispatchOutcome>;
}

function providerErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export function bindToolsProvider(
  provider: ToolsProvider,
): CapabilityProviderBinding {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["catalog", "execute"],
      stream_operations: [],
      event_operations: [],
    },
    async invokeRequest(operation, context, payload) {
      switch (operation) {
      case "catalog": {
        let request: CatalogRequest;
        try {
          request = decodeCatalogRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.catalog(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeCatalogResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeCatalogError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "module_failure", detail: providerErrorMessage(error) } };
        }
      }
      case "execute": {
        let request: ExecuteRequest;
        try {
          request = decodeExecuteRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.execute(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeExecuteResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeExecuteError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "module_failure", detail: providerErrorMessage(error) } };
        }
      }
        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
  };
}

export type Provider = ToolsProvider;
export const bindProvider = bindToolsProvider;

export const portableValueProfile = lensoContractRuntime.portableValueProfile;
