/* @generated by lenso-contract-codegen; do not edit. */
import * as lensoContractRuntime from "@lenso/contract-runtime";

export const CAPABILITY_ID = "lenso.agent.tools@1";
export const DESCRIPTOR_VERSION = "1.0.0";
export const DESCRIPTOR_DIGEST = "sha256:cce8d9a6b3ba3fbe02e0fee42b86f40b43f0b821b9011e3101d6a6e6ed50d761";
export const PORTABLE = true;
export const CROSS_LANE_TRANSFER = false;

export type Int64 = lensoContractRuntime.Int64;
export type Uint64 = lensoContractRuntime.Uint64;
export type Bytes = lensoContractRuntime.Bytes;
export type Timestamp = lensoContractRuntime.Timestamp;
export type Duration = lensoContractRuntime.Duration;
export type OptionalValue<T> = lensoContractRuntime.OptionalValue<T>;
export type InvocationContext = lensoContractRuntime.InvocationContext;
export type RuntimeFailure = lensoContractRuntime.RuntimeFailure;
export type UnknownDomainError = lensoContractRuntime.UnknownDomainError;
export type StreamEvent<Message, DomainError> = lensoContractRuntime.StreamEvent<Message, DomainError>;
export type StreamSession<Message, DomainError> = lensoContractRuntime.StreamSession<Message, DomainError>;

export interface CapabilityContractReference<Client, Provider extends object> extends CapabilityDependencyBinding<Client> {
  readonly kind: "lenso.capability";
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly descriptor_digest: string;
  readonly generated_client: string;
  readonly descriptor: CapabilityProviderDescriptor;
  bindProvider(provider: Provider): CapabilityProviderBinding;
  required(id?: string): CapabilityDependencyDeclaration<Client, "one">;
  optional(id?: string): CapabilityDependencyDeclaration<Client, "optional">;
  many(id?: string): CapabilityDependencyDeclaration<Client, "many">;
  readonly __client?: Client;
  readonly __provider?: Provider;
}

export interface CatalogRequest {

}

export interface CatalogResponse {
  tools: Array<CatalogResponseToolsItem>;
}

export interface CatalogResponseToolsItem {
  description: string;
  input_schema_json: string;
  name: string;
}

export interface ExecuteRequest {
  arguments_json: string;
  name: string;
}

export interface ExecuteResponse {
  content: string;
  content_type: "text";
  metadata_json: string;
}

export interface ExecuteErrorToolErrorPayload {
  details_json: string;
  message: string;
  provider_code: string;
}

export type CatalogError = "catalog_invalid" | UnknownDomainError;
export type CatalogInvocationError = { readonly kind: "domain"; readonly error: CatalogError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type CatalogResult = { readonly ok: true; readonly value: CatalogResponse } | { readonly ok: false; readonly error: CatalogInvocationError };
export type ExecuteError = "invalid_arguments" | { readonly code: "tool_error"; readonly payload: ExecuteErrorToolErrorPayload } | "unknown_tool" | UnknownDomainError;
export type ExecuteInvocationError = { readonly kind: "domain"; readonly error: ExecuteError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type ExecuteResult = { readonly ok: true; readonly value: ExecuteResponse } | { readonly ok: false; readonly error: ExecuteInvocationError };
export function encodeCatalogRequest(value: CatalogRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeCatalogRequest(wire: string): CatalogRequest { return lensoContractRuntime.decodePortableJson<CatalogRequest>(wire); }
export function encodeCatalogResponse(value: CatalogResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeCatalogResponse(wire: string): CatalogResponse { return lensoContractRuntime.decodePortableJson<CatalogResponse>(wire); }
export function encodeCatalogError(value: CatalogError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeCatalogError(wire: string): CatalogError { return lensoContractRuntime.decodeDomainError<CatalogError>(wire, ["catalog_invalid"]); }

export function encodeExecuteRequest(value: ExecuteRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeExecuteRequest(wire: string): ExecuteRequest { return lensoContractRuntime.decodePortableJson<ExecuteRequest>(wire); }
export function encodeExecuteResponse(value: ExecuteResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeExecuteResponse(wire: string): ExecuteResponse { return lensoContractRuntime.decodePortableJson<ExecuteResponse>(wire); }
export function encodeExecuteError(value: ExecuteError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeExecuteError(wire: string): ExecuteError { return lensoContractRuntime.decodeDomainError<ExecuteError>(wire, ["invalid_arguments", "unknown_tool"]); }


export interface ToolsClient {
  catalog(request: CatalogRequest, context?: InvocationContext): Promise<CatalogResult>;
  execute(request: ExecuteRequest, context?: InvocationContext): Promise<ExecuteResult>;
}

export interface ToolsProvider {
  catalog(context: InvocationContext, request: CatalogRequest): Promise<CatalogResult>;
  execute(context: InvocationContext, request: ExecuteRequest): Promise<ExecuteResult>;
}

export const Tools: CapabilityContractReference<ToolsClient, ToolsProvider> = { kind: "lenso.capability", ...bindToolsDependency(), capability_id: CAPABILITY_ID, descriptor_version: DESCRIPTOR_VERSION, descriptor_digest: DESCRIPTOR_DIGEST, generated_client: "ToolsClient", descriptor: { capability_id: CAPABILITY_ID, descriptor_version: DESCRIPTOR_VERSION, operations: ["catalog", "execute"], stream_operations: [], event_operations: [] }, bindProvider: bindToolsProvider, required(id) { return { kind: "lenso.dependency", ...(id === undefined ? {} : { id }), contract: this, cardinality: "one" }; }, optional(id) { return { kind: "lenso.dependency", ...(id === undefined ? {} : { id }), contract: this, cardinality: "optional" }; }, many(id) { return { kind: "lenso.dependency", ...(id === undefined ? {} : { id }), contract: this, cardinality: "many" }; }, };
export const TOOLS_CONTRACT = Tools;

export type ProviderDispatchOutcome =
  | { readonly kind: "success"; readonly value: unknown }
  | { readonly kind: "domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
export type ProviderStreamActionOutcome =
  | { readonly kind: "accepted" }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
export type ProviderStreamReceiveOutcome =
  | { readonly kind: "message"; readonly value: unknown }
  | { readonly kind: "peer_half_closed" }
  | { readonly kind: "terminal_success" }
  | { readonly kind: "terminal_domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
/** @internal Runtime lowering seam. */
export interface ProviderStreamSessionBinding {
  send(message: unknown): Promise<ProviderStreamActionOutcome>;
  receive(): Promise<ProviderStreamReceiveOutcome>;
  closeSend(): Promise<ProviderStreamActionOutcome>;
  cancel(): void;
}
export type ProviderStreamOpenOutcome =
  | { readonly kind: "opened"; readonly stream: ProviderStreamSessionBinding }
  | { readonly kind: "domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
export type ProviderEventPublishOutcome =
  | { readonly kind: "accepted" }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };

export interface CapabilityProviderDescriptor {
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly operations: ReadonlyArray<string>;
  readonly stream_operations: ReadonlyArray<string>;
  readonly event_operations: ReadonlyArray<string>;
}

/** @internal Runtime lowering seam. */
export interface CapabilityProviderBinding {
  readonly descriptor: CapabilityProviderDescriptor;
  invokeRequest(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderDispatchOutcome>;
  openStream(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderStreamOpenOutcome>;
  publishEvent(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderEventPublishOutcome>;
}

function providerErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export function bindToolsProvider(
  provider: ToolsProvider,
): CapabilityProviderBinding {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["catalog", "execute"],
      stream_operations: [],
      event_operations: [],
    },
    async invokeRequest(operation, context, payload) {
      switch (operation) {
      case "catalog": {
        let request: CatalogRequest;
        try {
          request = decodeCatalogRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.catalog(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeCatalogResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeCatalogError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
        }
      }
      case "execute": {
        let request: ExecuteRequest;
        try {
          request = decodeExecuteRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.execute(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeExecuteResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeExecuteError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
        }
      }
        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
    async openStream(operation, context, payload) {
      switch (operation) {

        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
    async publishEvent(operation, context, payload) {
      switch (operation) {

        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
  };
}

export type Provider = ToolsProvider;
export const bindProvider = bindToolsProvider;

export type DependencyInvoker = (
  operation: string,
  context: InvocationContext,
  payload: unknown,
) => Promise<ProviderDispatchOutcome>;

export interface CapabilityDependencyBinding<Client> {
  readonly descriptor: CapabilityProviderDescriptor;
  createClient(invoke: DependencyInvoker): Client;
}

export interface CapabilityDependencyDeclaration<Client, Cardinality extends "one" | "optional" | "many"> {
  readonly kind: "lenso.dependency";
  readonly id?: string;
  readonly contract: CapabilityDependencyBinding<Client>;
  readonly cardinality: Cardinality;
}

function dependencyErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export function bindToolsDependency(): CapabilityDependencyBinding<ToolsClient> {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["catalog", "execute"],
      stream_operations: [],
      event_operations: [],
    },
    createClient(invoke) {
      return {
      async catalog(request, context) {
        let payload: unknown;
        try {
          payload = JSON.parse(encodeCatalogRequest(request)) as unknown;
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "protocol_violation", detail: dependencyErrorMessage(error) } } };
        }
        const call = context ?? { requestId: "0" as Uint64, cancelled: false };
        try {
          const outcome = await invoke("catalog", call, payload);
          if (outcome.kind === "success") {
            return { ok: true, value: decodeCatalogResponse(JSON.stringify(outcome.value)) };
          }
          if (outcome.kind === "domain") {
            return { ok: false, error: { kind: "domain", error: decodeCatalogError(JSON.stringify(outcome.value)) } };
          }
          return { ok: false, error: { kind: "runtime", error: outcome.failure } };
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "plugin_failure", detail: dependencyErrorMessage(error) } } };
        }
      },
      async execute(request, context) {
        let payload: unknown;
        try {
          payload = JSON.parse(encodeExecuteRequest(request)) as unknown;
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "protocol_violation", detail: dependencyErrorMessage(error) } } };
        }
        const call = context ?? { requestId: "0" as Uint64, cancelled: false };
        try {
          const outcome = await invoke("execute", call, payload);
          if (outcome.kind === "success") {
            return { ok: true, value: decodeExecuteResponse(JSON.stringify(outcome.value)) };
          }
          if (outcome.kind === "domain") {
            return { ok: false, error: { kind: "domain", error: decodeExecuteError(JSON.stringify(outcome.value)) } };
          }
          return { ok: false, error: { kind: "runtime", error: outcome.failure } };
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "plugin_failure", detail: dependencyErrorMessage(error) } } };
        }
      },
      };
    },
  };
}

export const bindDependency = bindToolsDependency;

export const portableValueProfile = lensoContractRuntime.portableValueProfile;
