/* @generated by lenso-contract-codegen; do not edit. */
import * as lensoContractRuntime from "@lenso/contract-runtime";

export const CAPABILITY_ID = "lenso.agent.auth.openai-codex@1";
export const DESCRIPTOR_VERSION = "1.0.0";
export const DESCRIPTOR_DIGEST = "sha256:22f178904ed4633ee41e505889e31d52a5d3b82bc98180cfd73b9ee97c151353";
export const PORTABLE = false;
export const CROSS_LANE_TRANSFER = false;

export type Int64 = lensoContractRuntime.Int64;
export type Uint64 = lensoContractRuntime.Uint64;
export type Bytes = lensoContractRuntime.Bytes;
export type Timestamp = lensoContractRuntime.Timestamp;
export type Duration = lensoContractRuntime.Duration;
export type OptionalValue<T> = lensoContractRuntime.OptionalValue<T>;
export type InvocationContext = lensoContractRuntime.InvocationContext;
export type RuntimeFailure = lensoContractRuntime.RuntimeFailure;
export type UnknownDomainError = lensoContractRuntime.UnknownDomainError;
export type StreamEvent<Message, DomainError> = lensoContractRuntime.StreamEvent<Message, DomainError>;
export type StreamSession<Message, DomainError> = lensoContractRuntime.StreamSession<Message, DomainError>;

export interface CapabilityContractReference<Client> extends CapabilityDependencyBinding<Client> {
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly descriptor_digest: string;
  readonly generated_client: string;
  readonly __client?: Client;
}

export interface AccessRequest {

}

export interface AccessResponse {
  access_token: string;
  account_id: string;
  expires_at: Uint64;
}

export type AccessError = "not_authenticated" | "refresh_rejected" | UnknownDomainError;
export type AccessInvocationError = { readonly kind: "domain"; readonly error: AccessError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type AccessResult = { readonly ok: true; readonly value: AccessResponse } | { readonly ok: false; readonly error: AccessInvocationError };
export function encodeAccessRequest(value: AccessRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeAccessRequest(wire: string): AccessRequest { return lensoContractRuntime.decodePortableJson<AccessRequest>(wire); }
export function encodeAccessResponse(value: AccessResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeAccessResponse(wire: string): AccessResponse { return lensoContractRuntime.decodePortableJson<AccessResponse>(wire); }
export function encodeAccessError(value: AccessError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeAccessError(wire: string): AccessError { return lensoContractRuntime.decodeDomainError<AccessError>(wire, ["not_authenticated", "refresh_rejected"]); }


export interface OpenaiCodexClient {
  access(request: AccessRequest, context?: InvocationContext): Promise<AccessResult>;
}

export interface OpenaiCodexProvider {
  access(context: InvocationContext, request: AccessRequest): Promise<AccessResult>;
}

export const OPENAI_CODEX_CONTRACT: CapabilityContractReference<OpenaiCodexClient> = { ...bindOpenaiCodexDependency(), capability_id: CAPABILITY_ID, descriptor_version: DESCRIPTOR_VERSION, descriptor_digest: DESCRIPTOR_DIGEST, generated_client: "OpenaiCodexClient" };

export type ProviderDispatchOutcome =
  | { readonly kind: "success"; readonly value: unknown }
  | { readonly kind: "domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };

export interface CapabilityProviderDescriptor {
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly operations: ReadonlyArray<string>;
  readonly stream_operations: ReadonlyArray<string>;
  readonly event_operations: ReadonlyArray<string>;
}

export interface CapabilityProviderBinding {
  readonly descriptor: CapabilityProviderDescriptor;
  invokeRequest(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderDispatchOutcome>;
}

function providerErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export function bindOpenaiCodexProvider(
  provider: OpenaiCodexProvider,
): CapabilityProviderBinding {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["access"],
      stream_operations: [],
      event_operations: [],
    },
    async invokeRequest(operation, context, payload) {
      switch (operation) {
      case "access": {
        let request: AccessRequest;
        try {
          request = decodeAccessRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.access(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeAccessResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeAccessError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
        }
      }
        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
  };
}

export type Provider = OpenaiCodexProvider;
export const bindProvider = bindOpenaiCodexProvider;

export type DependencyInvoker = (
  operation: string,
  context: InvocationContext,
  payload: unknown,
) => Promise<ProviderDispatchOutcome>;

export interface CapabilityDependencyBinding<Client> {
  readonly descriptor: CapabilityProviderDescriptor;
  createClient(invoke: DependencyInvoker): Client;
}

function dependencyErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export function bindOpenaiCodexDependency(): CapabilityDependencyBinding<OpenaiCodexClient> {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["access"],
      stream_operations: [],
      event_operations: [],
    },
    createClient(invoke) {
      return {
      async access(request, context) {
        let payload: unknown;
        try {
          payload = JSON.parse(encodeAccessRequest(request)) as unknown;
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "protocol_violation", detail: dependencyErrorMessage(error) } } };
        }
        const call = context ?? { requestId: "0" as Uint64, cancelled: false };
        try {
          const outcome = await invoke("access", call, payload);
          if (outcome.kind === "success") {
            return { ok: true, value: decodeAccessResponse(JSON.stringify(outcome.value)) };
          }
          if (outcome.kind === "domain") {
            return { ok: false, error: { kind: "domain", error: decodeAccessError(JSON.stringify(outcome.value)) } };
          }
          return { ok: false, error: { kind: "runtime", error: outcome.failure } };
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "plugin_failure", detail: dependencyErrorMessage(error) } } };
        }
      },
      };
    },
  };
}

export const bindDependency = bindOpenaiCodexDependency;

export const portableValueProfile = lensoContractRuntime.portableValueProfile;
