/* @generated by lenso-contract-codegen; do not edit. */
import * as lensoContractRuntime from "@lenso/contract-runtime";

export const CAPABILITY_ID = "lenso.agent.prompt-provider@1";
export const DESCRIPTOR_VERSION = "1.0.0";
export const PORTABLE = true;
export const CROSS_LANE_TRANSFER = false;

export type Int64 = lensoContractRuntime.Int64;
export type Uint64 = lensoContractRuntime.Uint64;
export type Bytes = lensoContractRuntime.Bytes;
export type Timestamp = lensoContractRuntime.Timestamp;
export type Duration = lensoContractRuntime.Duration;
export type OptionalValue<T> = lensoContractRuntime.OptionalValue<T>;
export type InvocationContext = lensoContractRuntime.InvocationContext;
export type RuntimeFailure = lensoContractRuntime.RuntimeFailure;
export type UnknownDomainError = lensoContractRuntime.UnknownDomainError;
export type StreamEvent<Message, DomainError> = lensoContractRuntime.StreamEvent<Message, DomainError>;
export type StreamSession<Message, DomainError> = lensoContractRuntime.StreamSession<Message, DomainError>;

export interface ContributeRequest {

}

export interface ContributeResponse {
  contributions: Array<ContributeResponseContributionsItem>;
}

export interface ContributeResponseContributionsItem {
  content: string;
  id: string;
  kind: "instruction" | "skill";
  version: string;
}

export type ContributeError = "contribution_invalid" | UnknownDomainError;
export type ContributeInvocationError = { readonly kind: "domain"; readonly error: ContributeError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type ContributeResult = { readonly ok: true; readonly value: ContributeResponse } | { readonly ok: false; readonly error: ContributeInvocationError };
export function encodeContributeRequest(value: ContributeRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeContributeRequest(wire: string): ContributeRequest { return lensoContractRuntime.decodePortableJson<ContributeRequest>(wire); }
export function encodeContributeResponse(value: ContributeResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeContributeResponse(wire: string): ContributeResponse { return lensoContractRuntime.decodePortableJson<ContributeResponse>(wire); }
export function encodeContributeError(value: ContributeError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeContributeError(wire: string): ContributeError { return lensoContractRuntime.decodeDomainError<ContributeError>(wire, ["contribution_invalid"]); }


export interface PromptProviderClient {
  contribute(request: ContributeRequest, context?: InvocationContext): Promise<ContributeResult>;
}

export interface PromptProviderProvider {
  contribute(context: InvocationContext, request: ContributeRequest): Promise<ContributeResult>;
}

export type ProviderDispatchOutcome =
  | { readonly kind: "success"; readonly value: unknown }
  | { readonly kind: "domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };

export interface CapabilityProviderDescriptor {
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly operations: ReadonlyArray<string>;
  readonly stream_operations: ReadonlyArray<string>;
  readonly event_operations: ReadonlyArray<string>;
}

export interface CapabilityProviderBinding {
  readonly descriptor: CapabilityProviderDescriptor;
  invokeRequest(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderDispatchOutcome>;
}

function providerErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export function bindPromptProviderProvider(
  provider: PromptProviderProvider,
): CapabilityProviderBinding {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["contribute"],
      stream_operations: [],
      event_operations: [],
    },
    async invokeRequest(operation, context, payload) {
      switch (operation) {
      case "contribute": {
        let request: ContributeRequest;
        try {
          request = decodeContributeRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.contribute(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeContributeResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeContributeError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
        }
      }
        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
  };
}

export type Provider = PromptProviderProvider;
export const bindProvider = bindPromptProviderProvider;

export const portableValueProfile = lensoContractRuntime.portableValueProfile;
