/* @generated by lenso-contract-codegen; do not edit. */
import * as lensoContractRuntime from "@lenso/contract-runtime";

export const CAPABILITY_ID = "lenso.agent.prompt@1";
export const DESCRIPTOR_VERSION = "1.0.0";
export const PORTABLE = true;
export const CROSS_LANE_TRANSFER = false;

export type Int64 = lensoContractRuntime.Int64;
export type Uint64 = lensoContractRuntime.Uint64;
export type Bytes = lensoContractRuntime.Bytes;
export type Timestamp = lensoContractRuntime.Timestamp;
export type Duration = lensoContractRuntime.Duration;
export type OptionalValue<T> = lensoContractRuntime.OptionalValue<T>;
export type InvocationContext = lensoContractRuntime.InvocationContext;
export type RuntimeFailure = lensoContractRuntime.RuntimeFailure;
export type UnknownDomainError = lensoContractRuntime.UnknownDomainError;
export type StreamEvent<Message, DomainError> = lensoContractRuntime.StreamEvent<Message, DomainError>;
export type StreamSession<Message, DomainError> = lensoContractRuntime.StreamSession<Message, DomainError>;

export interface AssembleRequest {

}

export interface AssembleResponse {
  content: string;
  contributions: Array<AssembleResponseContributionsItem>;
}

export interface AssembleResponseContributionsItem {
  digest: string;
  id: string;
  kind: "instruction" | "skill";
  version: string;
}

export type AssembleError = "prompt_invalid" | UnknownDomainError;
export type AssembleInvocationError = { readonly kind: "domain"; readonly error: AssembleError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type AssembleResult = { readonly ok: true; readonly value: AssembleResponse } | { readonly ok: false; readonly error: AssembleInvocationError };
export function encodeAssembleRequest(value: AssembleRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeAssembleRequest(wire: string): AssembleRequest { return lensoContractRuntime.decodePortableJson<AssembleRequest>(wire); }
export function encodeAssembleResponse(value: AssembleResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeAssembleResponse(wire: string): AssembleResponse { return lensoContractRuntime.decodePortableJson<AssembleResponse>(wire); }
export function encodeAssembleError(value: AssembleError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeAssembleError(wire: string): AssembleError { return lensoContractRuntime.decodeDomainError<AssembleError>(wire, ["prompt_invalid"]); }


export interface PromptClient {
  assemble(request: AssembleRequest, context?: InvocationContext): Promise<AssembleResult>;
}

export interface PromptProvider {
  assemble(context: InvocationContext, request: AssembleRequest): Promise<AssembleResult>;
}

export type ProviderDispatchOutcome =
  | { readonly kind: "success"; readonly value: unknown }
  | { readonly kind: "domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };

export interface CapabilityProviderDescriptor {
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly operations: ReadonlyArray<string>;
  readonly stream_operations: ReadonlyArray<string>;
  readonly event_operations: ReadonlyArray<string>;
}

export interface CapabilityProviderBinding {
  readonly descriptor: CapabilityProviderDescriptor;
  invokeRequest(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderDispatchOutcome>;
}

function providerErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export function bindPromptProvider(
  provider: PromptProvider,
): CapabilityProviderBinding {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["assemble"],
      stream_operations: [],
      event_operations: [],
    },
    async invokeRequest(operation, context, payload) {
      switch (operation) {
      case "assemble": {
        let request: AssembleRequest;
        try {
          request = decodeAssembleRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.assemble(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeAssembleResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeAssembleError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "module_failure", detail: providerErrorMessage(error) } };
        }
      }
        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
  };
}

export type Provider = PromptProvider;
export const bindProvider = bindPromptProvider;

export const portableValueProfile = lensoContractRuntime.portableValueProfile;
