/* @generated by lenso-contract-codegen; do not edit. */
import * as lensoContractRuntime from "@lenso/contract-runtime";

export const CAPABILITY_ID = "lenso.auth.anonymous@1";
export const DESCRIPTOR_VERSION = "1.0.0";
export const PORTABLE = true;
export const CROSS_LANE_TRANSFER = true;

export type Int64 = lensoContractRuntime.Int64;
export type Uint64 = lensoContractRuntime.Uint64;
export type Bytes = lensoContractRuntime.Bytes;
export type Timestamp = lensoContractRuntime.Timestamp;
export type Duration = lensoContractRuntime.Duration;
export type OptionalValue<T> = lensoContractRuntime.OptionalValue<T>;
export type InvocationContext = lensoContractRuntime.InvocationContext;
export type RuntimeFailure = lensoContractRuntime.RuntimeFailure;
export type UnknownDomainError = lensoContractRuntime.UnknownDomainError;
export type StreamEvent<Message, DomainError> = lensoContractRuntime.StreamEvent<Message, DomainError>;
export type StreamSession<Message, DomainError> = lensoContractRuntime.StreamSession<Message, DomainError>;

export interface SignInRequest {
  device_id: string | null;
}

export interface SignInResponse {
  created: boolean;
  credential: string;
  expires_at: Timestamp;
  session_id: string;
  subject: string;
}

export type SignInError = "disabled" | "invalid_device" | UnknownDomainError;
export type SignInInvocationError = { readonly kind: "domain"; readonly error: SignInError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type SignInResult = { readonly ok: true; readonly value: SignInResponse } | { readonly ok: false; readonly error: SignInInvocationError };
export function encodeSignInRequest(value: SignInRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeSignInRequest(wire: string): SignInRequest { return lensoContractRuntime.decodePortableJson<SignInRequest>(wire); }
export function encodeSignInResponse(value: SignInResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeSignInResponse(wire: string): SignInResponse { return lensoContractRuntime.decodePortableJson<SignInResponse>(wire); }
export function encodeSignInError(value: SignInError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeSignInError(wire: string): SignInError { return lensoContractRuntime.decodeDomainError<SignInError>(wire, ["disabled", "invalid_device"]); }


export interface AnonymousClient {
  sign_in(request: SignInRequest, context?: InvocationContext): Promise<SignInResult>;
}

export interface AnonymousProvider {
  sign_in(context: InvocationContext, request: SignInRequest): Promise<SignInResult>;
}

export type ProviderDispatchOutcome =
  | { readonly kind: "success"; readonly value: unknown }
  | { readonly kind: "domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };

export interface CapabilityProviderDescriptor {
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly operations: ReadonlyArray<string>;
  readonly stream_operations: ReadonlyArray<string>;
  readonly event_operations: ReadonlyArray<string>;
}

export interface CapabilityProviderBinding {
  readonly descriptor: CapabilityProviderDescriptor;
  invokeRequest(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderDispatchOutcome>;
}

function providerErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export function bindAnonymousProvider(
  provider: AnonymousProvider,
): CapabilityProviderBinding {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["sign_in"],
      stream_operations: [],
      event_operations: [],
    },
    async invokeRequest(operation, context, payload) {
      switch (operation) {
      case "sign_in": {
        let request: SignInRequest;
        try {
          request = decodeSignInRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.sign_in(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeSignInResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeSignInError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "module_failure", detail: providerErrorMessage(error) } };
        }
      }
        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
  };
}

export type Provider = AnonymousProvider;
export const bindProvider = bindAnonymousProvider;

export const portableValueProfile = lensoContractRuntime.portableValueProfile;
