/* @generated by lenso-contract-codegen; do not edit. */
import * as lensoContractRuntime from "@lenso/contract-runtime";

export const CAPABILITY_ID = "lenso.auth@1";
export const DESCRIPTOR_VERSION = "1.0.0";
export const DESCRIPTOR_DIGEST = "sha256:b14b8ad9c35dee119ff4fb61635853a28c11bb096d47a8dd5b6d7455de77321a";
export const PORTABLE = true;
export const CROSS_LANE_TRANSFER = false;

export type Int64 = lensoContractRuntime.Int64;
export type Uint64 = lensoContractRuntime.Uint64;
export type Bytes = lensoContractRuntime.Bytes;
export type Timestamp = lensoContractRuntime.Timestamp;
export type Duration = lensoContractRuntime.Duration;
export type OptionalValue<T> = lensoContractRuntime.OptionalValue<T>;
export type InvocationContext = lensoContractRuntime.InvocationContext;
export type RuntimeFailure = lensoContractRuntime.RuntimeFailure;
export type UnknownDomainError = lensoContractRuntime.UnknownDomainError;
export type StreamEvent<Message, DomainError> = lensoContractRuntime.StreamEvent<Message, DomainError>;
export type StreamSession<Message, DomainError> = lensoContractRuntime.StreamSession<Message, DomainError>;

export interface CapabilityContractReference<Client> extends CapabilityDependencyBinding<Client> {
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly descriptor_digest: string;
  readonly generated_client: string;
  readonly __client?: Client;
}

export interface AuthenticateRequest {
  credential: AuthenticateRequestCredential | null;
}

export interface AuthenticateRequestCredential {
  scheme: string;
  value: string;
}

export interface AuthenticateResponse {
  assertion: AuthenticateResponseAssertion | null;
  kind: "absent" | "authenticated";
}

export interface AuthenticateResponseAssertion {
  actor_kind: string;
  assurance: string;
  audience: Array<string>;
  claims?: Record<string, unknown>;
  expires_at: Timestamp;
  issued_at: Timestamp;
  issuer: string;
  parent_provenance?: string;
  proof: string;
  subject: string;
}

export type AuthenticateError = "expired" | "invalid" | "revoked" | "unsupported" | UnknownDomainError;
export type AuthenticateInvocationError = { readonly kind: "domain"; readonly error: AuthenticateError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type AuthenticateResult = { readonly ok: true; readonly value: AuthenticateResponse } | { readonly ok: false; readonly error: AuthenticateInvocationError };
export function encodeAuthenticateRequest(value: AuthenticateRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeAuthenticateRequest(wire: string): AuthenticateRequest { return lensoContractRuntime.decodePortableJson<AuthenticateRequest>(wire); }
export function encodeAuthenticateResponse(value: AuthenticateResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeAuthenticateResponse(wire: string): AuthenticateResponse { return lensoContractRuntime.decodePortableJson<AuthenticateResponse>(wire); }
export function encodeAuthenticateError(value: AuthenticateError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeAuthenticateError(wire: string): AuthenticateError { return lensoContractRuntime.decodeDomainError<AuthenticateError>(wire, ["expired", "invalid", "revoked", "unsupported"]); }


export interface AuthClient {
  authenticate(request: AuthenticateRequest, context?: InvocationContext): Promise<AuthenticateResult>;
}

export interface AuthProvider {
  authenticate(context: InvocationContext, request: AuthenticateRequest): Promise<AuthenticateResult>;
}

export const AUTH_CONTRACT: CapabilityContractReference<AuthClient> = { ...bindAuthDependency(), capability_id: CAPABILITY_ID, descriptor_version: DESCRIPTOR_VERSION, descriptor_digest: DESCRIPTOR_DIGEST, generated_client: "AuthClient" };

export type ProviderDispatchOutcome =
  | { readonly kind: "success"; readonly value: unknown }
  | { readonly kind: "domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };

export interface CapabilityProviderDescriptor {
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly operations: ReadonlyArray<string>;
  readonly stream_operations: ReadonlyArray<string>;
  readonly event_operations: ReadonlyArray<string>;
}

export interface CapabilityProviderBinding {
  readonly descriptor: CapabilityProviderDescriptor;
  invokeRequest(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderDispatchOutcome>;
}

function providerErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export function bindAuthProvider(
  provider: AuthProvider,
): CapabilityProviderBinding {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["authenticate"],
      stream_operations: [],
      event_operations: [],
    },
    async invokeRequest(operation, context, payload) {
      switch (operation) {
      case "authenticate": {
        let request: AuthenticateRequest;
        try {
          request = decodeAuthenticateRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.authenticate(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeAuthenticateResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeAuthenticateError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
        }
      }
        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
  };
}

export type Provider = AuthProvider;
export const bindProvider = bindAuthProvider;

export type DependencyInvoker = (
  operation: string,
  context: InvocationContext,
  payload: unknown,
) => Promise<ProviderDispatchOutcome>;

export interface CapabilityDependencyBinding<Client> {
  readonly descriptor: CapabilityProviderDescriptor;
  createClient(invoke: DependencyInvoker): Client;
}

function dependencyErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export function bindAuthDependency(): CapabilityDependencyBinding<AuthClient> {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["authenticate"],
      stream_operations: [],
      event_operations: [],
    },
    createClient(invoke) {
      return {
      async authenticate(request, context) {
        let payload: unknown;
        try {
          payload = JSON.parse(encodeAuthenticateRequest(request)) as unknown;
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "protocol_violation", detail: dependencyErrorMessage(error) } } };
        }
        const call = context ?? { requestId: "0" as Uint64, cancelled: false };
        try {
          const outcome = await invoke("authenticate", call, payload);
          if (outcome.kind === "success") {
            return { ok: true, value: decodeAuthenticateResponse(JSON.stringify(outcome.value)) };
          }
          if (outcome.kind === "domain") {
            return { ok: false, error: { kind: "domain", error: decodeAuthenticateError(JSON.stringify(outcome.value)) } };
          }
          return { ok: false, error: { kind: "runtime", error: outcome.failure } };
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "plugin_failure", detail: dependencyErrorMessage(error) } } };
        }
      },
      };
    },
  };
}

export const bindDependency = bindAuthDependency;

export const portableValueProfile = lensoContractRuntime.portableValueProfile;
