/* @generated by lenso-contract-codegen; do not edit. */
import * as lensoContractRuntime from "@lenso/contract-runtime";

export const CAPABILITY_ID = "lenso.auth.credential-issuer@1";
export const DESCRIPTOR_VERSION = "1.0.0";
export const DESCRIPTOR_DIGEST = "sha256:c7dfd679a0a3a534b9b1206ea4639163a0a8eae6eb5c9bc6e944efeee0560ac3";
export const PORTABLE = true;
export const CROSS_LANE_TRANSFER = true;

export type Int64 = lensoContractRuntime.Int64;
export type Uint64 = lensoContractRuntime.Uint64;
export type Bytes = lensoContractRuntime.Bytes;
export type Timestamp = lensoContractRuntime.Timestamp;
export type Duration = lensoContractRuntime.Duration;
export type OptionalValue<T> = lensoContractRuntime.OptionalValue<T>;
export type InvocationContext = lensoContractRuntime.InvocationContext;
export type RuntimeFailure = lensoContractRuntime.RuntimeFailure;
export type UnknownDomainError = lensoContractRuntime.UnknownDomainError;
export type StreamEvent<Message, DomainError> = lensoContractRuntime.StreamEvent<Message, DomainError>;
export type StreamSession<Message, DomainError> = lensoContractRuntime.StreamSession<Message, DomainError>;

export interface CapabilityContractReference<Client, Provider extends object, Runtime extends DependencyInvoker = DependencyInvoker> extends CapabilityDependencyBinding<Client, Runtime> {
  readonly kind: "lenso.capability";
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly descriptor_digest: string;
  readonly generated_client: string;
  readonly descriptor: CapabilityProviderDescriptor;
  bindProvider(provider: Provider): CapabilityProviderBinding;
  required(id?: string): CapabilityDependencyDeclaration<Client, "one", Runtime>;
  optional(id?: string): CapabilityDependencyDeclaration<Client, "optional", Runtime>;
  many(id?: string): CapabilityDependencyDeclaration<Client, "many", Runtime>;
  readonly __client?: Client;
  readonly __provider?: Provider;
}

export interface IssueRequest {
  actor_kind: string;
  assurance: string;
  audience: Array<string>;
  claims: Record<string, unknown>;
  expires_at: Timestamp;
  subject: string;
}

export interface IssueResponse {
  credential: string;
  expires_at: Timestamp;
  session_id: string;
}

export interface RevokeRequest {
  session_id: string;
}

export interface RevokeResponse {
  changed: boolean;
}

export type IssueError = "disabled" | "expired" | "invalid_authority" | "invalid_subject" | UnknownDomainError;
export type IssueInvocationError = { readonly kind: "domain"; readonly error: IssueError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type IssueResult = { readonly ok: true; readonly value: IssueResponse } | { readonly ok: false; readonly error: IssueInvocationError };
export type RevokeError = "invalid_session" | "not_found" | UnknownDomainError;
export type RevokeInvocationError = { readonly kind: "domain"; readonly error: RevokeError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type RevokeResult = { readonly ok: true; readonly value: RevokeResponse } | { readonly ok: false; readonly error: RevokeInvocationError };
export function encodeIssueRequest(value: IssueRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeIssueRequest(wire: string): IssueRequest { return lensoContractRuntime.decodePortableJson<IssueRequest>(wire); }
export function encodeIssueResponse(value: IssueResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeIssueResponse(wire: string): IssueResponse { return lensoContractRuntime.decodePortableJson<IssueResponse>(wire); }
export function encodeIssueError(value: IssueError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeIssueError(wire: string): IssueError { return lensoContractRuntime.decodeDomainError<IssueError>(wire, ["disabled", "expired", "invalid_authority", "invalid_subject"]); }

export function encodeRevokeRequest(value: RevokeRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeRevokeRequest(wire: string): RevokeRequest { return lensoContractRuntime.decodePortableJson<RevokeRequest>(wire); }
export function encodeRevokeResponse(value: RevokeResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeRevokeResponse(wire: string): RevokeResponse { return lensoContractRuntime.decodePortableJson<RevokeResponse>(wire); }
export function encodeRevokeError(value: RevokeError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeRevokeError(wire: string): RevokeError { return lensoContractRuntime.decodeDomainError<RevokeError>(wire, ["invalid_session", "not_found"]); }


export interface CredentialIssuerClient {
  issue(request: IssueRequest, context?: InvocationContext): Promise<IssueResult>;
  revoke(request: RevokeRequest, context?: InvocationContext): Promise<RevokeResult>;
}

export interface CredentialIssuerProvider {
  issue(context: InvocationContext, request: IssueRequest): Promise<IssueResult>;
  revoke(context: InvocationContext, request: RevokeRequest): Promise<RevokeResult>;
}

export const CredentialIssuer: CapabilityContractReference<CredentialIssuerClient, CredentialIssuerProvider, DependencyInvoker> = { kind: "lenso.capability", ...bindCredentialIssuerDependency(), capability_id: CAPABILITY_ID, descriptor_version: DESCRIPTOR_VERSION, descriptor_digest: DESCRIPTOR_DIGEST, generated_client: "CredentialIssuerClient", descriptor: { capability_id: CAPABILITY_ID, descriptor_version: DESCRIPTOR_VERSION, operations: ["issue", "revoke"], stream_operations: [], event_operations: [] }, bindProvider: bindCredentialIssuerProvider, required(id) { return { kind: "lenso.dependency", ...(id === undefined ? {} : { id }), contract: this, cardinality: "one" }; }, optional(id) { return { kind: "lenso.dependency", ...(id === undefined ? {} : { id }), contract: this, cardinality: "optional" }; }, many(id) { return { kind: "lenso.dependency", ...(id === undefined ? {} : { id }), contract: this, cardinality: "many" }; }, };
export const CREDENTIAL_ISSUER_CONTRACT = CredentialIssuer;

export type ProviderDispatchOutcome =
  | { readonly kind: "success"; readonly value: unknown }
  | { readonly kind: "domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
export type ProviderStreamActionOutcome =
  | { readonly kind: "accepted" }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
export type ProviderStreamReceiveOutcome =
  | { readonly kind: "message"; readonly value: unknown }
  | { readonly kind: "peer_half_closed" }
  | { readonly kind: "terminal_success" }
  | { readonly kind: "terminal_domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
/** @internal Runtime lowering seam. */
export interface ProviderStreamSessionBinding {
  send(message: unknown): Promise<ProviderStreamActionOutcome>;
  receive(): Promise<ProviderStreamReceiveOutcome>;
  closeSend(): Promise<ProviderStreamActionOutcome>;
  cancel(): void;
}
export type ProviderStreamOpenOutcome =
  | { readonly kind: "opened"; readonly stream: ProviderStreamSessionBinding }
  | { readonly kind: "domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
export type ProviderEventPublishOutcome =
  | { readonly kind: "accepted" }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };

export interface CapabilityProviderDescriptor {
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly operations: ReadonlyArray<string>;
  readonly stream_operations: ReadonlyArray<string>;
  readonly event_operations: ReadonlyArray<string>;
}

/** @internal Runtime lowering seam. */
export interface CapabilityProviderBinding {
  readonly descriptor: CapabilityProviderDescriptor;
  invokeRequest(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderDispatchOutcome>;
  openStream(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderStreamOpenOutcome>;
  publishEvent(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderEventPublishOutcome>;
}

function providerErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export function bindCredentialIssuerProvider(
  provider: CredentialIssuerProvider,
): CapabilityProviderBinding {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["issue", "revoke"],
      stream_operations: [],
      event_operations: [],
    },
    async invokeRequest(operation, context, payload) {
      switch (operation) {
      case "issue": {
        let request: IssueRequest;
        try {
          request = decodeIssueRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.issue(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeIssueResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeIssueError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
        }
      }
      case "revoke": {
        let request: RevokeRequest;
        try {
          request = decodeRevokeRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.revoke(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeRevokeResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeRevokeError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
        }
      }
        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
    async openStream(operation, context, payload) {
      switch (operation) {

        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
    async publishEvent(operation, context, payload) {
      switch (operation) {

        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
  };
}

export type Provider = CredentialIssuerProvider;
export const bindProvider = bindCredentialIssuerProvider;

export type DependencyInvoker = (
  operation: string,
  context: InvocationContext,
  payload: unknown,
) => Promise<ProviderDispatchOutcome>;

export type InteractionDependencyInvoker = DependencyInvoker & {
  readonly providerInstance: string;
  openStream(operation: string, context: InvocationContext, payload: unknown): Promise<ProviderStreamOpenOutcome>;
  publishEvent(operation: string, context: InvocationContext, payload: unknown): Promise<ProviderEventPublishOutcome>;
};

export interface CapabilityDependencyBinding<Client, Runtime extends DependencyInvoker = DependencyInvoker> {
  readonly descriptor: CapabilityProviderDescriptor;
  createClient(invoke: Runtime): Client;
}

export interface CapabilityDependencyDeclaration<Client, Cardinality extends "one" | "optional" | "many", Runtime extends DependencyInvoker = DependencyInvoker> {
  readonly kind: "lenso.dependency";
  readonly id?: string;
  readonly contract: CapabilityDependencyBinding<Client, Runtime>;
  readonly cardinality: Cardinality;
}

function dependencyErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function dependencyRuntimeError(failure: RuntimeFailure): Error {
  return Object.assign(new Error(`Capability dependency failed: ${failure.kind}`), { failure });
}

function dependencyFailure(error: unknown): RuntimeFailure {
  if (typeof error === "object" && error !== null && "failure" in error) return (error as { failure: RuntimeFailure }).failure;
  return { kind: "plugin_failure", detail: dependencyErrorMessage(error) };
}

export function bindCredentialIssuerDependency(): CapabilityDependencyBinding<CredentialIssuerClient, DependencyInvoker> {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["issue", "revoke"],
      stream_operations: [],
      event_operations: [],
    },
    createClient(invoke) {
      return {
      async issue(request, context) {
        let payload: unknown;
        try {
          payload = JSON.parse(encodeIssueRequest(request)) as unknown;
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "protocol_violation", detail: dependencyErrorMessage(error) } } };
        }
        const call = context ?? { requestId: "0" as Uint64, cancelled: false };
        try {
          const outcome = await invoke("issue", call, payload);
          if (outcome.kind === "success") {
            return { ok: true, value: decodeIssueResponse(JSON.stringify(outcome.value)) };
          }
          if (outcome.kind === "domain") {
            return { ok: false, error: { kind: "domain", error: decodeIssueError(JSON.stringify(outcome.value)) } };
          }
          return { ok: false, error: { kind: "runtime", error: outcome.failure } };
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "plugin_failure", detail: dependencyErrorMessage(error) } } };
        }
      },
      async revoke(request, context) {
        let payload: unknown;
        try {
          payload = JSON.parse(encodeRevokeRequest(request)) as unknown;
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "protocol_violation", detail: dependencyErrorMessage(error) } } };
        }
        const call = context ?? { requestId: "0" as Uint64, cancelled: false };
        try {
          const outcome = await invoke("revoke", call, payload);
          if (outcome.kind === "success") {
            return { ok: true, value: decodeRevokeResponse(JSON.stringify(outcome.value)) };
          }
          if (outcome.kind === "domain") {
            return { ok: false, error: { kind: "domain", error: decodeRevokeError(JSON.stringify(outcome.value)) } };
          }
          return { ok: false, error: { kind: "runtime", error: outcome.failure } };
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "plugin_failure", detail: dependencyErrorMessage(error) } } };
        }
      },
      };
    },
  };
}

export const bindDependency = bindCredentialIssuerDependency;

export const portableValueProfile = lensoContractRuntime.portableValueProfile;
