/* @generated by lenso-contract-codegen; do not edit. */
import * as lensoContractRuntime from "@lenso/contract-runtime";

export const CAPABILITY_ID = "lenso.auth.federated@1";
export const DESCRIPTOR_VERSION = "1.0.0";
export const DESCRIPTOR_DIGEST = "sha256:298d90953f0dc7de9506bbe0a9bcd38a1789ba6ab4a922a4e8fe0f325dcd0557";
export const PORTABLE = true;
export const CROSS_LANE_TRANSFER = true;

export type Int64 = lensoContractRuntime.Int64;
export type Uint64 = lensoContractRuntime.Uint64;
export type Bytes = lensoContractRuntime.Bytes;
export type Timestamp = lensoContractRuntime.Timestamp;
export type Duration = lensoContractRuntime.Duration;
export type OptionalValue<T> = lensoContractRuntime.OptionalValue<T>;
export type InvocationContext = lensoContractRuntime.InvocationContext;
export type RuntimeFailure = lensoContractRuntime.RuntimeFailure;
export type UnknownDomainError = lensoContractRuntime.UnknownDomainError;
export type StreamEvent<Message, DomainError> = lensoContractRuntime.StreamEvent<Message, DomainError>;
export type StreamSession<Message, DomainError> = lensoContractRuntime.StreamSession<Message, DomainError>;

export interface CapabilityContractReference<Client> extends CapabilityDependencyBinding<Client> {
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly descriptor_digest: string;
  readonly generated_client: string;
  readonly __client?: Client;
}

export interface CompleteRequest {
  code: string;
  state: string;
}

export interface CompleteResponse {
  credential: string;
  expires_at: Timestamp;
  provider: string;
  return_to: string;
  session_id: string;
  subject: string;
}

export interface StartRequest {
  return_to: string;
}

export interface StartResponse {
  authorization_url: string;
  expires_at: Timestamp;
  provider: string;
}

export type CompleteError = "disabled" | "invalid_callback" | "invalid_state" | "provider_rejected" | "unverified_identity" | UnknownDomainError;
export type CompleteInvocationError = { readonly kind: "domain"; readonly error: CompleteError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type CompleteResult = { readonly ok: true; readonly value: CompleteResponse } | { readonly ok: false; readonly error: CompleteInvocationError };
export type StartError = "invalid_return_to" | "provider_unavailable" | UnknownDomainError;
export type StartInvocationError = { readonly kind: "domain"; readonly error: StartError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type StartResult = { readonly ok: true; readonly value: StartResponse } | { readonly ok: false; readonly error: StartInvocationError };
export function encodeCompleteRequest(value: CompleteRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeCompleteRequest(wire: string): CompleteRequest { return lensoContractRuntime.decodePortableJson<CompleteRequest>(wire); }
export function encodeCompleteResponse(value: CompleteResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeCompleteResponse(wire: string): CompleteResponse { return lensoContractRuntime.decodePortableJson<CompleteResponse>(wire); }
export function encodeCompleteError(value: CompleteError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeCompleteError(wire: string): CompleteError { return lensoContractRuntime.decodeDomainError<CompleteError>(wire, ["disabled", "invalid_callback", "invalid_state", "provider_rejected", "unverified_identity"]); }

export function encodeStartRequest(value: StartRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeStartRequest(wire: string): StartRequest { return lensoContractRuntime.decodePortableJson<StartRequest>(wire); }
export function encodeStartResponse(value: StartResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeStartResponse(wire: string): StartResponse { return lensoContractRuntime.decodePortableJson<StartResponse>(wire); }
export function encodeStartError(value: StartError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeStartError(wire: string): StartError { return lensoContractRuntime.decodeDomainError<StartError>(wire, ["invalid_return_to", "provider_unavailable"]); }


export interface FederatedClient {
  complete(request: CompleteRequest, context?: InvocationContext): Promise<CompleteResult>;
  start(request: StartRequest, context?: InvocationContext): Promise<StartResult>;
}

export interface FederatedProvider {
  complete(context: InvocationContext, request: CompleteRequest): Promise<CompleteResult>;
  start(context: InvocationContext, request: StartRequest): Promise<StartResult>;
}

export const FEDERATED_CONTRACT: CapabilityContractReference<FederatedClient> = { ...bindFederatedDependency(), capability_id: CAPABILITY_ID, descriptor_version: DESCRIPTOR_VERSION, descriptor_digest: DESCRIPTOR_DIGEST, generated_client: "FederatedClient" };

export type ProviderDispatchOutcome =
  | { readonly kind: "success"; readonly value: unknown }
  | { readonly kind: "domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };

export interface CapabilityProviderDescriptor {
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly operations: ReadonlyArray<string>;
  readonly stream_operations: ReadonlyArray<string>;
  readonly event_operations: ReadonlyArray<string>;
}

export interface CapabilityProviderBinding {
  readonly descriptor: CapabilityProviderDescriptor;
  invokeRequest(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderDispatchOutcome>;
}

function providerErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export function bindFederatedProvider(
  provider: FederatedProvider,
): CapabilityProviderBinding {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["complete", "start"],
      stream_operations: [],
      event_operations: [],
    },
    async invokeRequest(operation, context, payload) {
      switch (operation) {
      case "complete": {
        let request: CompleteRequest;
        try {
          request = decodeCompleteRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.complete(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeCompleteResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeCompleteError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
        }
      }
      case "start": {
        let request: StartRequest;
        try {
          request = decodeStartRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.start(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeStartResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeStartError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
        }
      }
        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
  };
}

export type Provider = FederatedProvider;
export const bindProvider = bindFederatedProvider;

export type DependencyInvoker = (
  operation: string,
  context: InvocationContext,
  payload: unknown,
) => Promise<ProviderDispatchOutcome>;

export interface CapabilityDependencyBinding<Client> {
  readonly descriptor: CapabilityProviderDescriptor;
  createClient(invoke: DependencyInvoker): Client;
}

function dependencyErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export function bindFederatedDependency(): CapabilityDependencyBinding<FederatedClient> {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["complete", "start"],
      stream_operations: [],
      event_operations: [],
    },
    createClient(invoke) {
      return {
      async complete(request, context) {
        let payload: unknown;
        try {
          payload = JSON.parse(encodeCompleteRequest(request)) as unknown;
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "protocol_violation", detail: dependencyErrorMessage(error) } } };
        }
        const call = context ?? { requestId: "0" as Uint64, cancelled: false };
        try {
          const outcome = await invoke("complete", call, payload);
          if (outcome.kind === "success") {
            return { ok: true, value: decodeCompleteResponse(JSON.stringify(outcome.value)) };
          }
          if (outcome.kind === "domain") {
            return { ok: false, error: { kind: "domain", error: decodeCompleteError(JSON.stringify(outcome.value)) } };
          }
          return { ok: false, error: { kind: "runtime", error: outcome.failure } };
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "plugin_failure", detail: dependencyErrorMessage(error) } } };
        }
      },
      async start(request, context) {
        let payload: unknown;
        try {
          payload = JSON.parse(encodeStartRequest(request)) as unknown;
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "protocol_violation", detail: dependencyErrorMessage(error) } } };
        }
        const call = context ?? { requestId: "0" as Uint64, cancelled: false };
        try {
          const outcome = await invoke("start", call, payload);
          if (outcome.kind === "success") {
            return { ok: true, value: decodeStartResponse(JSON.stringify(outcome.value)) };
          }
          if (outcome.kind === "domain") {
            return { ok: false, error: { kind: "domain", error: decodeStartError(JSON.stringify(outcome.value)) } };
          }
          return { ok: false, error: { kind: "runtime", error: outcome.failure } };
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "plugin_failure", detail: dependencyErrorMessage(error) } } };
        }
      },
      };
    },
  };
}

export const bindDependency = bindFederatedDependency;

export const portableValueProfile = lensoContractRuntime.portableValueProfile;
