/* @generated by lenso-contract-codegen; do not edit. */
import * as lensoContractRuntime from "@lenso/contract-runtime";

export const CAPABILITY_ID = "lenso.http.endpoint@1";
export const DESCRIPTOR_VERSION = "1.1.0";
export const DESCRIPTOR_DIGEST = "sha256:701deedf705cb1a3b2f35fcae72f20ae85d46c6da6a008405a519018bbcdd3fe";
export const PORTABLE = true;
export const CROSS_LANE_TRANSFER = true;

export type Int64 = lensoContractRuntime.Int64;
export type Uint64 = lensoContractRuntime.Uint64;
export type Bytes = lensoContractRuntime.Bytes;
export type Timestamp = lensoContractRuntime.Timestamp;
export type Duration = lensoContractRuntime.Duration;
export type OptionalValue<T> = lensoContractRuntime.OptionalValue<T>;
export type InvocationContext = lensoContractRuntime.InvocationContext;
export type RuntimeFailure = lensoContractRuntime.RuntimeFailure;
export type UnknownDomainError = lensoContractRuntime.UnknownDomainError;
export type StreamEvent<Message, DomainError> = lensoContractRuntime.StreamEvent<Message, DomainError>;
export type StreamSession<Message, DomainError> = lensoContractRuntime.StreamSession<Message, DomainError>;

export interface CapabilityContractReference<Client, Provider extends object> extends CapabilityDependencyBinding<Client> {
  readonly kind: "lenso.capability";
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly descriptor_digest: string;
  readonly generated_client: string;
  readonly descriptor: CapabilityProviderDescriptor;
  bindProvider(provider: Provider): CapabilityProviderBinding;
  required(id?: string): CapabilityDependencyDeclaration<Client, "one">;
  optional(id?: string): CapabilityDependencyDeclaration<Client, "optional">;
  many(id?: string): CapabilityDependencyDeclaration<Client, "many">;
  readonly __client?: Client;
  readonly __provider?: Provider;
}

export interface DescribeRequest {

}

export interface DescribeResponse {
  routes: Array<DescribeResponseRoutesItem>;
}

export interface DescribeResponseRoutesItem {
  method: string;
  openapi?: Record<string, unknown>;
  path: string;
  route_id: string;
}

export interface HandleRequest {
  body: Bytes;
  credential?: HandleRequestCredential;
  headers: Array<HandleRequestHeadersItem>;
  method: string;
  path: string;
  path_parameters: Array<HandleRequestPathParametersItem>;
  query?: string;
  request_id: string;
  route_id: string;
}

export interface HandleRequestCredential {
  scheme: string;
  value: string;
}

export interface HandleRequestHeadersItem {
  name: string;
  value: string;
}

export interface HandleRequestPathParametersItem {
  name: string;
  value: string;
}

export interface HandleResponse {
  body: Bytes;
  headers: Array<HandleResponseHeadersItem>;
  status: number;
}

export interface HandleResponseHeadersItem {
  name: string;
  value: string;
}

export type DescribeError = "invalid_configuration" | UnknownDomainError;
export type DescribeInvocationError = { readonly kind: "domain"; readonly error: DescribeError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type DescribeResult = { readonly ok: true; readonly value: DescribeResponse } | { readonly ok: false; readonly error: DescribeInvocationError };
export type HandleError = "rejected" | UnknownDomainError;
export type HandleInvocationError = { readonly kind: "domain"; readonly error: HandleError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type HandleResult = { readonly ok: true; readonly value: HandleResponse } | { readonly ok: false; readonly error: HandleInvocationError };
export function encodeDescribeRequest(value: DescribeRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeDescribeRequest(wire: string): DescribeRequest { return lensoContractRuntime.decodePortableJson<DescribeRequest>(wire); }
export function encodeDescribeResponse(value: DescribeResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeDescribeResponse(wire: string): DescribeResponse { return lensoContractRuntime.decodePortableJson<DescribeResponse>(wire); }
export function encodeDescribeError(value: DescribeError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeDescribeError(wire: string): DescribeError { return lensoContractRuntime.decodeDomainError<DescribeError>(wire, ["invalid_configuration"]); }

export function encodeHandleRequest(value: HandleRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeHandleRequest(wire: string): HandleRequest { return lensoContractRuntime.decodePortableJson<HandleRequest>(wire); }
export function encodeHandleResponse(value: HandleResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeHandleResponse(wire: string): HandleResponse { return lensoContractRuntime.decodePortableJson<HandleResponse>(wire); }
export function encodeHandleError(value: HandleError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeHandleError(wire: string): HandleError { return lensoContractRuntime.decodeDomainError<HandleError>(wire, ["rejected"]); }


export interface EndpointClient {
  describe(request: DescribeRequest, context?: InvocationContext): Promise<DescribeResult>;
  handle(request: HandleRequest, context?: InvocationContext): Promise<HandleResult>;
}

export interface EndpointProvider {
  describe(context: InvocationContext, request: DescribeRequest): Promise<DescribeResult>;
  handle(context: InvocationContext, request: HandleRequest): Promise<HandleResult>;
}

export const Endpoint: CapabilityContractReference<EndpointClient, EndpointProvider> = { kind: "lenso.capability", ...bindEndpointDependency(), capability_id: CAPABILITY_ID, descriptor_version: DESCRIPTOR_VERSION, descriptor_digest: DESCRIPTOR_DIGEST, generated_client: "EndpointClient", descriptor: { capability_id: CAPABILITY_ID, descriptor_version: DESCRIPTOR_VERSION, operations: ["describe", "handle"], stream_operations: [], event_operations: [] }, bindProvider: bindEndpointProvider, required(id) { return { kind: "lenso.dependency", ...(id === undefined ? {} : { id }), contract: this, cardinality: "one" }; }, optional(id) { return { kind: "lenso.dependency", ...(id === undefined ? {} : { id }), contract: this, cardinality: "optional" }; }, many(id) { return { kind: "lenso.dependency", ...(id === undefined ? {} : { id }), contract: this, cardinality: "many" }; }, };
export const ENDPOINT_CONTRACT = Endpoint;

export type ProviderDispatchOutcome =
  | { readonly kind: "success"; readonly value: unknown }
  | { readonly kind: "domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
export type ProviderStreamActionOutcome =
  | { readonly kind: "accepted" }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
export type ProviderStreamReceiveOutcome =
  | { readonly kind: "message"; readonly value: unknown }
  | { readonly kind: "peer_half_closed" }
  | { readonly kind: "terminal_success" }
  | { readonly kind: "terminal_domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
/** @internal Runtime lowering seam. */
export interface ProviderStreamSessionBinding {
  send(message: unknown): Promise<ProviderStreamActionOutcome>;
  receive(): Promise<ProviderStreamReceiveOutcome>;
  closeSend(): Promise<ProviderStreamActionOutcome>;
  cancel(): void;
}
export type ProviderStreamOpenOutcome =
  | { readonly kind: "opened"; readonly stream: ProviderStreamSessionBinding }
  | { readonly kind: "domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
export type ProviderEventPublishOutcome =
  | { readonly kind: "accepted" }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };

export interface CapabilityProviderDescriptor {
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly operations: ReadonlyArray<string>;
  readonly stream_operations: ReadonlyArray<string>;
  readonly event_operations: ReadonlyArray<string>;
}

/** @internal Runtime lowering seam. */
export interface CapabilityProviderBinding {
  readonly descriptor: CapabilityProviderDescriptor;
  invokeRequest(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderDispatchOutcome>;
  openStream(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderStreamOpenOutcome>;
  publishEvent(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderEventPublishOutcome>;
}

function providerErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export function bindEndpointProvider(
  provider: EndpointProvider,
): CapabilityProviderBinding {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["describe", "handle"],
      stream_operations: [],
      event_operations: [],
    },
    async invokeRequest(operation, context, payload) {
      switch (operation) {
      case "describe": {
        let request: DescribeRequest;
        try {
          request = decodeDescribeRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.describe(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeDescribeResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeDescribeError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
        }
      }
      case "handle": {
        let request: HandleRequest;
        try {
          request = decodeHandleRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.handle(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeHandleResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeHandleError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
        }
      }
        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
    async openStream(operation, context, payload) {
      switch (operation) {

        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
    async publishEvent(operation, context, payload) {
      switch (operation) {

        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
  };
}

export type Provider = EndpointProvider;
export const bindProvider = bindEndpointProvider;

export type DependencyInvoker = (
  operation: string,
  context: InvocationContext,
  payload: unknown,
) => Promise<ProviderDispatchOutcome>;

export interface CapabilityDependencyBinding<Client> {
  readonly descriptor: CapabilityProviderDescriptor;
  createClient(invoke: DependencyInvoker): Client;
}

export interface CapabilityDependencyDeclaration<Client, Cardinality extends "one" | "optional" | "many"> {
  readonly kind: "lenso.dependency";
  readonly id?: string;
  readonly contract: CapabilityDependencyBinding<Client>;
  readonly cardinality: Cardinality;
}

function dependencyErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export function bindEndpointDependency(): CapabilityDependencyBinding<EndpointClient> {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["describe", "handle"],
      stream_operations: [],
      event_operations: [],
    },
    createClient(invoke) {
      return {
      async describe(request, context) {
        let payload: unknown;
        try {
          payload = JSON.parse(encodeDescribeRequest(request)) as unknown;
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "protocol_violation", detail: dependencyErrorMessage(error) } } };
        }
        const call = context ?? { requestId: "0" as Uint64, cancelled: false };
        try {
          const outcome = await invoke("describe", call, payload);
          if (outcome.kind === "success") {
            return { ok: true, value: decodeDescribeResponse(JSON.stringify(outcome.value)) };
          }
          if (outcome.kind === "domain") {
            return { ok: false, error: { kind: "domain", error: decodeDescribeError(JSON.stringify(outcome.value)) } };
          }
          return { ok: false, error: { kind: "runtime", error: outcome.failure } };
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "plugin_failure", detail: dependencyErrorMessage(error) } } };
        }
      },
      async handle(request, context) {
        let payload: unknown;
        try {
          payload = JSON.parse(encodeHandleRequest(request)) as unknown;
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "protocol_violation", detail: dependencyErrorMessage(error) } } };
        }
        const call = context ?? { requestId: "0" as Uint64, cancelled: false };
        try {
          const outcome = await invoke("handle", call, payload);
          if (outcome.kind === "success") {
            return { ok: true, value: decodeHandleResponse(JSON.stringify(outcome.value)) };
          }
          if (outcome.kind === "domain") {
            return { ok: false, error: { kind: "domain", error: decodeHandleError(JSON.stringify(outcome.value)) } };
          }
          return { ok: false, error: { kind: "runtime", error: outcome.failure } };
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "plugin_failure", detail: dependencyErrorMessage(error) } } };
        }
      },
      };
    },
  };
}

export const bindDependency = bindEndpointDependency;

export const portableValueProfile = lensoContractRuntime.portableValueProfile;
