/* @generated by lenso-contract-codegen; do not edit. */
import * as lensoContractRuntime from "@lenso/contract-runtime";

export const CAPABILITY_ID = "lenso.identity.directory@1";
export const DESCRIPTOR_VERSION = "1.0.0";
export const DESCRIPTOR_DIGEST = "sha256:1a2067f9a41179d5090f3095c4eef8ffb422ee788428ea567a9f9236d1636a91";
export const PORTABLE = true;
export const CROSS_LANE_TRANSFER = true;

export type Int64 = lensoContractRuntime.Int64;
export type Uint64 = lensoContractRuntime.Uint64;
export type Bytes = lensoContractRuntime.Bytes;
export type Timestamp = lensoContractRuntime.Timestamp;
export type Duration = lensoContractRuntime.Duration;
export type OptionalValue<T> = lensoContractRuntime.OptionalValue<T>;
export type InvocationContext = lensoContractRuntime.InvocationContext;
export type RuntimeFailure = lensoContractRuntime.RuntimeFailure;
export type UnknownDomainError = lensoContractRuntime.UnknownDomainError;
export type StreamEvent<Message, DomainError> = lensoContractRuntime.StreamEvent<Message, DomainError>;
export type StreamSession<Message, DomainError> = lensoContractRuntime.StreamSession<Message, DomainError>;

export interface CapabilityContractReference<Client> extends CapabilityDependencyBinding<Client> {
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly descriptor_digest: string;
  readonly generated_client: string;
  readonly __client?: Client;
}

export interface EnsureIdentityRequest {
  external_subject: string;
  provider: string;
}

export interface EnsureIdentityResponse {
  created: boolean;
  subject: string;
}

export interface ReadStatusRequest {
  subject: string;
}

export interface ReadStatusResponse {
  status: "active" | "disabled";
  subject: string;
}

export type EnsureIdentityError = "disabled" | "invalid_identity" | UnknownDomainError;
export type EnsureIdentityInvocationError = { readonly kind: "domain"; readonly error: EnsureIdentityError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type EnsureIdentityResult = { readonly ok: true; readonly value: EnsureIdentityResponse } | { readonly ok: false; readonly error: EnsureIdentityInvocationError };
export type ReadStatusError = "invalid_subject" | "not_found" | UnknownDomainError;
export type ReadStatusInvocationError = { readonly kind: "domain"; readonly error: ReadStatusError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type ReadStatusResult = { readonly ok: true; readonly value: ReadStatusResponse } | { readonly ok: false; readonly error: ReadStatusInvocationError };
export function encodeEnsureIdentityRequest(value: EnsureIdentityRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeEnsureIdentityRequest(wire: string): EnsureIdentityRequest { return lensoContractRuntime.decodePortableJson<EnsureIdentityRequest>(wire); }
export function encodeEnsureIdentityResponse(value: EnsureIdentityResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeEnsureIdentityResponse(wire: string): EnsureIdentityResponse { return lensoContractRuntime.decodePortableJson<EnsureIdentityResponse>(wire); }
export function encodeEnsureIdentityError(value: EnsureIdentityError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeEnsureIdentityError(wire: string): EnsureIdentityError { return lensoContractRuntime.decodeDomainError<EnsureIdentityError>(wire, ["disabled", "invalid_identity"]); }

export function encodeReadStatusRequest(value: ReadStatusRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeReadStatusRequest(wire: string): ReadStatusRequest { return lensoContractRuntime.decodePortableJson<ReadStatusRequest>(wire); }
export function encodeReadStatusResponse(value: ReadStatusResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeReadStatusResponse(wire: string): ReadStatusResponse { return lensoContractRuntime.decodePortableJson<ReadStatusResponse>(wire); }
export function encodeReadStatusError(value: ReadStatusError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeReadStatusError(wire: string): ReadStatusError { return lensoContractRuntime.decodeDomainError<ReadStatusError>(wire, ["invalid_subject", "not_found"]); }


export interface DirectoryClient {
  ensure_identity(request: EnsureIdentityRequest, context?: InvocationContext): Promise<EnsureIdentityResult>;
  read_status(request: ReadStatusRequest, context?: InvocationContext): Promise<ReadStatusResult>;
}

export interface DirectoryProvider {
  ensure_identity(context: InvocationContext, request: EnsureIdentityRequest): Promise<EnsureIdentityResult>;
  read_status(context: InvocationContext, request: ReadStatusRequest): Promise<ReadStatusResult>;
}

export const DIRECTORY_CONTRACT: CapabilityContractReference<DirectoryClient> = { ...bindDirectoryDependency(), capability_id: CAPABILITY_ID, descriptor_version: DESCRIPTOR_VERSION, descriptor_digest: DESCRIPTOR_DIGEST, generated_client: "DirectoryClient" };

export type ProviderDispatchOutcome =
  | { readonly kind: "success"; readonly value: unknown }
  | { readonly kind: "domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };

export interface CapabilityProviderDescriptor {
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly operations: ReadonlyArray<string>;
  readonly stream_operations: ReadonlyArray<string>;
  readonly event_operations: ReadonlyArray<string>;
}

export interface CapabilityProviderBinding {
  readonly descriptor: CapabilityProviderDescriptor;
  invokeRequest(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderDispatchOutcome>;
}

function providerErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export function bindDirectoryProvider(
  provider: DirectoryProvider,
): CapabilityProviderBinding {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["ensure_identity", "read_status"],
      stream_operations: [],
      event_operations: [],
    },
    async invokeRequest(operation, context, payload) {
      switch (operation) {
      case "ensure_identity": {
        let request: EnsureIdentityRequest;
        try {
          request = decodeEnsureIdentityRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.ensure_identity(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeEnsureIdentityResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeEnsureIdentityError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
        }
      }
      case "read_status": {
        let request: ReadStatusRequest;
        try {
          request = decodeReadStatusRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.read_status(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeReadStatusResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeReadStatusError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
        }
      }
        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
  };
}

export type Provider = DirectoryProvider;
export const bindProvider = bindDirectoryProvider;

export type DependencyInvoker = (
  operation: string,
  context: InvocationContext,
  payload: unknown,
) => Promise<ProviderDispatchOutcome>;

export interface CapabilityDependencyBinding<Client> {
  readonly descriptor: CapabilityProviderDescriptor;
  createClient(invoke: DependencyInvoker): Client;
}

function dependencyErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export function bindDirectoryDependency(): CapabilityDependencyBinding<DirectoryClient> {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["ensure_identity", "read_status"],
      stream_operations: [],
      event_operations: [],
    },
    createClient(invoke) {
      return {
      async ensure_identity(request, context) {
        let payload: unknown;
        try {
          payload = JSON.parse(encodeEnsureIdentityRequest(request)) as unknown;
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "protocol_violation", detail: dependencyErrorMessage(error) } } };
        }
        const call = context ?? { requestId: "0" as Uint64, cancelled: false };
        try {
          const outcome = await invoke("ensure_identity", call, payload);
          if (outcome.kind === "success") {
            return { ok: true, value: decodeEnsureIdentityResponse(JSON.stringify(outcome.value)) };
          }
          if (outcome.kind === "domain") {
            return { ok: false, error: { kind: "domain", error: decodeEnsureIdentityError(JSON.stringify(outcome.value)) } };
          }
          return { ok: false, error: { kind: "runtime", error: outcome.failure } };
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "plugin_failure", detail: dependencyErrorMessage(error) } } };
        }
      },
      async read_status(request, context) {
        let payload: unknown;
        try {
          payload = JSON.parse(encodeReadStatusRequest(request)) as unknown;
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "protocol_violation", detail: dependencyErrorMessage(error) } } };
        }
        const call = context ?? { requestId: "0" as Uint64, cancelled: false };
        try {
          const outcome = await invoke("read_status", call, payload);
          if (outcome.kind === "success") {
            return { ok: true, value: decodeReadStatusResponse(JSON.stringify(outcome.value)) };
          }
          if (outcome.kind === "domain") {
            return { ok: false, error: { kind: "domain", error: decodeReadStatusError(JSON.stringify(outcome.value)) } };
          }
          return { ok: false, error: { kind: "runtime", error: outcome.failure } };
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "plugin_failure", detail: dependencyErrorMessage(error) } } };
        }
      },
      };
    },
  };
}

export const bindDependency = bindDirectoryDependency;

export const portableValueProfile = lensoContractRuntime.portableValueProfile;
