/* @generated by lenso-contract-codegen; do not edit. */
import * as lensoContractRuntime from "@lenso/contract-runtime";

export const CAPABILITY_ID = "lenso.auth.oauth-flow@1";
export const DESCRIPTOR_VERSION = "1.0.0";
export const DESCRIPTOR_DIGEST = "sha256:a48fea8dc09de5b5b83df7d24e903b8f0623f713aef2f1305ed6536559771610";
export const PORTABLE = true;
export const CROSS_LANE_TRANSFER = true;

export type Int64 = lensoContractRuntime.Int64;
export type Uint64 = lensoContractRuntime.Uint64;
export type Bytes = lensoContractRuntime.Bytes;
export type Timestamp = lensoContractRuntime.Timestamp;
export type Duration = lensoContractRuntime.Duration;
export type OptionalValue<T> = lensoContractRuntime.OptionalValue<T>;
export type InvocationContext = lensoContractRuntime.InvocationContext;
export type RuntimeFailure = lensoContractRuntime.RuntimeFailure;
export type UnknownDomainError = lensoContractRuntime.UnknownDomainError;
export type StreamEvent<Message, DomainError> = lensoContractRuntime.StreamEvent<Message, DomainError>;
export type StreamSession<Message, DomainError> = lensoContractRuntime.StreamSession<Message, DomainError>;

export interface CapabilityContractReference<Client, Provider extends object> extends CapabilityDependencyBinding<Client> {
  readonly kind: "lenso.capability";
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly descriptor_digest: string;
  readonly generated_client: string;
  readonly descriptor: CapabilityProviderDescriptor;
  bindProvider(provider: Provider): CapabilityProviderBinding;
  required(id?: string): CapabilityDependencyDeclaration<Client, "one">;
  optional(id?: string): CapabilityDependencyDeclaration<Client, "optional">;
  many(id?: string): CapabilityDependencyDeclaration<Client, "many">;
  readonly __client?: Client;
  readonly __provider?: Provider;
}

export interface ConsumeRequest {
  provider: string;
  state: string;
}

export interface ConsumeResponse {
  code_verifier: string;
  expires_at: Timestamp;
  return_to: string;
}

export interface CreateRequest {
  expires_at: Timestamp;
  provider: string;
  return_to: string;
}

export interface CreateResponse {
  code_challenge: string;
  code_verifier: string;
  expires_at: Timestamp;
  state: string;
}

export type ConsumeError = "already_consumed" | "expired" | "invalid_state" | "provider_mismatch" | UnknownDomainError;
export type ConsumeInvocationError = { readonly kind: "domain"; readonly error: ConsumeError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type ConsumeResult = { readonly ok: true; readonly value: ConsumeResponse } | { readonly ok: false; readonly error: ConsumeInvocationError };
export type CreateError = "invalid_expiry" | "invalid_provider" | "invalid_return_to" | UnknownDomainError;
export type CreateInvocationError = { readonly kind: "domain"; readonly error: CreateError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type CreateResult = { readonly ok: true; readonly value: CreateResponse } | { readonly ok: false; readonly error: CreateInvocationError };
export function encodeConsumeRequest(value: ConsumeRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeConsumeRequest(wire: string): ConsumeRequest { return lensoContractRuntime.decodePortableJson<ConsumeRequest>(wire); }
export function encodeConsumeResponse(value: ConsumeResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeConsumeResponse(wire: string): ConsumeResponse { return lensoContractRuntime.decodePortableJson<ConsumeResponse>(wire); }
export function encodeConsumeError(value: ConsumeError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeConsumeError(wire: string): ConsumeError { return lensoContractRuntime.decodeDomainError<ConsumeError>(wire, ["already_consumed", "expired", "invalid_state", "provider_mismatch"]); }

export function encodeCreateRequest(value: CreateRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeCreateRequest(wire: string): CreateRequest { return lensoContractRuntime.decodePortableJson<CreateRequest>(wire); }
export function encodeCreateResponse(value: CreateResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeCreateResponse(wire: string): CreateResponse { return lensoContractRuntime.decodePortableJson<CreateResponse>(wire); }
export function encodeCreateError(value: CreateError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeCreateError(wire: string): CreateError { return lensoContractRuntime.decodeDomainError<CreateError>(wire, ["invalid_expiry", "invalid_provider", "invalid_return_to"]); }


export interface OauthFlowClient {
  consume(request: ConsumeRequest, context?: InvocationContext): Promise<ConsumeResult>;
  create(request: CreateRequest, context?: InvocationContext): Promise<CreateResult>;
}

export interface OauthFlowProvider {
  consume(context: InvocationContext, request: ConsumeRequest): Promise<ConsumeResult>;
  create(context: InvocationContext, request: CreateRequest): Promise<CreateResult>;
}

export const OauthFlow: CapabilityContractReference<OauthFlowClient, OauthFlowProvider> = { kind: "lenso.capability", ...bindOauthFlowDependency(), capability_id: CAPABILITY_ID, descriptor_version: DESCRIPTOR_VERSION, descriptor_digest: DESCRIPTOR_DIGEST, generated_client: "OauthFlowClient", descriptor: { capability_id: CAPABILITY_ID, descriptor_version: DESCRIPTOR_VERSION, operations: ["consume", "create"], stream_operations: [], event_operations: [] }, bindProvider: bindOauthFlowProvider, required(id) { return { kind: "lenso.dependency", ...(id === undefined ? {} : { id }), contract: this, cardinality: "one" }; }, optional(id) { return { kind: "lenso.dependency", ...(id === undefined ? {} : { id }), contract: this, cardinality: "optional" }; }, many(id) { return { kind: "lenso.dependency", ...(id === undefined ? {} : { id }), contract: this, cardinality: "many" }; }, };
export const OAUTH_FLOW_CONTRACT = OauthFlow;

export type ProviderDispatchOutcome =
  | { readonly kind: "success"; readonly value: unknown }
  | { readonly kind: "domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
export type ProviderStreamActionOutcome =
  | { readonly kind: "accepted" }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
export type ProviderStreamReceiveOutcome =
  | { readonly kind: "message"; readonly value: unknown }
  | { readonly kind: "peer_half_closed" }
  | { readonly kind: "terminal_success" }
  | { readonly kind: "terminal_domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
/** @internal Runtime lowering seam. */
export interface ProviderStreamSessionBinding {
  send(message: unknown): Promise<ProviderStreamActionOutcome>;
  receive(): Promise<ProviderStreamReceiveOutcome>;
  closeSend(): Promise<ProviderStreamActionOutcome>;
  cancel(): void;
}
export type ProviderStreamOpenOutcome =
  | { readonly kind: "opened"; readonly stream: ProviderStreamSessionBinding }
  | { readonly kind: "domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
export type ProviderEventPublishOutcome =
  | { readonly kind: "accepted" }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };

export interface CapabilityProviderDescriptor {
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly operations: ReadonlyArray<string>;
  readonly stream_operations: ReadonlyArray<string>;
  readonly event_operations: ReadonlyArray<string>;
}

/** @internal Runtime lowering seam. */
export interface CapabilityProviderBinding {
  readonly descriptor: CapabilityProviderDescriptor;
  invokeRequest(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderDispatchOutcome>;
  openStream(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderStreamOpenOutcome>;
  publishEvent(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderEventPublishOutcome>;
}

function providerErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export function bindOauthFlowProvider(
  provider: OauthFlowProvider,
): CapabilityProviderBinding {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["consume", "create"],
      stream_operations: [],
      event_operations: [],
    },
    async invokeRequest(operation, context, payload) {
      switch (operation) {
      case "consume": {
        let request: ConsumeRequest;
        try {
          request = decodeConsumeRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.consume(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeConsumeResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeConsumeError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
        }
      }
      case "create": {
        let request: CreateRequest;
        try {
          request = decodeCreateRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.create(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeCreateResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeCreateError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
        }
      }
        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
    async openStream(operation, context, payload) {
      switch (operation) {

        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
    async publishEvent(operation, context, payload) {
      switch (operation) {

        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
  };
}

export type Provider = OauthFlowProvider;
export const bindProvider = bindOauthFlowProvider;

export type DependencyInvoker = (
  operation: string,
  context: InvocationContext,
  payload: unknown,
) => Promise<ProviderDispatchOutcome>;

export interface CapabilityDependencyBinding<Client> {
  readonly descriptor: CapabilityProviderDescriptor;
  createClient(invoke: DependencyInvoker): Client;
}

export interface CapabilityDependencyDeclaration<Client, Cardinality extends "one" | "optional" | "many"> {
  readonly kind: "lenso.dependency";
  readonly id?: string;
  readonly contract: CapabilityDependencyBinding<Client>;
  readonly cardinality: Cardinality;
}

function dependencyErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export function bindOauthFlowDependency(): CapabilityDependencyBinding<OauthFlowClient> {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["consume", "create"],
      stream_operations: [],
      event_operations: [],
    },
    createClient(invoke) {
      return {
      async consume(request, context) {
        let payload: unknown;
        try {
          payload = JSON.parse(encodeConsumeRequest(request)) as unknown;
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "protocol_violation", detail: dependencyErrorMessage(error) } } };
        }
        const call = context ?? { requestId: "0" as Uint64, cancelled: false };
        try {
          const outcome = await invoke("consume", call, payload);
          if (outcome.kind === "success") {
            return { ok: true, value: decodeConsumeResponse(JSON.stringify(outcome.value)) };
          }
          if (outcome.kind === "domain") {
            return { ok: false, error: { kind: "domain", error: decodeConsumeError(JSON.stringify(outcome.value)) } };
          }
          return { ok: false, error: { kind: "runtime", error: outcome.failure } };
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "plugin_failure", detail: dependencyErrorMessage(error) } } };
        }
      },
      async create(request, context) {
        let payload: unknown;
        try {
          payload = JSON.parse(encodeCreateRequest(request)) as unknown;
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "protocol_violation", detail: dependencyErrorMessage(error) } } };
        }
        const call = context ?? { requestId: "0" as Uint64, cancelled: false };
        try {
          const outcome = await invoke("create", call, payload);
          if (outcome.kind === "success") {
            return { ok: true, value: decodeCreateResponse(JSON.stringify(outcome.value)) };
          }
          if (outcome.kind === "domain") {
            return { ok: false, error: { kind: "domain", error: decodeCreateError(JSON.stringify(outcome.value)) } };
          }
          return { ok: false, error: { kind: "runtime", error: outcome.failure } };
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "plugin_failure", detail: dependencyErrorMessage(error) } } };
        }
      },
      };
    },
  };
}

export const bindDependency = bindOauthFlowDependency;

export const portableValueProfile = lensoContractRuntime.portableValueProfile;
