/* @generated by lenso-contract-codegen; do not edit. */
import * as lensoContractRuntime from "@lenso/contract-runtime";

export const CAPABILITY_ID = "lenso.auth.oidc-provider@1";
export const DESCRIPTOR_VERSION = "1.0.0";
export const DESCRIPTOR_DIGEST = "sha256:2a0c7ec263bae3fd702bab778a396a9a2e6503d757d5d0f84d1afa4d4ccde1e1";
export const PORTABLE = true;
export const CROSS_LANE_TRANSFER = true;

export type Int64 = lensoContractRuntime.Int64;
export type Uint64 = lensoContractRuntime.Uint64;
export type Bytes = lensoContractRuntime.Bytes;
export type Timestamp = lensoContractRuntime.Timestamp;
export type Duration = lensoContractRuntime.Duration;
export type OptionalValue<T> = lensoContractRuntime.OptionalValue<T>;
export type InvocationContext = lensoContractRuntime.InvocationContext;
export type RuntimeFailure = lensoContractRuntime.RuntimeFailure;
export type UnknownDomainError = lensoContractRuntime.UnknownDomainError;
export type StreamEvent<Message, DomainError> = lensoContractRuntime.StreamEvent<Message, DomainError>;
export type StreamSession<Message, DomainError> = lensoContractRuntime.StreamSession<Message, DomainError>;

export interface CapabilityContractReference<Client, Provider extends object, Runtime extends DependencyInvoker = DependencyInvoker> extends CapabilityDependencyBinding<Client, Runtime> {
  readonly kind: "lenso.capability";
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly descriptor_digest: string;
  readonly generated_client: string;
  readonly descriptor: CapabilityProviderDescriptor;
  bindProvider(provider: Provider): CapabilityProviderBinding;
  required(id?: string): CapabilityDependencyDeclaration<Client, "one", Runtime>;
  optional(id?: string): CapabilityDependencyDeclaration<Client, "optional", Runtime>;
  many(id?: string): CapabilityDependencyDeclaration<Client, "many", Runtime>;
  readonly __client?: Client;
  readonly __provider?: Provider;
}

export interface AuthorizeRequest {
  client_id: string;
  code_challenge: string;
  code_challenge_method: string;
  nonce: string | null;
  redirect_uri: string;
  response_type: string;
  scope: string;
  state: string | null;
  subject: string;
}

export interface AuthorizeResponse {
  code: string;
  expires_at: Timestamp;
  redirect_uri: string;
  state: string | null;
}

export interface ExchangeRequest {
  client_id: string;
  code: string;
  code_verifier: string;
  grant_type: string;
  redirect_uri: string;
}

export interface ExchangeResponse {
  access_token: string;
  expires_in: number;
  id_token: string;
  scope: string;
  session_id: string;
  token_type: string;
}

export interface JwksRequest {

}

export interface JwksResponse {
  jwks: Record<string, unknown>;
}

export interface MetadataRequest {

}

export interface MetadataResponse {
  authorization_endpoint: string;
  client_id: string;
  issuer: string;
  jwks_uri: string;
  scopes_supported: Array<string>;
  token_endpoint: string;
}

export type AuthorizeError = "disabled_subject" | "forbidden" | "invalid_client" | "invalid_pkce" | "invalid_redirect_uri" | "invalid_request" | "invalid_scope" | UnknownDomainError;
export type AuthorizeInvocationError = { readonly kind: "domain"; readonly error: AuthorizeError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type AuthorizeResult = { readonly ok: true; readonly value: AuthorizeResponse } | { readonly ok: false; readonly error: AuthorizeInvocationError };
export type ExchangeError = "disabled_subject" | "invalid_grant" | "invalid_request" | UnknownDomainError;
export type ExchangeInvocationError = { readonly kind: "domain"; readonly error: ExchangeError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type ExchangeResult = { readonly ok: true; readonly value: ExchangeResponse } | { readonly ok: false; readonly error: ExchangeInvocationError };
export type JwksError = "disabled" | UnknownDomainError;
export type JwksInvocationError = { readonly kind: "domain"; readonly error: JwksError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type JwksResult = { readonly ok: true; readonly value: JwksResponse } | { readonly ok: false; readonly error: JwksInvocationError };
export type MetadataError = "disabled" | UnknownDomainError;
export type MetadataInvocationError = { readonly kind: "domain"; readonly error: MetadataError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type MetadataResult = { readonly ok: true; readonly value: MetadataResponse } | { readonly ok: false; readonly error: MetadataInvocationError };
export function encodeAuthorizeRequest(value: AuthorizeRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeAuthorizeRequest(wire: string): AuthorizeRequest { return lensoContractRuntime.decodePortableJson<AuthorizeRequest>(wire); }
export function encodeAuthorizeResponse(value: AuthorizeResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeAuthorizeResponse(wire: string): AuthorizeResponse { return lensoContractRuntime.decodePortableJson<AuthorizeResponse>(wire); }
export function encodeAuthorizeError(value: AuthorizeError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeAuthorizeError(wire: string): AuthorizeError { return lensoContractRuntime.decodeDomainError<AuthorizeError>(wire, ["disabled_subject", "forbidden", "invalid_client", "invalid_pkce", "invalid_redirect_uri", "invalid_request", "invalid_scope"]); }

export function encodeExchangeRequest(value: ExchangeRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeExchangeRequest(wire: string): ExchangeRequest { return lensoContractRuntime.decodePortableJson<ExchangeRequest>(wire); }
export function encodeExchangeResponse(value: ExchangeResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeExchangeResponse(wire: string): ExchangeResponse { return lensoContractRuntime.decodePortableJson<ExchangeResponse>(wire); }
export function encodeExchangeError(value: ExchangeError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeExchangeError(wire: string): ExchangeError { return lensoContractRuntime.decodeDomainError<ExchangeError>(wire, ["disabled_subject", "invalid_grant", "invalid_request"]); }

export function encodeJwksRequest(value: JwksRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeJwksRequest(wire: string): JwksRequest { return lensoContractRuntime.decodePortableJson<JwksRequest>(wire); }
export function encodeJwksResponse(value: JwksResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeJwksResponse(wire: string): JwksResponse { return lensoContractRuntime.decodePortableJson<JwksResponse>(wire); }
export function encodeJwksError(value: JwksError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeJwksError(wire: string): JwksError { return lensoContractRuntime.decodeDomainError<JwksError>(wire, ["disabled"]); }

export function encodeMetadataRequest(value: MetadataRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeMetadataRequest(wire: string): MetadataRequest { return lensoContractRuntime.decodePortableJson<MetadataRequest>(wire); }
export function encodeMetadataResponse(value: MetadataResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeMetadataResponse(wire: string): MetadataResponse { return lensoContractRuntime.decodePortableJson<MetadataResponse>(wire); }
export function encodeMetadataError(value: MetadataError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeMetadataError(wire: string): MetadataError { return lensoContractRuntime.decodeDomainError<MetadataError>(wire, ["disabled"]); }


export interface OidcProviderClient {
  authorize(request: AuthorizeRequest, context?: InvocationContext): Promise<AuthorizeResult>;
  exchange(request: ExchangeRequest, context?: InvocationContext): Promise<ExchangeResult>;
  jwks(request: JwksRequest, context?: InvocationContext): Promise<JwksResult>;
  metadata(request: MetadataRequest, context?: InvocationContext): Promise<MetadataResult>;
}

export interface OidcProviderProvider {
  authorize(context: InvocationContext, request: AuthorizeRequest): Promise<AuthorizeResult>;
  exchange(context: InvocationContext, request: ExchangeRequest): Promise<ExchangeResult>;
  jwks(context: InvocationContext, request: JwksRequest): Promise<JwksResult>;
  metadata(context: InvocationContext, request: MetadataRequest): Promise<MetadataResult>;
}

export const OidcProvider: CapabilityContractReference<OidcProviderClient, OidcProviderProvider, DependencyInvoker> = { kind: "lenso.capability", ...bindOidcProviderDependency(), capability_id: CAPABILITY_ID, descriptor_version: DESCRIPTOR_VERSION, descriptor_digest: DESCRIPTOR_DIGEST, generated_client: "OidcProviderClient", descriptor: { capability_id: CAPABILITY_ID, descriptor_version: DESCRIPTOR_VERSION, operations: ["authorize", "exchange", "jwks", "metadata"], stream_operations: [], event_operations: [] }, bindProvider: bindOidcProviderProvider, required(id) { return { kind: "lenso.dependency", ...(id === undefined ? {} : { id }), contract: this, cardinality: "one" }; }, optional(id) { return { kind: "lenso.dependency", ...(id === undefined ? {} : { id }), contract: this, cardinality: "optional" }; }, many(id) { return { kind: "lenso.dependency", ...(id === undefined ? {} : { id }), contract: this, cardinality: "many" }; }, };
export const OIDC_PROVIDER_CONTRACT = OidcProvider;

export type ProviderDispatchOutcome =
  | { readonly kind: "success"; readonly value: unknown }
  | { readonly kind: "domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
export type ProviderStreamActionOutcome =
  | { readonly kind: "accepted" }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
export type ProviderStreamReceiveOutcome =
  | { readonly kind: "message"; readonly value: unknown }
  | { readonly kind: "peer_half_closed" }
  | { readonly kind: "terminal_success" }
  | { readonly kind: "terminal_domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
/** @internal Runtime lowering seam. */
export interface ProviderStreamSessionBinding {
  send(message: unknown): Promise<ProviderStreamActionOutcome>;
  receive(): Promise<ProviderStreamReceiveOutcome>;
  closeSend(): Promise<ProviderStreamActionOutcome>;
  cancel(): void;
}
export type ProviderStreamOpenOutcome =
  | { readonly kind: "opened"; readonly stream: ProviderStreamSessionBinding }
  | { readonly kind: "domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
export type ProviderEventPublishOutcome =
  | { readonly kind: "accepted" }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };

export interface CapabilityProviderDescriptor {
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly operations: ReadonlyArray<string>;
  readonly stream_operations: ReadonlyArray<string>;
  readonly event_operations: ReadonlyArray<string>;
}

/** @internal Runtime lowering seam. */
export interface CapabilityProviderBinding {
  readonly descriptor: CapabilityProviderDescriptor;
  invokeRequest(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderDispatchOutcome>;
  openStream(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderStreamOpenOutcome>;
  publishEvent(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderEventPublishOutcome>;
}

function providerErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export function bindOidcProviderProvider(
  provider: OidcProviderProvider,
): CapabilityProviderBinding {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["authorize", "exchange", "jwks", "metadata"],
      stream_operations: [],
      event_operations: [],
    },
    async invokeRequest(operation, context, payload) {
      switch (operation) {
      case "authorize": {
        let request: AuthorizeRequest;
        try {
          request = decodeAuthorizeRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.authorize(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeAuthorizeResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeAuthorizeError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
        }
      }
      case "exchange": {
        let request: ExchangeRequest;
        try {
          request = decodeExchangeRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.exchange(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeExchangeResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeExchangeError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
        }
      }
      case "jwks": {
        let request: JwksRequest;
        try {
          request = decodeJwksRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.jwks(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeJwksResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeJwksError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
        }
      }
      case "metadata": {
        let request: MetadataRequest;
        try {
          request = decodeMetadataRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.metadata(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeMetadataResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeMetadataError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
        }
      }
        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
    async openStream(operation, context, payload) {
      switch (operation) {

        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
    async publishEvent(operation, context, payload) {
      switch (operation) {

        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
  };
}

export type Provider = OidcProviderProvider;
export const bindProvider = bindOidcProviderProvider;

export type DependencyInvoker = (
  operation: string,
  context: InvocationContext,
  payload: unknown,
) => Promise<ProviderDispatchOutcome>;

export type InteractionDependencyInvoker = DependencyInvoker & {
  readonly providerInstance: string;
  openStream(operation: string, context: InvocationContext, payload: unknown): Promise<ProviderStreamOpenOutcome>;
  publishEvent(operation: string, context: InvocationContext, payload: unknown): Promise<ProviderEventPublishOutcome>;
};

export interface CapabilityDependencyBinding<Client, Runtime extends DependencyInvoker = DependencyInvoker> {
  readonly descriptor: CapabilityProviderDescriptor;
  createClient(invoke: Runtime): Client;
}

export interface CapabilityDependencyDeclaration<Client, Cardinality extends "one" | "optional" | "many", Runtime extends DependencyInvoker = DependencyInvoker> {
  readonly kind: "lenso.dependency";
  readonly id?: string;
  readonly contract: CapabilityDependencyBinding<Client, Runtime>;
  readonly cardinality: Cardinality;
}

function dependencyErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function dependencyRuntimeError(failure: RuntimeFailure): Error {
  return Object.assign(new Error(`Capability dependency failed: ${failure.kind}`), { failure });
}

function dependencyFailure(error: unknown): RuntimeFailure {
  if (typeof error === "object" && error !== null && "failure" in error) return (error as { failure: RuntimeFailure }).failure;
  return { kind: "plugin_failure", detail: dependencyErrorMessage(error) };
}

export function bindOidcProviderDependency(): CapabilityDependencyBinding<OidcProviderClient, DependencyInvoker> {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["authorize", "exchange", "jwks", "metadata"],
      stream_operations: [],
      event_operations: [],
    },
    createClient(invoke) {
      return {
      async authorize(request, context) {
        let payload: unknown;
        try {
          payload = JSON.parse(encodeAuthorizeRequest(request)) as unknown;
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "protocol_violation", detail: dependencyErrorMessage(error) } } };
        }
        const call = context ?? { requestId: "0" as Uint64, cancelled: false };
        try {
          const outcome = await invoke("authorize", call, payload);
          if (outcome.kind === "success") {
            return { ok: true, value: decodeAuthorizeResponse(JSON.stringify(outcome.value)) };
          }
          if (outcome.kind === "domain") {
            return { ok: false, error: { kind: "domain", error: decodeAuthorizeError(JSON.stringify(outcome.value)) } };
          }
          return { ok: false, error: { kind: "runtime", error: outcome.failure } };
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "plugin_failure", detail: dependencyErrorMessage(error) } } };
        }
      },
      async exchange(request, context) {
        let payload: unknown;
        try {
          payload = JSON.parse(encodeExchangeRequest(request)) as unknown;
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "protocol_violation", detail: dependencyErrorMessage(error) } } };
        }
        const call = context ?? { requestId: "0" as Uint64, cancelled: false };
        try {
          const outcome = await invoke("exchange", call, payload);
          if (outcome.kind === "success") {
            return { ok: true, value: decodeExchangeResponse(JSON.stringify(outcome.value)) };
          }
          if (outcome.kind === "domain") {
            return { ok: false, error: { kind: "domain", error: decodeExchangeError(JSON.stringify(outcome.value)) } };
          }
          return { ok: false, error: { kind: "runtime", error: outcome.failure } };
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "plugin_failure", detail: dependencyErrorMessage(error) } } };
        }
      },
      async jwks(request, context) {
        let payload: unknown;
        try {
          payload = JSON.parse(encodeJwksRequest(request)) as unknown;
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "protocol_violation", detail: dependencyErrorMessage(error) } } };
        }
        const call = context ?? { requestId: "0" as Uint64, cancelled: false };
        try {
          const outcome = await invoke("jwks", call, payload);
          if (outcome.kind === "success") {
            return { ok: true, value: decodeJwksResponse(JSON.stringify(outcome.value)) };
          }
          if (outcome.kind === "domain") {
            return { ok: false, error: { kind: "domain", error: decodeJwksError(JSON.stringify(outcome.value)) } };
          }
          return { ok: false, error: { kind: "runtime", error: outcome.failure } };
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "plugin_failure", detail: dependencyErrorMessage(error) } } };
        }
      },
      async metadata(request, context) {
        let payload: unknown;
        try {
          payload = JSON.parse(encodeMetadataRequest(request)) as unknown;
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "protocol_violation", detail: dependencyErrorMessage(error) } } };
        }
        const call = context ?? { requestId: "0" as Uint64, cancelled: false };
        try {
          const outcome = await invoke("metadata", call, payload);
          if (outcome.kind === "success") {
            return { ok: true, value: decodeMetadataResponse(JSON.stringify(outcome.value)) };
          }
          if (outcome.kind === "domain") {
            return { ok: false, error: { kind: "domain", error: decodeMetadataError(JSON.stringify(outcome.value)) } };
          }
          return { ok: false, error: { kind: "runtime", error: outcome.failure } };
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "plugin_failure", detail: dependencyErrorMessage(error) } } };
        }
      },
      };
    },
  };
}

export const bindDependency = bindOidcProviderDependency;

export const portableValueProfile = lensoContractRuntime.portableValueProfile;
