/* @generated by lenso-contract-codegen; do not edit. */
import * as lensoContractRuntime from "@lenso/contract-runtime";

export const CAPABILITY_ID = "lenso.auth.oidc-provider@1";
export const DESCRIPTOR_VERSION = "1.0.0";
export const PORTABLE = true;
export const CROSS_LANE_TRANSFER = true;

export type Int64 = lensoContractRuntime.Int64;
export type Uint64 = lensoContractRuntime.Uint64;
export type Bytes = lensoContractRuntime.Bytes;
export type Timestamp = lensoContractRuntime.Timestamp;
export type Duration = lensoContractRuntime.Duration;
export type OptionalValue<T> = lensoContractRuntime.OptionalValue<T>;
export type InvocationContext = lensoContractRuntime.InvocationContext;
export type RuntimeFailure = lensoContractRuntime.RuntimeFailure;
export type UnknownDomainError = lensoContractRuntime.UnknownDomainError;
export type StreamEvent<Message, DomainError> = lensoContractRuntime.StreamEvent<Message, DomainError>;
export type StreamSession<Message, DomainError> = lensoContractRuntime.StreamSession<Message, DomainError>;

export interface AuthorizeRequest {
  client_id: string;
  code_challenge: string;
  code_challenge_method: string;
  nonce: string | null;
  redirect_uri: string;
  response_type: string;
  scope: string;
  state: string | null;
  subject: string;
}

export interface AuthorizeResponse {
  code: string;
  expires_at: Timestamp;
  redirect_uri: string;
  state: string | null;
}

export interface ExchangeRequest {
  client_id: string;
  code: string;
  code_verifier: string;
  grant_type: string;
  redirect_uri: string;
}

export interface ExchangeResponse {
  access_token: string;
  expires_in: number;
  id_token: string;
  scope: string;
  session_id: string;
  token_type: string;
}

export interface JwksRequest {

}

export interface JwksResponse {
  jwks: Record<string, unknown>;
}

export interface MetadataRequest {

}

export interface MetadataResponse {
  authorization_endpoint: string;
  client_id: string;
  issuer: string;
  jwks_uri: string;
  scopes_supported: Array<string>;
  token_endpoint: string;
}

export type AuthorizeError = "disabled_subject" | "forbidden" | "invalid_client" | "invalid_pkce" | "invalid_redirect_uri" | "invalid_request" | "invalid_scope" | UnknownDomainError;
export type AuthorizeInvocationError = { readonly kind: "domain"; readonly error: AuthorizeError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type AuthorizeResult = { readonly ok: true; readonly value: AuthorizeResponse } | { readonly ok: false; readonly error: AuthorizeInvocationError };
export type ExchangeError = "disabled_subject" | "invalid_grant" | "invalid_request" | UnknownDomainError;
export type ExchangeInvocationError = { readonly kind: "domain"; readonly error: ExchangeError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type ExchangeResult = { readonly ok: true; readonly value: ExchangeResponse } | { readonly ok: false; readonly error: ExchangeInvocationError };
export type JwksError = "disabled" | UnknownDomainError;
export type JwksInvocationError = { readonly kind: "domain"; readonly error: JwksError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type JwksResult = { readonly ok: true; readonly value: JwksResponse } | { readonly ok: false; readonly error: JwksInvocationError };
export type MetadataError = "disabled" | UnknownDomainError;
export type MetadataInvocationError = { readonly kind: "domain"; readonly error: MetadataError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type MetadataResult = { readonly ok: true; readonly value: MetadataResponse } | { readonly ok: false; readonly error: MetadataInvocationError };
export function encodeAuthorizeRequest(value: AuthorizeRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeAuthorizeRequest(wire: string): AuthorizeRequest { return lensoContractRuntime.decodePortableJson<AuthorizeRequest>(wire); }
export function encodeAuthorizeResponse(value: AuthorizeResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeAuthorizeResponse(wire: string): AuthorizeResponse { return lensoContractRuntime.decodePortableJson<AuthorizeResponse>(wire); }
export function encodeAuthorizeError(value: AuthorizeError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeAuthorizeError(wire: string): AuthorizeError { return lensoContractRuntime.decodeDomainError<AuthorizeError>(wire, ["disabled_subject", "forbidden", "invalid_client", "invalid_pkce", "invalid_redirect_uri", "invalid_request", "invalid_scope"]); }

export function encodeExchangeRequest(value: ExchangeRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeExchangeRequest(wire: string): ExchangeRequest { return lensoContractRuntime.decodePortableJson<ExchangeRequest>(wire); }
export function encodeExchangeResponse(value: ExchangeResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeExchangeResponse(wire: string): ExchangeResponse { return lensoContractRuntime.decodePortableJson<ExchangeResponse>(wire); }
export function encodeExchangeError(value: ExchangeError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeExchangeError(wire: string): ExchangeError { return lensoContractRuntime.decodeDomainError<ExchangeError>(wire, ["disabled_subject", "invalid_grant", "invalid_request"]); }

export function encodeJwksRequest(value: JwksRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeJwksRequest(wire: string): JwksRequest { return lensoContractRuntime.decodePortableJson<JwksRequest>(wire); }
export function encodeJwksResponse(value: JwksResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeJwksResponse(wire: string): JwksResponse { return lensoContractRuntime.decodePortableJson<JwksResponse>(wire); }
export function encodeJwksError(value: JwksError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeJwksError(wire: string): JwksError { return lensoContractRuntime.decodeDomainError<JwksError>(wire, ["disabled"]); }

export function encodeMetadataRequest(value: MetadataRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeMetadataRequest(wire: string): MetadataRequest { return lensoContractRuntime.decodePortableJson<MetadataRequest>(wire); }
export function encodeMetadataResponse(value: MetadataResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeMetadataResponse(wire: string): MetadataResponse { return lensoContractRuntime.decodePortableJson<MetadataResponse>(wire); }
export function encodeMetadataError(value: MetadataError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeMetadataError(wire: string): MetadataError { return lensoContractRuntime.decodeDomainError<MetadataError>(wire, ["disabled"]); }


export interface OidcProviderClient {
  authorize(request: AuthorizeRequest, context?: InvocationContext): Promise<AuthorizeResult>;
  exchange(request: ExchangeRequest, context?: InvocationContext): Promise<ExchangeResult>;
  jwks(request: JwksRequest, context?: InvocationContext): Promise<JwksResult>;
  metadata(request: MetadataRequest, context?: InvocationContext): Promise<MetadataResult>;
}

export interface OidcProviderProvider {
  authorize(context: InvocationContext, request: AuthorizeRequest): Promise<AuthorizeResult>;
  exchange(context: InvocationContext, request: ExchangeRequest): Promise<ExchangeResult>;
  jwks(context: InvocationContext, request: JwksRequest): Promise<JwksResult>;
  metadata(context: InvocationContext, request: MetadataRequest): Promise<MetadataResult>;
}

export type ProviderDispatchOutcome =
  | { readonly kind: "success"; readonly value: unknown }
  | { readonly kind: "domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };

export interface CapabilityProviderDescriptor {
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly operations: ReadonlyArray<string>;
  readonly stream_operations: ReadonlyArray<string>;
  readonly event_operations: ReadonlyArray<string>;
}

export interface CapabilityProviderBinding {
  readonly descriptor: CapabilityProviderDescriptor;
  invokeRequest(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderDispatchOutcome>;
}

function providerErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export function bindOidcProviderProvider(
  provider: OidcProviderProvider,
): CapabilityProviderBinding {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["authorize", "exchange", "jwks", "metadata"],
      stream_operations: [],
      event_operations: [],
    },
    async invokeRequest(operation, context, payload) {
      switch (operation) {
      case "authorize": {
        let request: AuthorizeRequest;
        try {
          request = decodeAuthorizeRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.authorize(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeAuthorizeResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeAuthorizeError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "module_failure", detail: providerErrorMessage(error) } };
        }
      }
      case "exchange": {
        let request: ExchangeRequest;
        try {
          request = decodeExchangeRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.exchange(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeExchangeResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeExchangeError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "module_failure", detail: providerErrorMessage(error) } };
        }
      }
      case "jwks": {
        let request: JwksRequest;
        try {
          request = decodeJwksRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.jwks(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeJwksResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeJwksError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "module_failure", detail: providerErrorMessage(error) } };
        }
      }
      case "metadata": {
        let request: MetadataRequest;
        try {
          request = decodeMetadataRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.metadata(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeMetadataResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeMetadataError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "module_failure", detail: providerErrorMessage(error) } };
        }
      }
        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
  };
}

export type Provider = OidcProviderProvider;
export const bindProvider = bindOidcProviderProvider;

export const portableValueProfile = lensoContractRuntime.portableValueProfile;
