/* @generated by lenso-contract-codegen; do not edit. */
import * as lensoContractRuntime from "@lenso/contract-runtime";

export const CAPABILITY_ID = "lenso.auth.password@1";
export const DESCRIPTOR_VERSION = "1.0.0";
export const PORTABLE = true;
export const CROSS_LANE_TRANSFER = true;

export type Int64 = lensoContractRuntime.Int64;
export type Uint64 = lensoContractRuntime.Uint64;
export type Bytes = lensoContractRuntime.Bytes;
export type Timestamp = lensoContractRuntime.Timestamp;
export type Duration = lensoContractRuntime.Duration;
export type OptionalValue<T> = lensoContractRuntime.OptionalValue<T>;
export type InvocationContext = lensoContractRuntime.InvocationContext;
export type RuntimeFailure = lensoContractRuntime.RuntimeFailure;
export type UnknownDomainError = lensoContractRuntime.UnknownDomainError;
export type StreamEvent<Message, DomainError> = lensoContractRuntime.StreamEvent<Message, DomainError>;
export type StreamSession<Message, DomainError> = lensoContractRuntime.StreamSession<Message, DomainError>;

export interface LoginRequest {
  identifier: string;
  password: string;
}

export interface LoginResponse {
  credential: string;
  expires_at: Timestamp;
  session_id: string;
  subject: string;
}

export interface RegisterRequest {
  identifier: string;
  password: string;
}

export interface RegisterResponse {
  credential: string;
  expires_at: Timestamp;
  session_id: string;
  subject: string;
}

export type LoginError = "disabled" | "invalid_credentials" | "invalid_identifier" | "rate_limited" | UnknownDomainError;
export type LoginInvocationError = { readonly kind: "domain"; readonly error: LoginError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type LoginResult = { readonly ok: true; readonly value: LoginResponse } | { readonly ok: false; readonly error: LoginInvocationError };
export type RegisterError = "disabled" | "identifier_taken" | "invalid_identifier" | "weak_password" | UnknownDomainError;
export type RegisterInvocationError = { readonly kind: "domain"; readonly error: RegisterError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type RegisterResult = { readonly ok: true; readonly value: RegisterResponse } | { readonly ok: false; readonly error: RegisterInvocationError };
export function encodeLoginRequest(value: LoginRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeLoginRequest(wire: string): LoginRequest { return lensoContractRuntime.decodePortableJson<LoginRequest>(wire); }
export function encodeLoginResponse(value: LoginResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeLoginResponse(wire: string): LoginResponse { return lensoContractRuntime.decodePortableJson<LoginResponse>(wire); }
export function encodeLoginError(value: LoginError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeLoginError(wire: string): LoginError { return lensoContractRuntime.decodeDomainError<LoginError>(wire, ["disabled", "invalid_credentials", "invalid_identifier", "rate_limited"]); }

export function encodeRegisterRequest(value: RegisterRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeRegisterRequest(wire: string): RegisterRequest { return lensoContractRuntime.decodePortableJson<RegisterRequest>(wire); }
export function encodeRegisterResponse(value: RegisterResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeRegisterResponse(wire: string): RegisterResponse { return lensoContractRuntime.decodePortableJson<RegisterResponse>(wire); }
export function encodeRegisterError(value: RegisterError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeRegisterError(wire: string): RegisterError { return lensoContractRuntime.decodeDomainError<RegisterError>(wire, ["disabled", "identifier_taken", "invalid_identifier", "weak_password"]); }


export interface PasswordClient {
  login(request: LoginRequest, context?: InvocationContext): Promise<LoginResult>;
  register(request: RegisterRequest, context?: InvocationContext): Promise<RegisterResult>;
}

export interface PasswordProvider {
  login(context: InvocationContext, request: LoginRequest): Promise<LoginResult>;
  register(context: InvocationContext, request: RegisterRequest): Promise<RegisterResult>;
}

export type ProviderDispatchOutcome =
  | { readonly kind: "success"; readonly value: unknown }
  | { readonly kind: "domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };

export interface CapabilityProviderDescriptor {
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly operations: ReadonlyArray<string>;
  readonly stream_operations: ReadonlyArray<string>;
  readonly event_operations: ReadonlyArray<string>;
}

export interface CapabilityProviderBinding {
  readonly descriptor: CapabilityProviderDescriptor;
  invokeRequest(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderDispatchOutcome>;
}

function providerErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export function bindPasswordProvider(
  provider: PasswordProvider,
): CapabilityProviderBinding {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["login", "register"],
      stream_operations: [],
      event_operations: [],
    },
    async invokeRequest(operation, context, payload) {
      switch (operation) {
      case "login": {
        let request: LoginRequest;
        try {
          request = decodeLoginRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.login(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeLoginResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeLoginError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "module_failure", detail: providerErrorMessage(error) } };
        }
      }
      case "register": {
        let request: RegisterRequest;
        try {
          request = decodeRegisterRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.register(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeRegisterResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeRegisterError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "module_failure", detail: providerErrorMessage(error) } };
        }
      }
        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
  };
}

export type Provider = PasswordProvider;
export const bindProvider = bindPasswordProvider;

export const portableValueProfile = lensoContractRuntime.portableValueProfile;
