/* @generated by lenso-contract-codegen; do not edit. */
import * as lensoContractRuntime from "@lenso/contract-runtime";

export const CAPABILITY_ID = "lenso.auth.password@1";
export const DESCRIPTOR_VERSION = "1.0.0";
export const DESCRIPTOR_DIGEST = "sha256:49bcdc6966b97438419f6de15a3d929a8dab45f78dc9e1b27b0ce122f8f21b80";
export const PORTABLE = true;
export const CROSS_LANE_TRANSFER = true;

export type Int64 = lensoContractRuntime.Int64;
export type Uint64 = lensoContractRuntime.Uint64;
export type Bytes = lensoContractRuntime.Bytes;
export type Timestamp = lensoContractRuntime.Timestamp;
export type Duration = lensoContractRuntime.Duration;
export type OptionalValue<T> = lensoContractRuntime.OptionalValue<T>;
export type InvocationContext = lensoContractRuntime.InvocationContext;
export type RuntimeFailure = lensoContractRuntime.RuntimeFailure;
export type UnknownDomainError = lensoContractRuntime.UnknownDomainError;
export type StreamEvent<Message, DomainError> = lensoContractRuntime.StreamEvent<Message, DomainError>;
export type StreamSession<Message, DomainError> = lensoContractRuntime.StreamSession<Message, DomainError>;

export interface CapabilityContractReference<Client, Provider extends object> extends CapabilityDependencyBinding<Client> {
  readonly kind: "lenso.capability";
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly descriptor_digest: string;
  readonly generated_client: string;
  readonly descriptor: CapabilityProviderDescriptor;
  bindProvider(provider: Provider): CapabilityProviderBinding;
  required(id?: string): CapabilityDependencyDeclaration<Client, "one">;
  optional(id?: string): CapabilityDependencyDeclaration<Client, "optional">;
  many(id?: string): CapabilityDependencyDeclaration<Client, "many">;
  readonly __client?: Client;
  readonly __provider?: Provider;
}

export interface LoginRequest {
  identifier: string;
  password: string;
}

export interface LoginResponse {
  credential: string;
  expires_at: Timestamp;
  session_id: string;
  subject: string;
}

export interface RegisterRequest {
  identifier: string;
  password: string;
}

export interface RegisterResponse {
  credential: string;
  expires_at: Timestamp;
  session_id: string;
  subject: string;
}

export type LoginError = "disabled" | "invalid_credentials" | "invalid_identifier" | "rate_limited" | UnknownDomainError;
export type LoginInvocationError = { readonly kind: "domain"; readonly error: LoginError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type LoginResult = { readonly ok: true; readonly value: LoginResponse } | { readonly ok: false; readonly error: LoginInvocationError };
export type RegisterError = "disabled" | "identifier_taken" | "invalid_identifier" | "weak_password" | UnknownDomainError;
export type RegisterInvocationError = { readonly kind: "domain"; readonly error: RegisterError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type RegisterResult = { readonly ok: true; readonly value: RegisterResponse } | { readonly ok: false; readonly error: RegisterInvocationError };
export function encodeLoginRequest(value: LoginRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeLoginRequest(wire: string): LoginRequest { return lensoContractRuntime.decodePortableJson<LoginRequest>(wire); }
export function encodeLoginResponse(value: LoginResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeLoginResponse(wire: string): LoginResponse { return lensoContractRuntime.decodePortableJson<LoginResponse>(wire); }
export function encodeLoginError(value: LoginError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeLoginError(wire: string): LoginError { return lensoContractRuntime.decodeDomainError<LoginError>(wire, ["disabled", "invalid_credentials", "invalid_identifier", "rate_limited"]); }

export function encodeRegisterRequest(value: RegisterRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeRegisterRequest(wire: string): RegisterRequest { return lensoContractRuntime.decodePortableJson<RegisterRequest>(wire); }
export function encodeRegisterResponse(value: RegisterResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeRegisterResponse(wire: string): RegisterResponse { return lensoContractRuntime.decodePortableJson<RegisterResponse>(wire); }
export function encodeRegisterError(value: RegisterError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeRegisterError(wire: string): RegisterError { return lensoContractRuntime.decodeDomainError<RegisterError>(wire, ["disabled", "identifier_taken", "invalid_identifier", "weak_password"]); }


export interface PasswordClient {
  login(request: LoginRequest, context?: InvocationContext): Promise<LoginResult>;
  register(request: RegisterRequest, context?: InvocationContext): Promise<RegisterResult>;
}

export interface PasswordProvider {
  login(context: InvocationContext, request: LoginRequest): Promise<LoginResult>;
  register(context: InvocationContext, request: RegisterRequest): Promise<RegisterResult>;
}

export const Password: CapabilityContractReference<PasswordClient, PasswordProvider> = { kind: "lenso.capability", ...bindPasswordDependency(), capability_id: CAPABILITY_ID, descriptor_version: DESCRIPTOR_VERSION, descriptor_digest: DESCRIPTOR_DIGEST, generated_client: "PasswordClient", descriptor: { capability_id: CAPABILITY_ID, descriptor_version: DESCRIPTOR_VERSION, operations: ["login", "register"], stream_operations: [], event_operations: [] }, bindProvider: bindPasswordProvider, required(id) { return { kind: "lenso.dependency", ...(id === undefined ? {} : { id }), contract: this, cardinality: "one" }; }, optional(id) { return { kind: "lenso.dependency", ...(id === undefined ? {} : { id }), contract: this, cardinality: "optional" }; }, many(id) { return { kind: "lenso.dependency", ...(id === undefined ? {} : { id }), contract: this, cardinality: "many" }; }, };
export const PASSWORD_CONTRACT = Password;

export type ProviderDispatchOutcome =
  | { readonly kind: "success"; readonly value: unknown }
  | { readonly kind: "domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
export type ProviderStreamActionOutcome =
  | { readonly kind: "accepted" }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
export type ProviderStreamReceiveOutcome =
  | { readonly kind: "message"; readonly value: unknown }
  | { readonly kind: "peer_half_closed" }
  | { readonly kind: "terminal_success" }
  | { readonly kind: "terminal_domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
/** @internal Runtime lowering seam. */
export interface ProviderStreamSessionBinding {
  send(message: unknown): Promise<ProviderStreamActionOutcome>;
  receive(): Promise<ProviderStreamReceiveOutcome>;
  closeSend(): Promise<ProviderStreamActionOutcome>;
  cancel(): void;
}
export type ProviderStreamOpenOutcome =
  | { readonly kind: "opened"; readonly stream: ProviderStreamSessionBinding }
  | { readonly kind: "domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
export type ProviderEventPublishOutcome =
  | { readonly kind: "accepted" }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };

export interface CapabilityProviderDescriptor {
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly operations: ReadonlyArray<string>;
  readonly stream_operations: ReadonlyArray<string>;
  readonly event_operations: ReadonlyArray<string>;
}

/** @internal Runtime lowering seam. */
export interface CapabilityProviderBinding {
  readonly descriptor: CapabilityProviderDescriptor;
  invokeRequest(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderDispatchOutcome>;
  openStream(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderStreamOpenOutcome>;
  publishEvent(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderEventPublishOutcome>;
}

function providerErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export function bindPasswordProvider(
  provider: PasswordProvider,
): CapabilityProviderBinding {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["login", "register"],
      stream_operations: [],
      event_operations: [],
    },
    async invokeRequest(operation, context, payload) {
      switch (operation) {
      case "login": {
        let request: LoginRequest;
        try {
          request = decodeLoginRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.login(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeLoginResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeLoginError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
        }
      }
      case "register": {
        let request: RegisterRequest;
        try {
          request = decodeRegisterRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.register(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeRegisterResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeRegisterError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
        }
      }
        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
    async openStream(operation, context, payload) {
      switch (operation) {

        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
    async publishEvent(operation, context, payload) {
      switch (operation) {

        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
  };
}

export type Provider = PasswordProvider;
export const bindProvider = bindPasswordProvider;

export type DependencyInvoker = (
  operation: string,
  context: InvocationContext,
  payload: unknown,
) => Promise<ProviderDispatchOutcome>;

export interface CapabilityDependencyBinding<Client> {
  readonly descriptor: CapabilityProviderDescriptor;
  createClient(invoke: DependencyInvoker): Client;
}

export interface CapabilityDependencyDeclaration<Client, Cardinality extends "one" | "optional" | "many"> {
  readonly kind: "lenso.dependency";
  readonly id?: string;
  readonly contract: CapabilityDependencyBinding<Client>;
  readonly cardinality: Cardinality;
}

function dependencyErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export function bindPasswordDependency(): CapabilityDependencyBinding<PasswordClient> {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["login", "register"],
      stream_operations: [],
      event_operations: [],
    },
    createClient(invoke) {
      return {
      async login(request, context) {
        let payload: unknown;
        try {
          payload = JSON.parse(encodeLoginRequest(request)) as unknown;
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "protocol_violation", detail: dependencyErrorMessage(error) } } };
        }
        const call = context ?? { requestId: "0" as Uint64, cancelled: false };
        try {
          const outcome = await invoke("login", call, payload);
          if (outcome.kind === "success") {
            return { ok: true, value: decodeLoginResponse(JSON.stringify(outcome.value)) };
          }
          if (outcome.kind === "domain") {
            return { ok: false, error: { kind: "domain", error: decodeLoginError(JSON.stringify(outcome.value)) } };
          }
          return { ok: false, error: { kind: "runtime", error: outcome.failure } };
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "plugin_failure", detail: dependencyErrorMessage(error) } } };
        }
      },
      async register(request, context) {
        let payload: unknown;
        try {
          payload = JSON.parse(encodeRegisterRequest(request)) as unknown;
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "protocol_violation", detail: dependencyErrorMessage(error) } } };
        }
        const call = context ?? { requestId: "0" as Uint64, cancelled: false };
        try {
          const outcome = await invoke("register", call, payload);
          if (outcome.kind === "success") {
            return { ok: true, value: decodeRegisterResponse(JSON.stringify(outcome.value)) };
          }
          if (outcome.kind === "domain") {
            return { ok: false, error: { kind: "domain", error: decodeRegisterError(JSON.stringify(outcome.value)) } };
          }
          return { ok: false, error: { kind: "runtime", error: outcome.failure } };
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "plugin_failure", detail: dependencyErrorMessage(error) } } };
        }
      },
      };
    },
  };
}

export const bindDependency = bindPasswordDependency;

export const portableValueProfile = lensoContractRuntime.portableValueProfile;
