/* @generated by lenso-contract-codegen; do not edit. */
import * as lensoContractRuntime from "@lenso/contract-runtime";

export const CAPABILITY_ID = "lenso.auth.phone@1";
export const DESCRIPTOR_VERSION = "1.0.0";
export const PORTABLE = true;
export const CROSS_LANE_TRANSFER = true;

export type Int64 = lensoContractRuntime.Int64;
export type Uint64 = lensoContractRuntime.Uint64;
export type Bytes = lensoContractRuntime.Bytes;
export type Timestamp = lensoContractRuntime.Timestamp;
export type Duration = lensoContractRuntime.Duration;
export type OptionalValue<T> = lensoContractRuntime.OptionalValue<T>;
export type InvocationContext = lensoContractRuntime.InvocationContext;
export type RuntimeFailure = lensoContractRuntime.RuntimeFailure;
export type UnknownDomainError = lensoContractRuntime.UnknownDomainError;
export type StreamEvent<Message, DomainError> = lensoContractRuntime.StreamEvent<Message, DomainError>;
export type StreamSession<Message, DomainError> = lensoContractRuntime.StreamSession<Message, DomainError>;

export interface PasswordLoginRequest {
  device_id: string | null;
  password: string;
  phone: string;
}

export interface PasswordLoginResponse {
  credential: string;
  expires_at: Timestamp;
  masked_phone: string;
  session_id: string;
  subject: string;
}

export interface SetPasswordRequest {
  password: string;
  subject: string;
}

export interface SetPasswordResponse {
  updated: boolean;
}

export interface StartOtpRequest {
  client_ip: string | null;
  phone: string;
  purpose: "login" | "register";
}

export interface StartOtpResponse {
  challenge_id: string;
  debug_code: string | null;
  expires_at: Timestamp;
  resend_after: Timestamp;
}

export interface VerifyOtpRequest {
  challenge_id: string;
  code: string;
  device_id: string | null;
}

export interface VerifyOtpResponse {
  credential: string;
  expires_at: Timestamp;
  masked_phone: string;
  session_id: string;
  subject: string;
}

export type PasswordLoginError = "disabled" | "invalid_credentials" | "invalid_phone" | "rate_limited" | UnknownDomainError;
export type PasswordLoginInvocationError = { readonly kind: "domain"; readonly error: PasswordLoginError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type PasswordLoginResult = { readonly ok: true; readonly value: PasswordLoginResponse } | { readonly ok: false; readonly error: PasswordLoginInvocationError };
export type SetPasswordError = "disabled" | "forbidden" | "invalid_subject" | "not_found" | "weak_password" | UnknownDomainError;
export type SetPasswordInvocationError = { readonly kind: "domain"; readonly error: SetPasswordError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type SetPasswordResult = { readonly ok: true; readonly value: SetPasswordResponse } | { readonly ok: false; readonly error: SetPasswordInvocationError };
export type StartOtpError = "delivery_rejected" | "invalid_phone" | "invalid_purpose" | "rate_limited" | "resend_too_soon" | UnknownDomainError;
export type StartOtpInvocationError = { readonly kind: "domain"; readonly error: StartOtpError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type StartOtpResult = { readonly ok: true; readonly value: StartOtpResponse } | { readonly ok: false; readonly error: StartOtpInvocationError };
export type VerifyOtpError = "disabled" | "expired" | "invalid_challenge" | "invalid_code" | "too_many_attempts" | UnknownDomainError;
export type VerifyOtpInvocationError = { readonly kind: "domain"; readonly error: VerifyOtpError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type VerifyOtpResult = { readonly ok: true; readonly value: VerifyOtpResponse } | { readonly ok: false; readonly error: VerifyOtpInvocationError };
export function encodePasswordLoginRequest(value: PasswordLoginRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodePasswordLoginRequest(wire: string): PasswordLoginRequest { return lensoContractRuntime.decodePortableJson<PasswordLoginRequest>(wire); }
export function encodePasswordLoginResponse(value: PasswordLoginResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodePasswordLoginResponse(wire: string): PasswordLoginResponse { return lensoContractRuntime.decodePortableJson<PasswordLoginResponse>(wire); }
export function encodePasswordLoginError(value: PasswordLoginError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodePasswordLoginError(wire: string): PasswordLoginError { return lensoContractRuntime.decodeDomainError<PasswordLoginError>(wire, ["disabled", "invalid_credentials", "invalid_phone", "rate_limited"]); }

export function encodeSetPasswordRequest(value: SetPasswordRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeSetPasswordRequest(wire: string): SetPasswordRequest { return lensoContractRuntime.decodePortableJson<SetPasswordRequest>(wire); }
export function encodeSetPasswordResponse(value: SetPasswordResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeSetPasswordResponse(wire: string): SetPasswordResponse { return lensoContractRuntime.decodePortableJson<SetPasswordResponse>(wire); }
export function encodeSetPasswordError(value: SetPasswordError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeSetPasswordError(wire: string): SetPasswordError { return lensoContractRuntime.decodeDomainError<SetPasswordError>(wire, ["disabled", "forbidden", "invalid_subject", "not_found", "weak_password"]); }

export function encodeStartOtpRequest(value: StartOtpRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeStartOtpRequest(wire: string): StartOtpRequest { return lensoContractRuntime.decodePortableJson<StartOtpRequest>(wire); }
export function encodeStartOtpResponse(value: StartOtpResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeStartOtpResponse(wire: string): StartOtpResponse { return lensoContractRuntime.decodePortableJson<StartOtpResponse>(wire); }
export function encodeStartOtpError(value: StartOtpError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeStartOtpError(wire: string): StartOtpError { return lensoContractRuntime.decodeDomainError<StartOtpError>(wire, ["delivery_rejected", "invalid_phone", "invalid_purpose", "rate_limited", "resend_too_soon"]); }

export function encodeVerifyOtpRequest(value: VerifyOtpRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeVerifyOtpRequest(wire: string): VerifyOtpRequest { return lensoContractRuntime.decodePortableJson<VerifyOtpRequest>(wire); }
export function encodeVerifyOtpResponse(value: VerifyOtpResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeVerifyOtpResponse(wire: string): VerifyOtpResponse { return lensoContractRuntime.decodePortableJson<VerifyOtpResponse>(wire); }
export function encodeVerifyOtpError(value: VerifyOtpError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeVerifyOtpError(wire: string): VerifyOtpError { return lensoContractRuntime.decodeDomainError<VerifyOtpError>(wire, ["disabled", "expired", "invalid_challenge", "invalid_code", "too_many_attempts"]); }


export interface PhoneClient {
  password_login(request: PasswordLoginRequest, context?: InvocationContext): Promise<PasswordLoginResult>;
  set_password(request: SetPasswordRequest, context?: InvocationContext): Promise<SetPasswordResult>;
  start_otp(request: StartOtpRequest, context?: InvocationContext): Promise<StartOtpResult>;
  verify_otp(request: VerifyOtpRequest, context?: InvocationContext): Promise<VerifyOtpResult>;
}

export interface PhoneProvider {
  password_login(context: InvocationContext, request: PasswordLoginRequest): Promise<PasswordLoginResult>;
  set_password(context: InvocationContext, request: SetPasswordRequest): Promise<SetPasswordResult>;
  start_otp(context: InvocationContext, request: StartOtpRequest): Promise<StartOtpResult>;
  verify_otp(context: InvocationContext, request: VerifyOtpRequest): Promise<VerifyOtpResult>;
}

export type ProviderDispatchOutcome =
  | { readonly kind: "success"; readonly value: unknown }
  | { readonly kind: "domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };

export interface CapabilityProviderDescriptor {
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly operations: ReadonlyArray<string>;
  readonly stream_operations: ReadonlyArray<string>;
  readonly event_operations: ReadonlyArray<string>;
}

export interface CapabilityProviderBinding {
  readonly descriptor: CapabilityProviderDescriptor;
  invokeRequest(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderDispatchOutcome>;
}

function providerErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export function bindPhoneProvider(
  provider: PhoneProvider,
): CapabilityProviderBinding {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["password_login", "set_password", "start_otp", "verify_otp"],
      stream_operations: [],
      event_operations: [],
    },
    async invokeRequest(operation, context, payload) {
      switch (operation) {
      case "password_login": {
        let request: PasswordLoginRequest;
        try {
          request = decodePasswordLoginRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.password_login(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodePasswordLoginResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodePasswordLoginError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "module_failure", detail: providerErrorMessage(error) } };
        }
      }
      case "set_password": {
        let request: SetPasswordRequest;
        try {
          request = decodeSetPasswordRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.set_password(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeSetPasswordResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeSetPasswordError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "module_failure", detail: providerErrorMessage(error) } };
        }
      }
      case "start_otp": {
        let request: StartOtpRequest;
        try {
          request = decodeStartOtpRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.start_otp(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeStartOtpResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeStartOtpError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "module_failure", detail: providerErrorMessage(error) } };
        }
      }
      case "verify_otp": {
        let request: VerifyOtpRequest;
        try {
          request = decodeVerifyOtpRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.verify_otp(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeVerifyOtpResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeVerifyOtpError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "module_failure", detail: providerErrorMessage(error) } };
        }
      }
        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
  };
}

export type Provider = PhoneProvider;
export const bindProvider = bindPhoneProvider;

export const portableValueProfile = lensoContractRuntime.portableValueProfile;
