/* @generated by lenso-contract-codegen; do not edit. */
import * as lensoContractRuntime from "@lenso/contract-runtime";

export const CAPABILITY_ID = "lenso.secrets@1";
export const DESCRIPTOR_VERSION = "1.0.0";
export const DESCRIPTOR_DIGEST = "sha256:8f48068ae97861edffc7b156101cac61522a1d06113b7d054664b77ff781e1bd";
export const PORTABLE = false;
export const CROSS_LANE_TRANSFER = false;

export type Int64 = lensoContractRuntime.Int64;
export type Uint64 = lensoContractRuntime.Uint64;
export type Bytes = lensoContractRuntime.Bytes;
export type Timestamp = lensoContractRuntime.Timestamp;
export type Duration = lensoContractRuntime.Duration;
export type OptionalValue<T> = lensoContractRuntime.OptionalValue<T>;
export type InvocationContext = lensoContractRuntime.InvocationContext;
export type RuntimeFailure = lensoContractRuntime.RuntimeFailure;
export type UnknownDomainError = lensoContractRuntime.UnknownDomainError;
export type StreamEvent<Message, DomainError> = lensoContractRuntime.StreamEvent<Message, DomainError>;
export type StreamSession<Message, DomainError> = lensoContractRuntime.StreamSession<Message, DomainError>;

export interface CapabilityContractReference<Client> extends CapabilityDependencyBinding<Client> {
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly descriptor_digest: string;
  readonly generated_client: string;
  readonly __client?: Client;
}

export interface ResolveRequest {
  reference: string;
}

export interface ResolveResponse {
  value: string;
}

export type ResolveError = "invalid_reference" | "unknown_reference" | UnknownDomainError;
export type ResolveInvocationError = { readonly kind: "domain"; readonly error: ResolveError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type ResolveResult = { readonly ok: true; readonly value: ResolveResponse } | { readonly ok: false; readonly error: ResolveInvocationError };
export function encodeResolveRequest(value: ResolveRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeResolveRequest(wire: string): ResolveRequest { return lensoContractRuntime.decodePortableJson<ResolveRequest>(wire); }
export function encodeResolveResponse(value: ResolveResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeResolveResponse(wire: string): ResolveResponse { return lensoContractRuntime.decodePortableJson<ResolveResponse>(wire); }
export function encodeResolveError(value: ResolveError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeResolveError(wire: string): ResolveError { return lensoContractRuntime.decodeDomainError<ResolveError>(wire, ["invalid_reference", "unknown_reference"]); }


export interface SecretsClient {
  resolve(request: ResolveRequest, context?: InvocationContext): Promise<ResolveResult>;
}

export interface SecretsProvider {
  resolve(context: InvocationContext, request: ResolveRequest): Promise<ResolveResult>;
}

export const SECRETS_CONTRACT: CapabilityContractReference<SecretsClient> = { ...bindSecretsDependency(), capability_id: CAPABILITY_ID, descriptor_version: DESCRIPTOR_VERSION, descriptor_digest: DESCRIPTOR_DIGEST, generated_client: "SecretsClient" };

export type ProviderDispatchOutcome =
  | { readonly kind: "success"; readonly value: unknown }
  | { readonly kind: "domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };

export interface CapabilityProviderDescriptor {
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly operations: ReadonlyArray<string>;
  readonly stream_operations: ReadonlyArray<string>;
  readonly event_operations: ReadonlyArray<string>;
}

export interface CapabilityProviderBinding {
  readonly descriptor: CapabilityProviderDescriptor;
  invokeRequest(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderDispatchOutcome>;
}

function providerErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export function bindSecretsProvider(
  provider: SecretsProvider,
): CapabilityProviderBinding {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["resolve"],
      stream_operations: [],
      event_operations: [],
    },
    async invokeRequest(operation, context, payload) {
      switch (operation) {
      case "resolve": {
        let request: ResolveRequest;
        try {
          request = decodeResolveRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.resolve(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeResolveResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeResolveError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
        }
      }
        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
  };
}

export type Provider = SecretsProvider;
export const bindProvider = bindSecretsProvider;

export type DependencyInvoker = (
  operation: string,
  context: InvocationContext,
  payload: unknown,
) => Promise<ProviderDispatchOutcome>;

export interface CapabilityDependencyBinding<Client> {
  readonly descriptor: CapabilityProviderDescriptor;
  createClient(invoke: DependencyInvoker): Client;
}

function dependencyErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export function bindSecretsDependency(): CapabilityDependencyBinding<SecretsClient> {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["resolve"],
      stream_operations: [],
      event_operations: [],
    },
    createClient(invoke) {
      return {
      async resolve(request, context) {
        let payload: unknown;
        try {
          payload = JSON.parse(encodeResolveRequest(request)) as unknown;
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "protocol_violation", detail: dependencyErrorMessage(error) } } };
        }
        const call = context ?? { requestId: "0" as Uint64, cancelled: false };
        try {
          const outcome = await invoke("resolve", call, payload);
          if (outcome.kind === "success") {
            return { ok: true, value: decodeResolveResponse(JSON.stringify(outcome.value)) };
          }
          if (outcome.kind === "domain") {
            return { ok: false, error: { kind: "domain", error: decodeResolveError(JSON.stringify(outcome.value)) } };
          }
          return { ok: false, error: { kind: "runtime", error: outcome.failure } };
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "plugin_failure", detail: dependencyErrorMessage(error) } } };
        }
      },
      };
    },
  };
}

export const bindDependency = bindSecretsDependency;

export const portableValueProfile = lensoContractRuntime.portableValueProfile;
