/* @generated by lenso-contract-codegen; do not edit. */
import * as lensoContractRuntime from "@lenso/contract-runtime";

export const CAPABILITY_ID = "lenso.message.sms@1";
export const DESCRIPTOR_VERSION = "1.0.0";
export const DESCRIPTOR_DIGEST = "sha256:9f730009bddb72adf66cc6aef67109a187aa5029087661fd58f2c2169b1e6387";
export const PORTABLE = true;
export const CROSS_LANE_TRANSFER = true;

export type Int64 = lensoContractRuntime.Int64;
export type Uint64 = lensoContractRuntime.Uint64;
export type Bytes = lensoContractRuntime.Bytes;
export type Timestamp = lensoContractRuntime.Timestamp;
export type Duration = lensoContractRuntime.Duration;
export type OptionalValue<T> = lensoContractRuntime.OptionalValue<T>;
export type InvocationContext = lensoContractRuntime.InvocationContext;
export type RuntimeFailure = lensoContractRuntime.RuntimeFailure;
export type UnknownDomainError = lensoContractRuntime.UnknownDomainError;
export type StreamEvent<Message, DomainError> = lensoContractRuntime.StreamEvent<Message, DomainError>;
export type StreamSession<Message, DomainError> = lensoContractRuntime.StreamSession<Message, DomainError>;

export interface CapabilityContractReference<Client> extends CapabilityDependencyBinding<Client> {
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly descriptor_digest: string;
  readonly generated_client: string;
  readonly __client?: Client;
}

export interface SendRequest {
  body: string;
  destination: string;
}

export interface SendResponse {
  accepted: boolean;
}

export type SendError = "invalid_destination" | "rejected" | "throttled" | UnknownDomainError;
export type SendInvocationError = { readonly kind: "domain"; readonly error: SendError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type SendResult = { readonly ok: true; readonly value: SendResponse } | { readonly ok: false; readonly error: SendInvocationError };
export function encodeSendRequest(value: SendRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeSendRequest(wire: string): SendRequest { return lensoContractRuntime.decodePortableJson<SendRequest>(wire); }
export function encodeSendResponse(value: SendResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeSendResponse(wire: string): SendResponse { return lensoContractRuntime.decodePortableJson<SendResponse>(wire); }
export function encodeSendError(value: SendError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeSendError(wire: string): SendError { return lensoContractRuntime.decodeDomainError<SendError>(wire, ["invalid_destination", "rejected", "throttled"]); }


export interface SmsClient {
  send(request: SendRequest, context?: InvocationContext): Promise<SendResult>;
}

export interface SmsProvider {
  send(context: InvocationContext, request: SendRequest): Promise<SendResult>;
}

export const SMS_CONTRACT: CapabilityContractReference<SmsClient> = { ...bindSmsDependency(), capability_id: CAPABILITY_ID, descriptor_version: DESCRIPTOR_VERSION, descriptor_digest: DESCRIPTOR_DIGEST, generated_client: "SmsClient" };

export type ProviderDispatchOutcome =
  | { readonly kind: "success"; readonly value: unknown }
  | { readonly kind: "domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };

export interface CapabilityProviderDescriptor {
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly operations: ReadonlyArray<string>;
  readonly stream_operations: ReadonlyArray<string>;
  readonly event_operations: ReadonlyArray<string>;
}

export interface CapabilityProviderBinding {
  readonly descriptor: CapabilityProviderDescriptor;
  invokeRequest(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderDispatchOutcome>;
}

function providerErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export function bindSmsProvider(
  provider: SmsProvider,
): CapabilityProviderBinding {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["send"],
      stream_operations: [],
      event_operations: [],
    },
    async invokeRequest(operation, context, payload) {
      switch (operation) {
      case "send": {
        let request: SendRequest;
        try {
          request = decodeSendRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.send(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeSendResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeSendError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
        }
      }
        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
  };
}

export type Provider = SmsProvider;
export const bindProvider = bindSmsProvider;

export type DependencyInvoker = (
  operation: string,
  context: InvocationContext,
  payload: unknown,
) => Promise<ProviderDispatchOutcome>;

export interface CapabilityDependencyBinding<Client> {
  readonly descriptor: CapabilityProviderDescriptor;
  createClient(invoke: DependencyInvoker): Client;
}

function dependencyErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export function bindSmsDependency(): CapabilityDependencyBinding<SmsClient> {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["send"],
      stream_operations: [],
      event_operations: [],
    },
    createClient(invoke) {
      return {
      async send(request, context) {
        let payload: unknown;
        try {
          payload = JSON.parse(encodeSendRequest(request)) as unknown;
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "protocol_violation", detail: dependencyErrorMessage(error) } } };
        }
        const call = context ?? { requestId: "0" as Uint64, cancelled: false };
        try {
          const outcome = await invoke("send", call, payload);
          if (outcome.kind === "success") {
            return { ok: true, value: decodeSendResponse(JSON.stringify(outcome.value)) };
          }
          if (outcome.kind === "domain") {
            return { ok: false, error: { kind: "domain", error: decodeSendError(JSON.stringify(outcome.value)) } };
          }
          return { ok: false, error: { kind: "runtime", error: outcome.failure } };
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "plugin_failure", detail: dependencyErrorMessage(error) } } };
        }
      },
      };
    },
  };
}

export const bindDependency = bindSmsDependency;

export const portableValueProfile = lensoContractRuntime.portableValueProfile;
