/* @generated by lenso-contract-codegen; do not edit. */
import * as lensoContractRuntime from "@lenso/contract-runtime";

export const CAPABILITY_ID = "lenso.websocket.endpoint@1";
export const DESCRIPTOR_VERSION = "1.0.0";
export const DESCRIPTOR_DIGEST = "sha256:ab8584c9e3f1e1582398521cecedf0b2e9de0c6d29386141dcfc8175c620b798";
export const PORTABLE = true;
export const CROSS_LANE_TRANSFER = true;

export type Int64 = lensoContractRuntime.Int64;
export type Uint64 = lensoContractRuntime.Uint64;
export type Bytes = lensoContractRuntime.Bytes;
export type Timestamp = lensoContractRuntime.Timestamp;
export type Duration = lensoContractRuntime.Duration;
export type OptionalValue<T> = lensoContractRuntime.OptionalValue<T>;
export type InvocationContext = lensoContractRuntime.InvocationContext;
export type RuntimeFailure = lensoContractRuntime.RuntimeFailure;
export type UnknownDomainError = lensoContractRuntime.UnknownDomainError;
export type StreamEvent<Message, DomainError> = lensoContractRuntime.StreamEvent<Message, DomainError>;
export type StreamSession<Message, DomainError> = lensoContractRuntime.StreamSession<Message, DomainError>;

export type ProviderStream<Message, DomainError> = StreamSession<Message, DomainError> | AsyncIterable<Message>;

class ServerOutputStreamInputError extends Error {}

function isAsyncIterable<Message>(value: unknown): value is AsyncIterable<Message> {
  return typeof value === "object" && value !== null && Symbol.asyncIterator in value;
}

function lowerProviderStream<Message, DomainError>(stream: ProviderStream<Message, DomainError>): StreamSession<Message, DomainError> {
  if (!isAsyncIterable<Message>(stream)) return stream;
  const iterator = stream[Symbol.asyncIterator]();
  let cancelled = false;
  return {
    async send() { throw new ServerOutputStreamInputError("server-output stream does not accept inbound messages"); },
    async receive() {
      if (cancelled) return { kind: "terminal", outcome: { ok: true } };
      const next = await iterator.next();
      return next.done
        ? { kind: "terminal", outcome: { ok: true } }
        : { kind: "message", message: next.value };
    },
    async closeSend() {},
    cancel() {
      cancelled = true;
      const closing = iterator.return?.();
      if (closing !== undefined) void Promise.resolve(closing).catch(() => undefined);
    },
  };
}

export interface CapabilityContractReference<Client, Provider extends object, Runtime extends DependencyInvoker = DependencyInvoker> extends CapabilityDependencyBinding<Client, Runtime> {
  readonly kind: "lenso.capability";
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly descriptor_digest: string;
  readonly generated_client: string;
  readonly descriptor: CapabilityProviderDescriptor;
  bindProvider(provider: Provider): CapabilityProviderBinding;
  required(id?: string): CapabilityDependencyDeclaration<Client, "one", Runtime>;
  optional(id?: string): CapabilityDependencyDeclaration<Client, "optional", Runtime>;
  many(id?: string): CapabilityDependencyDeclaration<Client, "many", Runtime>;
  readonly __client?: Client;
  readonly __provider?: Provider;
}

export interface ConnectWebsocketRequest {
  credential?: ConnectWebsocketRequestCredential;
  headers: Array<ConnectWebsocketRequestHeadersItem>;
  path: string;
  path_parameters: Array<ConnectWebsocketRequestPathParametersItem>;
  protocols: Array<string>;
  query?: string;
  request_id: string;
  route_id: string;
}

export interface ConnectWebsocketRequestCredential {
  scheme: string;
  value: string;
}

export interface ConnectWebsocketRequestHeadersItem {
  name: string;
  value: string;
}

export interface ConnectWebsocketRequestPathParametersItem {
  name: string;
  value: string;
}

export interface ConnectWebsocketResponse {
  body?: Bytes;
  code?: number;
  kind: "accept" | "text" | "binary" | "close";
  protocol?: string;
  reason?: string;
  text?: string;
}

export interface DescribeWebsocketRequest {

}

export interface DescribeWebsocketResponse {
  routes: Array<DescribeWebsocketResponseRoutesItem>;
}

export interface DescribeWebsocketResponseRoutesItem {
  path: string;
  route_id: string;
}

export type ConnectWebsocketError = "rejected" | "unauthorized" | "unsupported_protocol" | UnknownDomainError;
export type ConnectWebsocketInvocationError = { readonly kind: "domain"; readonly error: ConnectWebsocketError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type ConnectWebsocketResult = { readonly ok: true; readonly value: StreamSession<ConnectWebsocketResponse, ConnectWebsocketError> } | { readonly ok: false; readonly error: ConnectWebsocketInvocationError };
export type ConnectWebsocketProviderResult = { readonly ok: true; readonly value: ProviderStream<ConnectWebsocketResponse, ConnectWebsocketError> } | { readonly ok: false; readonly error: ConnectWebsocketInvocationError };
export type ConnectWebsocketProviderOutput = AsyncIterable<ConnectWebsocketResponse> | ConnectWebsocketProviderResult | Promise<ConnectWebsocketProviderResult>;
export type DescribeWebsocketError = "invalid_configuration" | UnknownDomainError;
export type DescribeWebsocketInvocationError = { readonly kind: "domain"; readonly error: DescribeWebsocketError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type DescribeWebsocketResult = { readonly ok: true; readonly value: DescribeWebsocketResponse } | { readonly ok: false; readonly error: DescribeWebsocketInvocationError };
export function encodeConnectWebsocketRequest(value: ConnectWebsocketRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeConnectWebsocketRequest(wire: string): ConnectWebsocketRequest { return lensoContractRuntime.decodePortableJson<ConnectWebsocketRequest>(wire); }
export function encodeConnectWebsocketResponse(value: ConnectWebsocketResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeConnectWebsocketResponse(wire: string): ConnectWebsocketResponse { return lensoContractRuntime.decodePortableJson<ConnectWebsocketResponse>(wire); }
export function encodeConnectWebsocketError(value: ConnectWebsocketError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeConnectWebsocketError(wire: string): ConnectWebsocketError { return lensoContractRuntime.decodeDomainError<ConnectWebsocketError>(wire, ["rejected", "unauthorized", "unsupported_protocol"]); }

export function encodeDescribeWebsocketRequest(value: DescribeWebsocketRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeDescribeWebsocketRequest(wire: string): DescribeWebsocketRequest { return lensoContractRuntime.decodePortableJson<DescribeWebsocketRequest>(wire); }
export function encodeDescribeWebsocketResponse(value: DescribeWebsocketResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeDescribeWebsocketResponse(wire: string): DescribeWebsocketResponse { return lensoContractRuntime.decodePortableJson<DescribeWebsocketResponse>(wire); }
export function encodeDescribeWebsocketError(value: DescribeWebsocketError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeDescribeWebsocketError(wire: string): DescribeWebsocketError { return lensoContractRuntime.decodeDomainError<DescribeWebsocketError>(wire, ["invalid_configuration"]); }


export interface EndpointClient {
  connect_websocket(request: ConnectWebsocketRequest, context?: InvocationContext): Promise<ConnectWebsocketResult>;
  describe_websocket(request: DescribeWebsocketRequest, context?: InvocationContext): Promise<DescribeWebsocketResult>;
}

export interface EndpointProvider {
  connect_websocket(context: InvocationContext, request: ConnectWebsocketRequest): ConnectWebsocketProviderOutput;
  describe_websocket(context: InvocationContext, request: DescribeWebsocketRequest): Promise<DescribeWebsocketResult>;
}

export const Endpoint: CapabilityContractReference<EndpointClient, EndpointProvider, InteractionDependencyInvoker> = { kind: "lenso.capability", ...bindEndpointDependency(), capability_id: CAPABILITY_ID, descriptor_version: DESCRIPTOR_VERSION, descriptor_digest: DESCRIPTOR_DIGEST, generated_client: "EndpointClient", descriptor: { capability_id: CAPABILITY_ID, descriptor_version: DESCRIPTOR_VERSION, operations: ["connect_websocket", "describe_websocket"], stream_operations: ["connect_websocket"], event_operations: [] }, bindProvider: bindEndpointProvider, required(id) { return { kind: "lenso.dependency", ...(id === undefined ? {} : { id }), contract: this, cardinality: "one" }; }, optional(id) { return { kind: "lenso.dependency", ...(id === undefined ? {} : { id }), contract: this, cardinality: "optional" }; }, many(id) { return { kind: "lenso.dependency", ...(id === undefined ? {} : { id }), contract: this, cardinality: "many" }; }, };
export const ENDPOINT_CONTRACT = Endpoint;

export type ProviderDispatchOutcome =
  | { readonly kind: "success"; readonly value: unknown }
  | { readonly kind: "domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
export type ProviderStreamActionOutcome =
  | { readonly kind: "accepted" }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
export type ProviderStreamReceiveOutcome =
  | { readonly kind: "message"; readonly value: unknown }
  | { readonly kind: "peer_half_closed" }
  | { readonly kind: "terminal_success" }
  | { readonly kind: "terminal_domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
/** @internal Runtime lowering seam. */
export interface ProviderStreamSessionBinding {
  send(message: unknown): Promise<ProviderStreamActionOutcome>;
  receive(): Promise<ProviderStreamReceiveOutcome>;
  closeSend(): Promise<ProviderStreamActionOutcome>;
  cancel(): void;
}
export type ProviderStreamOpenOutcome =
  | { readonly kind: "opened"; readonly stream: ProviderStreamSessionBinding }
  | { readonly kind: "domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
export type ProviderEventPublishOutcome =
  | { readonly kind: "accepted" }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };

export interface CapabilityProviderDescriptor {
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly operations: ReadonlyArray<string>;
  readonly stream_operations: ReadonlyArray<string>;
  readonly event_operations: ReadonlyArray<string>;
}

/** @internal Runtime lowering seam. */
export interface CapabilityProviderBinding {
  readonly descriptor: CapabilityProviderDescriptor;
  invokeRequest(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderDispatchOutcome>;
  openStream(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderStreamOpenOutcome>;
  publishEvent(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderEventPublishOutcome>;
}

function providerErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export function bindEndpointProvider(
  provider: EndpointProvider,
): CapabilityProviderBinding {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["connect_websocket", "describe_websocket"],
      stream_operations: ["connect_websocket"],
      event_operations: [],
    },
    async invokeRequest(operation, context, payload) {
      switch (operation) {
      case "describe_websocket": {
        let request: DescribeWebsocketRequest;
        try {
          request = decodeDescribeWebsocketRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.describe_websocket(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeDescribeWebsocketResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeDescribeWebsocketError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
        }
      }
        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
    async openStream(operation, context, payload) {
      switch (operation) {
      case "connect_websocket": {
        let request: ConnectWebsocketRequest;
        try {
          request = decodeConnectWebsocketRequest(lensoContractRuntime.encodePortableJson(payload, "stream open request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const provided = provider.connect_websocket(context, request);
          const result = isAsyncIterable<ConnectWebsocketResponse>(provided)
            ? { ok: true as const, value: provided }
            : await provided;
          if (!result.ok) {
            if (result.error.kind === "domain") {
              return { kind: "domain", value: JSON.parse(encodeConnectWebsocketError(result.error.error)) as unknown };
            }
            return { kind: "runtime", failure: result.error.error };
          }
          const stream = lowerProviderStream(result.value);
          const binding: ProviderStreamSessionBinding = {
            async send(message) {
              let decoded: ConnectWebsocketResponse;
              try {
                decoded = decodeConnectWebsocketResponse(lensoContractRuntime.encodePortableJson(message, "stream message"));
              } catch (error) {
                return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
              }
              try {
                await stream.send(decoded);
                return { kind: "accepted" };
              } catch (error) {
                return { kind: "runtime", failure: error instanceof ServerOutputStreamInputError
                  ? { kind: "protocol_violation", detail: providerErrorMessage(error) }
                  : { kind: "plugin_failure", detail: providerErrorMessage(error) } };
              }
            },
            async receive() {
              try {
                const event = await stream.receive();
                if (event.kind === "message") {
                  return { kind: "message", value: JSON.parse(encodeConnectWebsocketResponse(event.message)) as unknown };
                }
                if (event.kind === "peer_half_closed") return { kind: "peer_half_closed" };
                if (event.outcome.ok) return { kind: "terminal_success" };
                return { kind: "terminal_domain", value: JSON.parse(encodeConnectWebsocketError(event.outcome.error)) as unknown };
              } catch (error) {
                return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
              }
            },
            async closeSend() {
              try {
                await stream.closeSend();
                return { kind: "accepted" };
              } catch (error) {
                return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
              }
            },
            cancel() { stream.cancel(); },
          };
          return { kind: "opened", stream: binding };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
        }
      }
        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
    async publishEvent(operation, context, payload) {
      switch (operation) {

        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
  };
}

export type Provider = EndpointProvider;
export const bindProvider = bindEndpointProvider;

export type DependencyInvoker = (
  operation: string,
  context: InvocationContext,
  payload: unknown,
) => Promise<ProviderDispatchOutcome>;

export type InteractionDependencyInvoker = DependencyInvoker & {
  readonly providerInstance: string;
  openStream(operation: string, context: InvocationContext, payload: unknown): Promise<ProviderStreamOpenOutcome>;
  publishEvent(operation: string, context: InvocationContext, payload: unknown): Promise<ProviderEventPublishOutcome>;
};

export interface CapabilityDependencyBinding<Client, Runtime extends DependencyInvoker = DependencyInvoker> {
  readonly descriptor: CapabilityProviderDescriptor;
  createClient(invoke: Runtime): Client;
}

export interface CapabilityDependencyDeclaration<Client, Cardinality extends "one" | "optional" | "many", Runtime extends DependencyInvoker = DependencyInvoker> {
  readonly kind: "lenso.dependency";
  readonly id?: string;
  readonly contract: CapabilityDependencyBinding<Client, Runtime>;
  readonly cardinality: Cardinality;
}

function dependencyErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function dependencyRuntimeError(failure: RuntimeFailure): Error {
  return Object.assign(new Error(`Capability dependency failed: ${failure.kind}`), { failure });
}

function dependencyFailure(error: unknown): RuntimeFailure {
  if (typeof error === "object" && error !== null && "failure" in error) return (error as { failure: RuntimeFailure }).failure;
  return { kind: "plugin_failure", detail: dependencyErrorMessage(error) };
}

export function bindEndpointDependency(): CapabilityDependencyBinding<EndpointClient, InteractionDependencyInvoker> {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["connect_websocket", "describe_websocket"],
      stream_operations: ["connect_websocket"],
      event_operations: [],
    },
    createClient(invoke) {
      return {
      async connect_websocket(request, context) {
        let payload: unknown;
        try {
          payload = JSON.parse(encodeConnectWebsocketRequest(request)) as unknown;
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "protocol_violation", detail: dependencyErrorMessage(error) } } };
        }
        const call = context ?? { requestId: "0" as Uint64, cancelled: false };
        try {
          const outcome = await invoke.openStream("connect_websocket", call, payload);
          if (outcome.kind === "domain") {
            return { ok: false, error: { kind: "domain", error: decodeConnectWebsocketError(JSON.stringify(outcome.value)) } };
          }
          if (outcome.kind === "runtime") {
            return { ok: false, error: { kind: "runtime", error: outcome.failure } };
          }
          const stream = outcome.stream;
          return { ok: true, value: {
            async send(message) {
              const encoded = JSON.parse(encodeConnectWebsocketResponse(message)) as unknown;
              const result = await stream.send(encoded);
              if (result.kind === "runtime") throw dependencyRuntimeError(result.failure);
            },
            async receive() {
              const result = await stream.receive();
              if (result.kind === "message") return { kind: "message", message: decodeConnectWebsocketResponse(JSON.stringify(result.value)) };
              if (result.kind === "peer_half_closed") return { kind: "peer_half_closed" };
              if (result.kind === "terminal_success") return { kind: "terminal", outcome: { ok: true } };
              if (result.kind === "terminal_domain") return { kind: "terminal", outcome: { ok: false, error: decodeConnectWebsocketError(JSON.stringify(result.value)) } };
              throw dependencyRuntimeError(result.failure);
            },
            async closeSend() {
              const result = await stream.closeSend();
              if (result.kind === "runtime") throw dependencyRuntimeError(result.failure);
            },
            cancel() { stream.cancel(); },
          } };
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: dependencyFailure(error) } };
        }
      },
      async describe_websocket(request, context) {
        let payload: unknown;
        try {
          payload = JSON.parse(encodeDescribeWebsocketRequest(request)) as unknown;
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "protocol_violation", detail: dependencyErrorMessage(error) } } };
        }
        const call = context ?? { requestId: "0" as Uint64, cancelled: false };
        try {
          const outcome = await invoke("describe_websocket", call, payload);
          if (outcome.kind === "success") {
            return { ok: true, value: decodeDescribeWebsocketResponse(JSON.stringify(outcome.value)) };
          }
          if (outcome.kind === "domain") {
            return { ok: false, error: { kind: "domain", error: decodeDescribeWebsocketError(JSON.stringify(outcome.value)) } };
          }
          return { ok: false, error: { kind: "runtime", error: outcome.failure } };
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "plugin_failure", detail: dependencyErrorMessage(error) } } };
        }
      },
      };
    },
  };
}

export const bindDependency = bindEndpointDependency;

export const portableValueProfile = lensoContractRuntime.portableValueProfile;
